import { SLANT_LEVEL_COUNT } from "../games/slantCampaign";
import { LIGHTS_OUT_LEVEL_COUNT } from "../games/lightsOutCampaign";
import { sequenceSymmetryArtwork } from "./catalog";
import { foldTreeLightArtwork } from "./catalog";
import { flowRailFunctionArtwork } from "./catalog";
import { iceFleetNumberArtwork } from "./catalog";
import { lazy, type LazyExoticComponent, type ComponentType } from "react";
import type { GameProps } from "./types";
import {
  firstGameArtwork,
  expansionArtwork,
  strategyArtwork,
  discoveryArtwork,
  scienceArtwork,
  planningArtwork,
  classicArtwork,
  networkCodeArtwork,
  regionNumberArtwork,
  strategyPhysicsArtwork,
  optimizationIslandsArtwork,
  bitSpatialArtwork,
  mathRouteCodeArtwork,
  scienceTownArtwork,
  codeEnergySpatialArtwork,
  type GameMeta,
} from "./catalog";
export type GameDefinition = GameMeta & {
  component: LazyExoticComponent<ComponentType<GameProps>>;
};
const original = {
  kind: "original",
  license: "GPL-3.0-only",
  notes: "原创规则实现、关卡和程序化图形；未复制第三方游戏源码。",
} as const;
export const games: GameDefinition[] = [
  {
    id: "light",
    title: "光线实验室",
    subtitle: "调整镜子与光路，让光线点亮目标吧。",
    category: "逻辑思维",
    difficulty: "初级",
    tone: "green",
    levelCount: 12,
    artwork: firstGameArtwork(0),
    source: original,
    component: lazy(() => import("../games/LightLab")),
  },
  {
    id: "robot",
    title: "机器人路线",
    subtitle: "编写指令，带领小机器人抵达终点。",
    category: "编程启蒙",
    difficulty: "初级",
    tone: "purple",
    levelCount: 12,
    artwork: firstGameArtwork(1),
    source: original,
    component: lazy(() => import("../games/RobotRoutes")),
  },
  {
    id: "bridge",
    title: "积木桥梁",
    subtitle: "旋转积木连接桥面，让小旗帜重逢。",
    category: "空间想象",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    artwork: firstGameArtwork(2),
    source: original,
    component: lazy(() => import("../games/BridgeBlocks")),
  },
  {
    id: "slide",
    title: "数字滑块",
    subtitle: "移动空格，让数字一步步回到自己的位置。",
    category: "空间想象",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    artwork: expansionArtwork(0),
    source: original,
    component: lazy(() => import("../games/SlidingTiles")),
  },
  {
    id: "lights-out",
    title: "熄灯谜阵",
    subtitle: "8 章 112 关，从第一盏灯到五阶花园。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: LIGHTS_OUT_LEVEL_COUNT,
    artwork: expansionArtwork(1),
    source: original,
    component: lazy(() => import("../games/LightsOut")),
  },
  {
    id: "sudoku",
    title: "四格数独",
    subtitle: "让每行、每列、每个小方格都恰好容纳 1 到 4。",
    category: "数字推理",
    difficulty: "初级",
    tone: "purple",
    levelCount: 12,
    artwork: expansionArtwork(2),
    source: original,
    component: lazy(() => import("../games/SudokuGarden")),
  },
  {
    id: "memory",
    title: "记忆花园",
    subtitle: "翻开卡片，记住形状，找出藏在花园里的伙伴。",
    category: "记忆观察",
    difficulty: "初级",
    tone: "purple",
    levelCount: 12,
    artwork: expansionArtwork(3),
    source: original,
    component: lazy(() => import("../games/MemoryGarden")),
  },
  {
    id: "mines",
    title: "花园侦探",
    subtitle: "用数字找出石头，让每一块安全土地重见阳光。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: expansionArtwork(4),
    source: original,
    component: lazy(() => import("../games/MinesGarden")),
  },
  {
    id: "hanoi",
    title: "圆盘搬家",
    subtitle: "规划圆盘的旅程，解开经典汉诺塔的递归秘密。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "orange",
    levelCount: 12,
    artwork: expansionArtwork(5),
    source: original,
    component: lazy(() => import("../games/HanoiTowers")),
  },
  {
    id: "nonogram",
    title: "像素逻辑画",
    subtitle: "读懂行列线索，让隐藏的小图案逐格显现。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: strategyArtwork(0),
    source: original,
    component: lazy(() => import("../games/NonogramGarden")),
  },
  {
    id: "boxes",
    title: "推箱花园",
    subtitle: "规划每一次推动，把木箱送到花朵标记上。",
    category: "空间想象",
    difficulty: "中级",
    tone: "purple",
    levelCount: 12,
    artwork: strategyArtwork(1),
    source: original,
    component: lazy(() => import("../games/BoxGarden")),
  },
  {
    id: "connect",
    title: "四子花径",
    subtitle: "预判对手的回应，让四颗棋子连成一条线。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "green",
    levelCount: 12,
    artwork: strategyArtwork(2),
    source: original,
    component: lazy(() => import("../games/FourInARow")),
  },
  {
    id: "reversi",
    title: "翻转花园",
    subtitle: "寻找夹击的位置，用一次落子翻转整个局面。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "orange",
    levelCount: 12,
    artwork: strategyArtwork(3),
    source: original,
    component: lazy(() => import("../games/ReversiGarden")),
  },
  {
    id: "merge",
    title: "2048",
    subtitle: "滑动、合并，一直玩下去，刷新自己的最高分。",
    category: "数字推理",
    difficulty: "中级",
    tone: "orange",
    levelCount: 0,
    endless: true,
    freePlayCaption: "无尽模式 · 本机最高分",
    resumeKey: "playgarden.merge.v1",
    artwork: discoveryArtwork(0),
    source: original,
    component: lazy(() => import("../games/MergeGarden")),
  },
  {
    id: "traffic",
    title: "停车场出口",
    subtitle: "移动挡路的车辆，为目标小车打开出口。",
    category: "空间想象",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: discoveryArtwork(1),
    source: original,
    component: lazy(() => import("../games/TrafficEscape")),
  },

  {
    id: "arithmetic",
    title: "数字工坊",
    subtitle: "组合四个数字与运算符，调配出目标答案。",
    category: "数字推理",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: discoveryArtwork(2),
    source: original,
    component: lazy(() => import("../games/ArithmeticWorkshop")),
  },
  {
    id: "word-search",
    title: "寻词花园",
    subtitle: "在横竖斜向的字格中，找出熟悉的自然词语。",
    category: "记忆观察",
    difficulty: "初级",
    tone: "purple",
    levelCount: 12,
    artwork: discoveryArtwork(3),
    source: original,
    component: lazy(() => import("../games/WordSearchGarden")),
  },
  {
    id: "balance",
    title: "杠杆实验室",
    subtitle: "改变砝码的位置，让重量与距离恰好平衡。",
    category: "科学实验",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    artwork: scienceArtwork(0),
    source: original,
    component: lazy(() => import("../games/BalanceLab")),
  },
  {
    id: "gears",
    title: "齿轮工坊",
    subtitle: "选择齿数与传动方式，让转速和方向都对上。",
    category: "科学实验",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: scienceArtwork(1),
    source: original,
    component: lazy(() => import("../games/GearWorks")),
  },
  {
    id: "one-stroke",
    title: "一笔花园",
    subtitle: "每条小路只走一次，把所有节点串成旅程。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: scienceArtwork(2),
    source: original,
    component: lazy(() => import("../games/OneStrokeGarden")),
  },
  {
    id: "map-colors",
    title: "缤纷地图",
    subtitle: "给相邻区域不同的颜色，用有限颜料完成地图。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "purple",
    levelCount: 12,
    artwork: scienceArtwork(3),
    source: original,
    component: lazy(() => import("../games/MapColors")),
  },
  {
    id: "futoshiki",
    title: "不等号花园",
    subtitle: "读懂大小关系，让每行每列都排列得恰到好处。",
    category: "数字推理",
    difficulty: "中级",
    tone: "purple",
    levelCount: 12,
    artwork: planningArtwork(0),
    source: original,
    component: lazy(() => import("../games/FutoshikiGarden")),
  },
  {
    id: "skyline",
    title: "城市天际线",
    subtitle: "从四个方向数高楼，还原城市的立体轮廓。",
    category: "空间想象",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: planningArtwork(1),
    source: original,
    component: lazy(() => import("../games/SkylineGarden")),
  },
  {
    id: "jugs",
    title: "量水实验室",
    subtitle: "装满、倒空与互倒，用有限容器量出目标体积。",
    category: "科学实验",
    difficulty: "初级",
    tone: "green",
    levelCount: 12,
    artwork: planningArtwork(2),
    source: original,
    component: lazy(() => import("../games/WaterJugLab")),
  },
  {
    id: "river",
    title: "过河伙伴",
    subtitle: "安排船上的乘客，让每位伙伴都平安到达对岸。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    artwork: planningArtwork(3),
    source: original,
    component: lazy(() => import("../games/RiverCrossingGarden")),
  },
  {
    id: "sowing",
    title: "播种花园",
    subtitle: "播撒种子、捕获与额外回合，规划每一步收获。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "orange",
    levelCount: 12,
    artwork: classicArtwork(0),
    source: original,
    component: lazy(() => import("../games/SeedSowing")),
  },
  {
    id: "nim",
    title: "尼姆花园",
    subtitle: "每次只取一堆，用异或思维掌握最后一颗。",
    category: "数字推理",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: classicArtwork(1),
    source: original,
    component: lazy(() => import("../games/NimGarden")),
  },
  {
    id: "peg",
    title: "跳棋独奏",
    subtitle: "跳过并移走棋子，让最后一颗留在目标位置。",
    category: "空间想象",
    difficulty: "中级",
    tone: "purple",
    levelCount: 12,
    artwork: classicArtwork(2),
    source: original,
    component: lazy(() => import("../games/PegSolitaireGarden")),
  },
  {
    id: "knight",
    title: "骑士巡游",
    subtitle: "走出日字形路线，每个格子只拜访一次。",
    category: "空间想象",
    difficulty: "进阶",
    tone: "green",
    levelCount: 12,
    artwork: classicArtwork(3),
    source: original,
    component: lazy(() => import("../games/KnightTourGarden")),
  },
  {
    id: "hashi",
    title: "桥岛连心",
    subtitle: "读懂岛屿数字，用不交叉的桥连接整片群岛。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "green",
    levelCount: 12,
    artwork: networkCodeArtwork(0),
    source: original,
    component: lazy(() => import("../games/HashiGarden")),
  },
  {
    id: "slitherlink",
    title: "数回花环",
    subtitle: "沿格子边画出唯一闭环，让每条线索都满足。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "orange",
    levelCount: 12,
    artwork: networkCodeArtwork(1),
    source: original,
    component: lazy(() => import("../games/SlitherlinkGarden")),
  },
  {
    id: "circuit",
    title: "逻辑电路",
    subtitle: "组合与、或、非逻辑门，让每一种输入都符合目标。",
    category: "编程启蒙",
    difficulty: "中级",
    tone: "purple",
    levelCount: 12,
    artwork: networkCodeArtwork(2),
    source: original,
    component: lazy(() => import("../games/BooleanCircuit")),
  },
  {
    id: "stack-queue",
    title: "栈与队列工坊",
    subtitle: "利用后进先出和先进先出，把货物按目标顺序送达。",
    category: "编程启蒙",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: networkCodeArtwork(3),
    source: original,
    component: lazy(() => import("../games/StackQueueWorkshop")),
  },
  {
    id: "shikaku",
    title: "矩形花园",
    subtitle: "按照面积线索，给每一片土地划出恰好的矩形。",
    category: "空间想象",
    difficulty: "中级",
    tone: "purple",
    levelCount: 200,
    artwork: regionNumberArtwork(0),
    source: original,
    component: lazy(() => import("../games/ShikakuGarden")),
  },
  {
    id: "tents",
    title: "林间帐篷",
    subtitle: "为每棵树安排一顶帐篷，兼顾行列与相邻约束。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 200,
    artwork: regionNumberArtwork(1),
    source: original,
    component: lazy(() => import("../games/TentsGarden")),
  },
  {
    id: "fraction",
    title: "分数拼盘",
    subtitle: "合并与等分有限材料，把每份分数配方装进托盘。",
    category: "数字推理",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    artwork: regionNumberArtwork(2),
    source: original,
    component: lazy(() => import("../games/FractionMosaic")),
  },
  {
    id: "coordinate",
    title: "坐标寻宝",
    subtitle: "用有限向量卡规划航线，收齐宝石并抵达终点。",
    category: "空间想象",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: regionNumberArtwork(3),
    source: original,
    component: lazy(() => import("../games/CoordinateTreasure")),
  },
  {
    id: "hex",
    title: "六角花径",
    subtitle: "在六角格中连接两岸，同时阻挡对手的通路。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "purple",
    levelCount: 12,
    artwork: strategyPhysicsArtwork(0),
    source: original,
    component: lazy(() => import("../games/HexGarden")),
  },
  {
    id: "dots",
    title: "点线花田",
    subtitle: "连边围格，利用额外回合收获更多花田。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: strategyPhysicsArtwork(1),
    source: original,
    component: lazy(() => import("../games/DotsAndBoxes")),
  },
  {
    id: "incline",
    title: "斜坡停车实验室",
    subtitle: "调整高度与摩擦，让滑车刚好停在目标区域。",
    category: "科学实验",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    artwork: strategyPhysicsArtwork(2),
    source: original,
    component: lazy(() => import("../games/InclineLab")),
  },
  {
    id: "buoyancy",
    title: "浮力码头",
    subtitle: "组合浮箱、装载货物，配出目标吃水深度。",
    category: "科学实验",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: strategyPhysicsArtwork(3),
    source: original,
    component: lazy(() => import("../games/BuoyancyDock")),
  },
  {
    id: "untangle",
    title: "花径解结",
    subtitle: "移动花房，把相交的小路整理成清晰的花园。",
    category: "空间想象",
    difficulty: "中级",
    tone: "purple",
    levelCount: 12,
    artwork: optimizationIslandsArtwork(0),
    source: original,
    component: lazy(() => import("../games/UntangleGarden")),
  },
  {
    id: "minimum-network",
    title: "最小连接网",
    subtitle: "用最少的总成本，把所有花园站点连成一体。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: optimizationIslandsArtwork(1),
    source: original,
    component: lazy(() => import("../games/MinimumNetwork")),
  },
  {
    id: "hitori",
    title: "数字留白",
    subtitle: "涂去重复数字，让留下的格子保持相连。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    artwork: optimizationIslandsArtwork(2),
    source: original,
    component: lazy(() => import("../games/HitoriGarden")),
  },
  {
    id: "nurikabe",
    title: "群岛海图",
    subtitle: "按面积培育岛屿，让海水连成一片。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "green",
    levelCount: 12,
    artwork: optimizationIslandsArtwork(3),
    source: original,
    component: lazy(() => import("../games/NurikabeGarden")),
  },
  {
    id: "binary",
    title: "位流快递",
    subtitle: "用有限运算卡变换比特，把目标信号准确送达。",
    category: "编程启蒙",
    difficulty: "中级",
    tone: "purple",
    levelCount: 12,
    artwork: bitSpatialArtwork(0),
    source: original,
    component: lazy(() => import("../games/BinaryCourier")),
  },
  {
    id: "sorting-network",
    title: "排序网络",
    subtitle: "配置比较交换器，让每一种输入都排好顺序。",
    category: "编程启蒙",
    difficulty: "进阶",
    tone: "green",
    levelCount: 12,
    artwork: bitSpatialArtwork(1),
    source: original,
    component: lazy(() => import("../games/SortingNetworkWorkshop")),
  },
  {
    id: "voxel",
    title: "三视方块",
    subtitle: "从三组方向计数，还原看得见与藏起来的方块。",
    category: "空间想象",
    difficulty: "进阶",
    tone: "orange",
    levelCount: 12,
    artwork: bitSpatialArtwork(2),
    source: original,
    component: lazy(() => import("../games/VoxelViews")),
  },
  {
    id: "cube-net",
    title: "立方纸模",
    subtitle: "摆出六个纸面，折成不重叠的立方体。",
    category: "空间想象",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: bitSpatialArtwork(3),
    source: original,
    component: lazy(() => import("../games/CubeNetWorkshop")),
  },
  {
    id: "kakuro",
    title: "和数庭院",
    subtitle: "沿线索填入数字，让横竖每段的和都恰好达标。",
    category: "数字推理",
    difficulty: "进阶",
    tone: "purple",
    levelCount: 12,
    artwork: mathRouteCodeArtwork(0),
    source: original,
    component: lazy(() => import("../games/KakuroGarden")),
  },
  {
    id: "arithmetic-cage",
    title: "算笼工坊",
    subtitle: "填好每行每列，再满足各个笼子的精确运算。",
    category: "数字推理",
    difficulty: "进阶",
    tone: "green",
    levelCount: 12,
    artwork: mathRouteCodeArtwork(1),
    source: original,
    component: lazy(() => import("../games/ArithmeticCageGarden")),
  },
  {
    id: "town-tour",
    title: "巡回探访",
    subtitle: "每座小镇只去一次，算好回家路的最低总路费。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "orange",
    levelCount: 12,
    artwork: mathRouteCodeArtwork(2),
    source: original,
    component: lazy(() => import("../games/TownTour")),
  },
  {
    id: "postman-routes",
    title: "邮差路线",
    subtitle: "每条街都要送到，用最省路费的往返完成投递。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "purple",
    levelCount: 12,
    artwork: mathRouteCodeArtwork(3),
    source: original,
    component: lazy(() => import("../games/PostmanRoutes")),
  },
  {
    id: "conditional-sorter",
    title: "条件分拣",
    subtitle: "编排如果与否则规则，让每一种包裹都送对地方。",
    category: "编程启蒙",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: mathRouteCodeArtwork(4),
    source: original,
    component: lazy(() => import("../games/ConditionalSorter")),
  },
  {
    id: "state-machine-locks",
    title: "状态机门锁",
    subtitle: "读懂状态转移，用有限的输入打开目标门锁。",
    category: "编程启蒙",
    difficulty: "进阶",
    tone: "purple",
    levelCount: 12,
    artwork: mathRouteCodeArtwork(5),
    source: original,
    component: lazy(() => import("../games/StateMachineLocks")),
  },

  {
    id: "parabolic",
    title: "抛物线靶场",
    subtitle: "调整速度，越过障碍，让小球以正确方向穿过目标。",
    category: "科学实验",
    difficulty: "中级",
    tone: "purple",
    levelCount: 12,
    artwork: scienceTownArtwork(0),
    source: original,
    component: lazy(() => import("../games/ParabolicTargets")),
  },
  {
    id: "current-circuit",
    title: "电流实验室",
    subtitle: "探索串并联与分压，让电流和灯泡读数恰好达标。",
    category: "科学实验",
    difficulty: "进阶",
    tone: "green",
    levelCount: 12,
    artwork: scienceTownArtwork(1),
    source: original,
    component: lazy(() => import("../games/CurrentCircuitLab")),
  },
  {
    id: "budget-town",
    title: "预算小镇",
    subtitle: "组合空间设施，让有限游戏币照顾到每一项需求。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    artwork: scienceTownArtwork(2),
    source: original,
    component: lazy(() => import("../games/BudgetTown")),
  },
  {
    id: "concurrent-kitchen",
    title: "并发厨房",
    subtitle: "安排工序与工作台，让等待与并行都恰到好处。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "purple",
    levelCount: 12,
    artwork: scienceTownArtwork(3),
    source: original,
    component: lazy(() => import("../games/ConcurrentKitchen")),
  },
  {
    id: "code-clues",
    title: "码符侦探",
    subtitle: "根据位置与数量反馈，选择真正有信息量的试探。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "purple",
    levelCount: 12,
    artwork: codeEnergySpatialArtwork(0),
    source: original,
    component: lazy(() => import("../games/CodeClues")),
  },
  {
    id: "energy-dispatch",
    title: "储能调度",
    subtitle: "看清供需曲线，把电量、储能和预算安排到合适时刻。",
    category: "科学实验",
    difficulty: "进阶",
    tone: "green",
    levelCount: 12,
    artwork: codeEnergySpatialArtwork(1),
    source: original,
    component: lazy(() => import("../games/EnergyDispatch")),
  },

  {
    id: "rolling-faces",
    title: "滚面旅程",
    subtitle: "追踪立方体每一面，滚过机关与有朝向的出口。",
    category: "空间想象",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: codeEnergySpatialArtwork(2),
    source: original,
    component: lazy(() => import("../games/RollingFaces")),
  },
  {
    id: "shape-mosaic",
    title: "拼片镶嵌",
    subtitle: "旋转与翻面，把每块拼片放进恰好的凹角与空隙。",
    category: "空间想象",
    difficulty: "进阶",
    tone: "orange",
    levelCount: 12,
    artwork: codeEnergySpatialArtwork(3),
    source: original,
    component: lazy(() => import("../games/ShapeMosaic")),
  },
  {
    id: "ice-stops",
    title: "冰原停靠",
    subtitle: "借另一枚冰块刹车，规划滑行与临时停靠。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: iceFleetNumberArtwork(0),
    source: original,
    component: lazy(() => import("../games/IceStops")),
  },
  {
    id: "fleet-logic",
    title: "船队海图",
    subtitle: "读取行列数量和船只片段，推断完整舰队。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "purple",
    levelCount: 12,
    artwork: iceFleetNumberArtwork(1),
    source: original,
    component: lazy(() => import("../games/FleetLogic")),
  },
  {
    id: "carry-letters",
    title: "进位字母",
    subtitle: "同一字母代表同一数字，用逐列进位解开算式。",
    category: "数字推理",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    artwork: iceFleetNumberArtwork(2),
    source: original,
    component: lazy(() => import("../games/CarryLetters")),
  },
  {
    id: "binary-balance",
    title: "双符平衡",
    subtitle: "平衡 A 与 B，避免三连和重复行列。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "purple",
    levelCount: 12,
    artwork: iceFleetNumberArtwork(3),
    source: original,
    component: lazy(() => import("../games/BinaryBalance")),
  },
  {
    id: "pipe-capacity",
    title: "管道配流",
    subtitle: "分配有限流量，在容量与守恒之间找到低成本路线。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "green",
    levelCount: 12,
    artwork: flowRailFunctionArtwork(0),
    source: original,
    component: lazy(() => import("../games/PipeCapacity")),
  },
  {
    id: "railway-timetable",
    title: "列车时刻",
    subtitle: "安排道岔与等待，让两辆列车安全共享路网。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "orange",
    levelCount: 12,
    artwork: flowRailFunctionArtwork(1),
    source: original,
    component: lazy(() => import("../games/RailwayTimetable")),
  },
  {
    id: "function-factory",
    title: "函数工厂",
    subtitle: "定义可复用的小函数，组合出完整有序的笔画。",
    category: "编程启蒙",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: flowRailFunctionArtwork(2),
    source: original,
    component: lazy(() => import("../games/FunctionFactory")),
  },
  {
    id: "compression-post",
    title: "压缩邮局",
    subtitle: "权衡字面包、重复包与词典，让消息无损又紧凑。",
    category: "编程启蒙",
    difficulty: "中级",
    tone: "purple",
    levelCount: 12,
    artwork: flowRailFunctionArtwork(3),
    source: original,
    component: lazy(() => import("../games/CompressionPost")),
  },
  {
    id: "paper-fold",
    title: "折纸打孔",
    subtitle: "折叠纸层后打孔，展开检验每个孔的位置。",
    category: "空间想象",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    artwork: foldTreeLightArtwork(0),
    source: original,
    component: lazy(() => import("../games/PaperFold")),
  },
  {
    id: "tree-rotations",
    title: "树形旋转",
    subtitle: "保持键值顺序，用局部旋转优化搜索树。",
    category: "编程启蒙",
    difficulty: "进阶",
    tone: "green",
    levelCount: 12,
    artwork: foldTreeLightArtwork(1),
    source: original,
    component: lazy(() => import("../games/TreeRotations")),
  },
  {
    id: "spectral-filters",
    title: "理想滤光",
    subtitle: "组合有限滤片，用精确比例调配目标光。",
    category: "科学实验",
    difficulty: "中级",
    tone: "purple",
    levelCount: 12,
    artwork: foldTreeLightArtwork(2),
    source: original,
    component: lazy(() => import("../games/SpectralFilters")),
  },
  {
    id: "wave-studio",
    title: "谐波工作室",
    subtitle: "调节频率、幅度与相位，合成目标谐波。",
    category: "科学实验",
    difficulty: "进阶",
    tone: "green",
    levelCount: 12,
    artwork: foldTreeLightArtwork(3),
    source: original,
    component: lazy(() => import("../games/WaveStudio")),
  },
  {
    id: "memory-routes",
    title: "路线记忆",
    subtitle: "记住路线的转弯与回访，藏起后按顺序重走。",
    category: "记忆观察",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: sequenceSymmetryArtwork(0),
    source: original,
    component: lazy(() => import("../games/MemoryRoutes")),
  },
  {
    id: "rhythm-echo",
    title: "节奏回声",
    subtitle: "读懂节奏变换，用不计时的间隔卡回应。",
    category: "记忆观察",
    difficulty: "中级",
    tone: "purple",
    levelCount: 12,
    artwork: sequenceSymmetryArtwork(1),
    source: original,
    component: lazy(() => import("../games/RhythmEcho")),
  },
  {
    id: "symmetry-repair",
    title: "对称修补",
    subtitle: "遵守镜像与旋转规则，在有限预算内修补图案。",
    category: "空间想象",
    difficulty: "进阶",
    tone: "orange",
    levelCount: 12,
    artwork: sequenceSymmetryArtwork(2),
    source: original,
    component: lazy(() => import("../games/SymmetryRepair")),
  },
  {
    id: "probability-bag",
    title: "概率抽袋",
    subtitle: "设计袋中数量，用精确概率满足抽取条件。",
    category: "数字推理",
    difficulty: "进阶",
    tone: "green",
    levelCount: 12,
    artwork: sequenceSymmetryArtwork(3),
    source: original,
    component: lazy(() => import("../games/ProbabilityBag")),
  },
  {
    id: "slant",
    title: "斜线森林",
    subtitle: "数字指路，斜线成林。300 关无环推理旅程。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "green",
    levelCount: SLANT_LEVEL_COUNT,
    artwork: firstGameArtwork(0),
    resumeKey: "playgarden.slant.v1",
    source: {
      kind: "adapted",
      license: "MIT",
      author: "Simon Tatham 与贡献者",
      url: "https://github.com/notpeter/sgtatham-puzzles/blob/a7c7826bce5cbb9b9c337c11b9b7f8b278e76fba/slant.c",
      commit: "a7c7826bce5cbb9b9c337c11b9b7f8b278e76fba",
      notice: "./slant-LICENCE.txt",
      notes:
        "实际移植 Slant 填盘与线索生成代码；本项目界面、求解器、种子题库与分级。",
    },
    component: lazy(() => import("../games/SlantForest")),
  },
  {
    id: "samegame",
    title: "花簇消除",
    subtitle: "5 章 100 关，借下落与靠拢，让每朵花找到伙伴。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 100,
    resumeKey: "playgarden.samegame.v1",
    artwork: { url: "./samegame-art.webp", position: "50% 50%", size: "cover" },
    source: original,
    component: lazy(() => import("../games/SameGameGarden")),
  },
  {
    id: "pancake",
    title: "煎饼翻排",
    subtitle: "6 章 120 关，翻动上方整叠，把大小排得刚刚好。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "orange",
    levelCount: 120,
    resumeKey: "playgarden.pancake.v1",
    artwork: { url: "./pancake-art.webp", position: "50% 50%", size: "cover" },
    source: original,
    component: lazy(() => import("../games/PancakeKitchen")),
  },
  {
    id: "blackbox",
    title: "星雾探测",
    subtitle: "6 章 84 关，从光束的去向，推理星雾里的秘密。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "purple",
    levelCount: 84,
    resumeKey: "playgarden.blackbox.v1",
    artwork: { url: "./blackbox-art.webp", position: "50% 50%", size: "cover" },
    source: original,
    component: lazy(() => import("../games/BlackboxObservatory")),
  },
  {
    id: "gomoku",
    title: "自由五子棋",
    subtitle: "一黑一白，慢慢想。离线对弈与 24 道棋形练习。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 24,
    freePlay: true,
    freePlayCaption: "15 × 15 · 完整对局",
    resumeKey: "playgarden.gomoku.v1",
    artwork: { url: "./gomoku-art.svg", position: "50% 50%", size: "cover" },
    source: {
      kind: "adapted",
      license: "MIT",
      author: "open-gomoku Contributors",
      workTitle: "open-gomoku",
      url: "https://github.com/tombelieber/gomoku/tree/0d8f81e687a04c729b1dfe5b0ce028295528cc17/engine/src",
      commit: "0d8f81e687a04c729b1dfe5b0ce028295528cc17",
      notice: "./gomoku-LICENSE.txt",
      notes:
        "规则、估值与搜索内核由固定 Rust 源码改编为 TypeScript；本项目重写界面、教学题库、存档和可取消的离线陪练。",
    },
    component: lazy(() => import("../games/GomokuGarden")),
  },
  {
    id: "xiangqi",
    title: "中国象棋",
    subtitle: "隔河对弈，走一步好棋。完整休闲对局与 13 道教学练习。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 13,
    freePlay: true,
    freePlayCaption: "9 路 × 10 行 · 休闲对局",
    resumeKey: "playgarden.xiangqi.v1",
    artwork: { url: "./xiangqi-art.svg", position: "50% 50%", size: "cover" },
    source: {
      kind: "adapted",
      license: "BSD-2-Clause",
      author: "lengyanyu258 / Jeff Hlywa",
      workTitle: "xiangqi.js",
      url: "https://github.com/lengyanyu258/xiangqi.js/tree/f9019ac2303d4b80ef0b82fd0515bfb55a80a62b",
      commit: "f9019ac2303d4b80ef0b82fd0515bfb55a80a62b",
      notice: "./xiangqi-LICENSE.txt",
      notes:
        "实际复用并修补 BSD-2-Clause 规则源码；原创界面、题库与离线入门搜索。重复三次/120 手无吃子按休闲约定和棋，不含完整比赛长将长捉裁决。",
    },
    component: lazy(() => import("../games/XiangqiGarden")),
  },
  {
    id: "cloudrunner",
    title: "云迹跑者",
    subtitle: "跃过矮栏，穿过横梁，在云端路口转弯。6 段入门与无尽漫游。",
    category: "动作反应",
    difficulty: "中级",
    tone: "orange",
    levelCount: 6,
    freePlay: true,
    freePlayCaption: "三道跑酷 · 无尽漫游",
    modeLabels: { free: "无尽漫游", practice: "六段入门" },
    allowUndo: false,
    resumeKey: "playgarden.cloudrunner.v1",
    artwork: {
      url: "./cloudrunner-art.svg",
      position: "50% 50%",
      size: "cover",
    },
    source: {
      kind: "adapted",
      license: "MIT",
      author: "Mark Stent",
      workTitle: "runner",
      url: "https://github.com/markstent/runner/tree/22a0d0dd74f880025559235bf6139a85316da821",
      commit: "22a0d0dd74f880025559235bf6139a85316da821",
      notice: "./cloudrunner-LICENSE.txt",
      notes:
        "实际复用 MIT 动作、轨道生成、碰撞、分数、难度、输入与合成音效模块；新增原创云路画面、90° 转弯、固定步长碰撞和六段教学。不含原项目角色模型或任何商业游戏素材。",
    },
    component: lazy(() => import("../games/CloudrunnerGarden")),
  },
  {
    id: "breakout",
    title: "反弹砖园",
    subtitle: "控制挡板落点，让小球反弹清空花园。12 关原创挑战。",
    category: "动作反应",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    allowUndo: false,
    artwork: { url: "./breakout-art.svg", position: "50% 50%", size: "cover" },
    source: {
      kind: "adapted",
      license: "MIT",
      author: "Jake Gordon and contributors",
      workTitle: "javascript-breakout",
      url: "https://github.com/jakesgordon/javascript-breakout/tree/eed59e2affa9423b93d2ac8ff93061bb88b33284",
      commit: "eed59e2affa9423b93d2ac8ff93061bb88b33284",
      notice: "./breakout-LICENSE.txt",
      notes:
        "真实移植 MIT 线段相交与挡板反弹规则，修正最早碰撞及迭代边界。原创12关、界面和图形；不含原项目图片或 CC BY-ND 音频。",
    },
    component: lazy(() => import("../games/BreakoutGarden")),
  },
  {
    id: "snake",
    title: "贪吃蛇花园",
    subtitle: "吃果实，慢慢长大；给每一次转弯留条路。",
    category: "动作反应",
    difficulty: "中级",
    tone: "green",
    levelCount: 0,
    endless: true,
    allowUndo: false,
    freePlayCaption: "无尽分数局 · 本机最高分",
    resumeKey: "playgarden.snake.v1",
    artwork: { url: "./snake-art.svg", position: "50% 50%", size: "cover" },
    source: {
      kind: "adapted",
      license: "MIT",
      author: "Patrick Gillespie",
      workTitle: "JavaScript-Snake",
      url: "https://github.com/patorjk/JavaScript-Snake/tree/7c80eddde2de6af669e6ae5133ba8ae60a8d7fb9",
      commit: "7c80eddde2de6af669e6ae5133ba8ae60a8d7fb9",
      notice: "./snake-LICENSE.txt",
      notes:
        "实际改编MIT方向编码、移动/尾部腾位及增长碰撞核心；新增安全转向队列、空格枚举食物、原创界面与续玩。不引入上游图片或全局DOM运行时。",
    },
    component: lazy(() => import("../games/SnakeGarden")),
  },
  {
    id: "falling",
    title: "落块花园",
    subtitle: "旋转、落下、消除整行，为下一块留出空间。",
    category: "动作反应",
    difficulty: "中级",
    tone: "green",
    levelCount: 0,
    endless: true,
    allowUndo: false,
    freePlayCaption: "无尽落块 · 本机最高分",
    resumeKey: "playgarden.falling.v1",
    artwork: { url: "./falling-art.svg", position: "50% 50%", size: "cover" },
    source: {
      kind: "adapted",
      license: "MIT",
      author: "Jake Gordon and contributors",
      workTitle: "javascript-tetris",
      url: "https://github.com/jakesgordon/javascript-tetris/tree/e5c0c42f7dac0f3514a55eff656c6e22e95d68ed",
      commit: "e5c0c42f7dac0f3514a55eff656c6e22e95d68ed",
      notice: "./falling-LICENSE.txt",
      notes:
        "真实移植MIT位掩码形状、占格碰撞、锁定与消行核心；修正顶部行清除，新增七袋随机、落点轮廓和暂停续玩。原创界面图形，不引入上游纹理、统计库或音频。",
    },
    component: lazy(() => import("../games/FallingGarden")),
  },
  {
    id: "flood",
    title: "染色花园",
    subtitle: "从一角换色生长，用有限步数连起整个花园。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 100,
    resumeKey: "playgarden.flood.v1",
    artwork: { url: "./flood-art.svg", position: "50% 50%", size: "cover" },
    source: {
      kind: "adapted",
      license: "MIT",
      author: "Simon Tatham and contributors",
      workTitle: "Flood",
      url: "https://github.com/chrisboyle/sgtpuzzles/tree/d1e10eb57dd80af4999e698a9ab31f546e9a0b9d",
      commit: "d1e10eb57dd80af4999e698a9ab31f546e9a0b9d",
      notice: "./flood-LICENCE.txt",
      notes:
        "实际移植 Flood 的队列填色、完成判定与合法动作检查；原创 100 关、界面、最短路提示与存档。",
    },
    component: lazy(() => import("../games/FloodGarden")),
  },
  {
    id: "akari",
    title: "灯照花园",
    subtitle: "放下小灯，照亮每个角落，让光线各行其道。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 36,
    resumeKey: "playgarden.akari.v1",
    artwork: { url: "./akari-art.svg", position: "50% 50%", size: "cover" },
    source: {
      kind: "adapted",
      license: "MIT",
      author: "Simon Tatham and contributors",
      workTitle: "Light Up",
      url: "https://github.com/chrisboyle/sgtpuzzles/tree/d1e10eb57dd80af4999e698a9ab31f546e9a0b9d",
      commit: "d1e10eb57dd80af4999e698a9ab31f546e9a0b9d",
      notice: "./akari-LICENCE.txt",
      notes:
        "实际移植 Light Up 的射线照明、邻灯计数和完整胜利判定；原创 36 关、界面、当前局面提示与存档。",
    },
    component: lazy(() => import("../games/AkariGarden")),
  },
  {
    id: "galaxies",
    title: "星系分区",
    subtitle: "围绕星心分配格子，让每片星系旋转半圈仍重合。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 36,
    resumeKey: "playgarden.galaxies.v1",
    artwork: { url: "./galaxies-art.svg", position: "50% 50%", size: "cover" },
    source: {
      kind: "adapted",
      license: "MIT",
      author: "Simon Tatham and contributors",
      workTitle: "Galaxies",
      url: "https://github.com/chrisboyle/sgtpuzzles/tree/d1e10eb57dd80af4999e698a9ab31f546e9a0b9d",
      commit: "d1e10eb57dd80af4999e698a9ab31f546e9a0b9d",
      notice: "./galaxies-LICENCE.txt",
      notes:
        "实际移植 Galaxies 的对称对应、连通分量、区域中心及完成判定；原创 36 关、界面、当前局面提示与存档。",
    },
    component: lazy(() => import("../games/GalaxiesGarden")),
  },
  {
    id: "magnets",
    title: "磁极拼图",
    subtitle: "让磁铁两极相对，同极相离，读懂边缘的数量线索。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 36,
    resumeKey: "playgarden.magnets.v1",
    artwork: { url: "./magnets-art.svg", position: "50% 50%", size: "cover" },
    source: {
      kind: "adapted",
      license: "MIT",
      author: "Simon Tatham and contributors",
      workTitle: "Magnets",
      url: "https://github.com/chrisboyle/sgtpuzzles/tree/d1e10eb57dd80af4999e698a9ab31f546e9a0b9d",
      commit: "d1e10eb57dd80af4999e698a9ab31f546e9a0b9d",
      notice: "./magnets-LICENCE.txt",
      notes:
        "实际移植 Magnets 的成对极性、行列计数与相邻同极完成判定；原创 36 关、界面、当前局面提示与存档。",
    },
    component: lazy(() => import("../games/MagnetsGarden")),
  },
  {
    id: "signpost",
    title: "箭头路标",
    subtitle: "顺着方向拼接路线，让每个数字找到自己的驿站。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 30,
    resumeKey: "playgarden.signpost.v1",
    artwork: { url: "./signpost-art.svg", position: "50% 50%", size: "cover" },
    source: {
      kind: "adapted", license: "MIT", author: "Simon Tatham and contributors",
      workTitle: "Signpost",
      url: "https://github.com/chrisboyle/sgtpuzzles/tree/d1e10eb57dd80af4999e698a9ab31f546e9a0b9d",
      commit: "d1e10eb57dd80af4999e698a9ab31f546e9a0b9d", notice: "./signpost-LICENCE.txt",
      notes: "移植 Signpost 的八向射线、数字链一致性与完成规则；原创30关、可从中段拼接的界面、当前局面搜索提示与存档。",
    },
    component: lazy(() => import("../games/SignpostGarden")),
  },
  {
    id: "ataxx",
    title: "孢子争园",
    subtitle: "一步复制，两步跳跃，让孢子在花园里连片生长。",
    category: "逻辑思维", difficulty: "中级", tone: "green",
    levelCount: 30, freePlay: true,
    modeLabels: { free: "自由对弈", practice: "成长练习" },
    freePlayCaption: "完整 7 × 7 · 本地轻量电脑",
    resumeKey: "playgarden.ataxx.v1",
    artwork: { url: "./ataxx-art.svg", position: "50% 50%", size: "cover" },
    source: {
      kind: "adapted", license: "MIT", author: "kz04px", workTitle: "libataxx",
      url: "https://github.com/kz04px/libataxx/tree/4226c26dd11a1f74be708882ece6fd9dc96c767b",
      commit: "4226c26dd11a1f74be708882ece6fd9dc96c767b", notice: "./ataxx-LICENSE.txt",
      notes: "实际移植 MIT libataxx 的复制、跳跃、八邻转化、无步跳过及终局规则；原创30关、完整本地AI对局、确认预览与可取消分析。",
    },
    component: lazy(() => import("../games/AtaxxGarden")),
  },
  {
    id: "loopover",
    title: "环移拼盘",
    subtitle: "18 关行列交织，把一整条线绕回自己的家。",
    category: "空间想象",
    difficulty: "中级",
    tone: "green",
    levelCount: 18,
    resumeKey: "playgarden.loopover.v1",
    artwork: { url: "./loopover-art.svg", position: "50% 50%", size: "cover" },
    source: {
      kind: "adapted",
      license: "MIT",
      author: "Janis Pritzkau",
      workTitle: "Loopover",
      url: "https://github.com/janispritzkau/loopover/blob/e4da7c57841e71beb5035bd4025c66216eec2b69/src/game/board.ts",
      commit: "e4da7c57841e71beb5035bd4025c66216eec2b69",
      notice: "./loopover-LICENSE.txt",
      notes: "实际改编整行、整列循环位移内核；原创中文界面、18 关、预览、提示路线、存档与程序化图形。",
    },
    component: lazy(() => import("../games/LoopoverGarden")),
  },
  {
    id: "set-trio", title: "三卡共鸣",
    subtitle: "选出全同或全异的三张牌，让四种属性一起共鸣。",
    category: "逻辑思维", difficulty: "中级", tone: "purple",
    levelCount: 18, resumeKey: "playgarden.set-trio.v1",
    artwork: { url: "./set-trio-art.svg", position: "50% 50%", size: "cover" },
    source: { kind: "original", license: "GPL-3.0-only", notes: "通用三值属性规则的原创实现；原创18个教学牌局、四项预览、当前余牌分组提示、可撤销收牌与经过校验的本机存档。与商业SET品牌无关联。" },
    component: lazy(() => import("../games/SetTrio")),
  },
  {
    id: "numberlink", title: "彩线连园",
    subtitle: "连起同符号伙伴，让彩线铺满整座花园。",
    category: "逻辑思维", difficulty: "中级", tone: "green",
    levelCount: 15, resumeKey: "playgarden.numberlink.v1",
    artwork: { url: "./numberlink-art.svg", position: "center", size: "cover" },
    source: { kind: "original", license: "GPL-3.0-only", notes: "原创配对路径规则实现、15个手作布局与SVG插画；未移植第三方源码，所有规则正确解法均有效。" },
    component: lazy(() => import("../games/NumberlinkGarden")),
  },
  {
    id: "bubble-shooter", title: "泡泡弹射",
    subtitle: "12 关轻轻瞄准，借墙反弹，让同色泡泡相遇。",
    category: "动作反应", difficulty: "中级", tone: "green",
    levelCount: 12, resumeKey: "playgarden.bubble-shooter.v1",
    artwork: { url: "./bubble-shooter-art.svg", position: "50% 50%", size: "cover" },
    source: { kind: "original", license: "GPL-3.0-only", notes: "通用泡泡弹射规则的原创实现：射线碰撞、墙壁反弹、六角吸附、至少三颗同色连组消除与悬空掉落；原创12关、有限队列、落点预览、启发式提示、可撤销存档和矢量图形。无外部游戏代码或素材。" },
    component: lazy(() => import("../games/BubbleShooterGarden")),
  },
  {
    id: "frog-crossing", title: "池塘过客",
    subtitle: "等车流、搭木筏，把每位伙伴送到花叶上。",
    category: "动作反应", difficulty: "中级", tone: "green",
    levelCount: 12, resumeKey: "playgarden.frog-crossing.v1", allowUndo: false,
    artwork: { url: "./frog-crossing-art.svg", position: "center", size: "cover" },
    source: { kind: "original", license: "GPL-3.0-only", notes: "原创实时过河实现、12 个独立关卡与程序化图形；未复制第三方游戏源码或资源。" },
    component: lazy(() => import("../games/FrogCrossingGarden")),
  },
  {
    id: "lunar-landing", title: "月面着陆",
    subtitle: "掌握推力与惯性，带着月面小船轻轻落下。",
    category: "科学实验", difficulty: "中级", tone: "purple",
    levelCount: 12, allowUndo: false, resumeKey: "playgarden.lunar-landing.v1",
    artwork: { url: "./lunar-landing-art.svg", position: "center", size: "cover" },
    source: { kind: "original", license: "GPL-3.0-only", notes: "通用重力、惯性、推力、燃料与低速着陆规则的原创实时实现；原创12个训练场、中文界面与SVG图形。未移植第三方源码或素材；侧风与可变重力是明确标注的虚构训练条件。" },
    component: lazy(() => import("../games/LunarLanding")),
  },
  {
    id: "chain-bloom", title: "连锁花火",
    subtitle: "选一个好时机，让一朵花火接成满园繁星。",
    category: "动作反应", difficulty: "初级", tone: "green",
    levelCount: 12, allowUndo: false, resumeKey: "playgarden.chain-bloom.v1",
    artwork: { url: "./chain-bloom-art.svg", position: "center", size: "cover" },
    source: { kind: "original", license: "GPL-3.0-only", notes: "原创连续几何连锁规则实现、12 个手写布局与 SVG 图形；未复制第三方游戏源码或素材。" },
    component: lazy(() => import("../games/ChainBloom")),
  },
  {
    id: "bloom-tap", title: "花田快拍",
    subtitle: "轻点花朵收花信，让红衣瓢虫好好歇一会。",
    category: "动作反应", difficulty: "初级", tone: "green",
    levelCount: 12, allowUndo: false, resumeKey: "playgarden.bloom-tap.v1",
    artwork: { url: "./bloom-tap-art.svg", position: "center", size: "cover" },
    source: { kind: "original", license: "GPL-3.0-only", notes: "原创九格视觉反应规则、12个手写来客时序与SVG图形；轻点花朵并避开瓢虫，支持悠闲速度和安全暂停。未使用外部代码或素材。" },
    component: lazy(() => import("../games/BloomTapGarden")),
  },
  {
    id: "word-ladder", title: "变词小径",
    subtitle: "每次换一个字母，沿着公开词本走到目标词。",
    category: "逻辑思维", difficulty: "初级", tone: "green",
    levelCount: 12, resumeKey: "playgarden.word-ladder.v1",
    artwork: { url: "./word-ladder-cover.svg", position: "center", size: "cover" },
    source: { kind: "original", license: "GPL-3.0-only", notes: "经典变词阶梯规则的原创实现；12 关词本、中文释义、界面与 SVG 均为本项目原创，无外部词典、图片或移植源码。" },
    component: lazy(() => import("../games/WordLadderGarden")),
  },
  {
    id: "freecell-garden", title: "空位纸牌",
    subtitle: "先留一个空位，再让四种花色依次回家。",
    category: "逻辑思维", difficulty: "中级", tone: "green",
    levelCount: 12, resumeKey: "playgarden.freecell-garden.v1",
    artwork: { url: "./freecell-garden-art.svg", position: "center", size: "cover" },
    source: { kind: "original", license: "GPL-3.0-only", notes: "通用 FreeCell 规则的原创单张移动实现；12 个手作教学牌局使用四花色 A–3/4/5/6 小牌组（12–24 张），包含牌列、单张空位、同花色升序归位、全部合法落点预览、可撤销动作重放存档及原创 SVG。并非完整 52 张牌模式；未复制第三方源码或素材。" },
    component: lazy(() => import("../games/FreecellGarden")),
  },
  {
    id: "star-sentry", title: "星门守望",
    subtitle: "横移瞄准，躲开反击，守护十二段宁静归途。",
    category: "动作反应", difficulty: "初级", tone: "purple",
    levelCount: 12, allowUndo: false, resumeKey: "playgarden.star-sentry.v1",
    artwork: { url: "./star-sentry-art.svg", position: "center", size: "cover" },
    source: { kind: "original", license: "GPL-3.0-only", notes: "原创编队射击实现、12 个有限关卡与程序化 SVG；未复制第三方游戏源码或商业素材。" },
    component: lazy(() => import("../games/StarSentry")),
  },
  {
    id: "petal-words", title: "花瓣猜词",
    subtitle: "猜一个字母，展开所有位置，拼好十二封花信。",
    category: "逻辑思维", difficulty: "初级", tone: "green",
    levelCount: 12, resumeKey: "playgarden.petal-words.v1",
    artwork: { url: "./petal-words-art.svg", position: "center", size: "cover" },
    source: { kind: "original", license: "GPL-3.0-only", notes: "原创有限字母猜词实现，12封词语花信、中文线索与SVG插画；重复字母一次全开，错误消耗花瓣，支持明示成本的提示和撤销。无外部词典、代码或素材。" },
    component: lazy(() => import("../games/PetalWords")),
  },
  {
    "id": "color-tubes",
    "title": "彩珠归管",
    "subtitle": "借用空管，把彩珠整理成一管一种颜色。",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 8,
    "allowUndo": true,
    "artwork": {
      "url": "./color-tubes-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创彩珠分类规则实现、八个教学布局与 SVG 图形；未复制第三方源码或素材。"
    },
    "component": lazy(() => import("../games/ColorTubes"))
  },
  {
    "id": "pipe-turns",
    "title": "水管转转",
    "subtitle": "旋转弯管与三通，让每朵花喝到水，不留一个漏口。",
    "category": "空间想象",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 10,
    "artwork": {
      "url": "./pipe-turns-art.svg",
      "position": "50% 50%",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创水管方向规则实现、十个网络关卡与 SVG 图形；未复制第三方源码。"
    },
    "component": lazy(() => import("../games/PipeTurns"))
  },
  {
    "id": "chomp-garden",
    "title": "饼干陷阱",
    "subtitle": "拿走一口，留下最后的苦杏仁",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "orange",
    "levelCount": 8,
    "artwork": {
      "url": "./chomp-garden-art.svg",
      "position": "center",
      "size": "cover"
    },
    "allowUndo": true,
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创 Chomp 规则实现、八张有限教学棋盘、精确本地电脑、中文说明与 SVG 插画；未复制第三方源码或关卡。"
    },
    "component": lazy(() => import("../games/ChompGarden"))
  },
  {
    "id": "rolling-block",
    "title": "翻滚石桥",
    "subtitle": "改变长石柱的姿态，稳稳站上终点",
    "category": "空间想象",
    "difficulty": "中级",
    "tone": "purple",
    "levelCount": 8,
    "artwork": {
      "url": "./rolling-block-art.svg",
      "position": "center",
      "size": "cover"
    },
    "allowUndo": true,
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创长方柱翻滚引擎、八张不同石桥、姿态搜索提示、中文说明与 SVG 插画；未复制第三方源码或关卡。"
    },
    "component": lazy(() => import("../games/RollingBlockGarden"))
  },
  {
    "id": "tile-pairs",
    "title": "叠牌寻对",
    "subtitle": "先找自由的一侧，再把相同花牌成对收起。",
    "category": "空间想象",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 8,
    "allowUndo": true,
    "artwork": {
      "url": "./tile-pairs-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创麻将接龙自由牌判定、八个叠牌教学布局与 SVG 图形；未复制第三方源码或素材。"
    },
    "component": lazy(() => import("../games/TilePairs"))
  },
  {
    "id": "matchstick-equations",
    "title": "火柴等式",
    "subtitle": "拿起一根，放下一个答案：移动火柴修好数码等式。",
    "category": "数字推理",
    "difficulty": "中级",
    "tone": "orange",
    "levelCount": 10,
    "artwork": {
      "url": "./matchstick-equations-art.svg",
      "position": "50% 50%",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创七段火柴移动规则实现、十个教学关卡与 SVG 图形；未复制第三方源码。"
    },
    "component": lazy(() => import("../games/MatchstickEquations"))
  },
  {
    "id": "star-battle",
    "title": "星星布阵",
    "subtitle": "每行、每列、每片区域一颗星，彼此留出距离。",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 10,
    "artwork": {
      "url": "./star-battle-art.svg",
      "position": "50% 50%",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创规则实现、10 份区域星图、中文界面和 SVG 插画；经典星星布阵规则，未复制第三方源码、关卡或素材。"
    },
    "component": lazy(() => import("../games/StarBattle"))
  },
  {
    "id": "domino-trail",
    "title": "骨牌接龙",
    "subtitle": "让相同点数相接，把所有骨牌排成不断的小径。",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "orange",
    "levelCount": 8,
    "allowUndo": true,
    "artwork": {
      "url": "./domino-trail-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创双端骨牌接龙实现、八个有限点数牌局与 SVG 图形；未复制第三方源码或素材。"
    },
    "component": lazy(() => import("../games/DominoTrail"))
  },
  {
    "id": "frog-swap",
    "title": "青蛙换岸",
    "subtitle": "只向前走或跳过异色伙伴，让两队青蛙交换岸边。",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 9,
    "allowUndo": true,
    "artwork": {
      "url": "./frog-swap-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创蛙蟾换位规则实现、九个教学队形与 SVG 图形；未复制第三方源码或素材。"
    },
    "component": lazy(() => import("../games/FrogSwap"))
  },
  {
    "id": "three-morris",
    "title": "三子移阵",
    "subtitle": "三颗棋子，沿线移动，连成花行",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 8,
    "artwork": {
      "url": "./three-morris-art.svg",
      "position": "center",
      "size": "cover"
    },
    "allowUndo": true,
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创三子棋规则与七层本地搜索、八道战术残局、中文说明及 SVG 插画；未复制第三方源码或关卡。"
    },
    "component": lazy(() => import("../games/ThreeMorrisGarden"))
  },
  {
    "id": "fox-hounds",
    "title": "林间追逐",
    "subtitle": "狐狸能后退，猎犬只能向前",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 8,
    "artwork": {
      "url": "./fox-hounds-art.svg",
      "position": "center",
      "size": "cover"
    },
    "allowUndo": true,
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创狐狸猎犬对弈引擎、六层本地电脑、八道有限逃脱残局、中文说明及 SVG 插画；未复制第三方源码或关卡。"
    },
    "component": lazy(() => import("../games/FoxHoundsGarden"))
  },
  {
    "id": "solo-chess",
    "title": "棋子独奏",
    "subtitle": "每一步必须吃子，让车、象、马和王接力到最后一枚。",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 10,
    "artwork": {
      "url": "./solo-chess-art.svg",
      "position": "50% 50%",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创混合棋子吃子谜题实现、10 个关卡及 SVG 插画；使用国际象棋运动几何，无双方对弈、无将军；未复制第三方代码、关卡或素材。"
    },
    "component": lazy(() => import("../games/SoloChess"))
  },
  {
    "id": "scene-differences",
    "title": "找不同花园",
    "subtitle": "并排看两幅小花园，找出悄悄发生的五处变化。",
    "category": "记忆观察",
    "difficulty": "初级",
    "tone": "green",
    "levelCount": 8,
    "artwork": {
      "url": "./scene-differences-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创场景差异规则、八幅配对花园、SVG物件和中文说明；没有外部图片或游戏源码。"
    },
    "component": lazy(() => import("../games/SceneDifferences"))
  },
  {
    "id": "cipher-letters",
    "title": "密码花信",
    "subtitle": "把字母一一对应，解开藏在花信里的英文短句。",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "orange",
    "levelCount": 8,
    "artwork": {
      "url": "./cipher-letters-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创一一替换密码实现、八封自编英文花信、中文线索与 SVG 插画；无外部引语、词典或游戏源码。"
    },
    "component": lazy(() => import("../games/CipherLetters"))
  },
  {
    "id": "crossword-garden",
    "title": "交叉词园",
    "subtitle": "读中文线索，把英文单词填进彼此相交的词格。",
    "category": "逻辑思维",
    "difficulty": "初级",
    "tone": "green",
    "levelCount": 8,
    "artwork": {
      "url": "./crossword-garden-art.svg",
      "position": "50% 50%",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创交叉填词规则、八个词格关卡、中文线索与 SVG 图形；未复制第三方源码。"
    },
    "component": lazy(() => import("../games/CrosswordGarden"))
  },
  {
    "id": "cloud-stack",
    "title": "云端叠楼",
    "subtitle": "看准重合的一瞬间，让每一层都稳稳留下来。",
    "category": "动作反应",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 8,
    "allowUndo": false,
    "artwork": {
      "url": "./cloud-stack-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创实时重叠裁切叠楼玩法、八个有限训练场与 SVG 插画；无第三方源码或素材。"
    },
    "component": lazy(() => import("../games/CloudStack"))
  },
  {
    "id": "story-sequence",
    "title": "故事排序",
    "subtitle": "移动原创句条，用时间与因果把小故事连接起来。",
    "category": "逻辑思维",
    "difficulty": "初级",
    "tone": "orange",
    "levelCount": 8,
    "artwork": {
      "url": "./story-sequence-art.svg",
      "position": "50% 50%",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创句条排序实现、八篇中文故事、因果反馈与 SVG 图形；未复制第三方源码。"
    },
    "component": lazy(() => import("../games/StorySequence"))
  },
  {
    "id": "garden-links",
    "title": "花径连连看",
    "subtitle": "画一条最多拐两次弯的空路，把相同花牌连起来。",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 8,
    "artwork": {
      "url": "./garden-links-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创两次转弯连线消牌规则、八个固定布局、当前局面搜索提示与 SVG 插画；无第三方源码或素材。"
    },
    "component": lazy(() => import("../games/GardenLinks"))
  },
  {
    "id": "gravity-maze",
    "title": "重力回廊",
    "subtitle": "旋转重力，拾取钥匙、打开门，让小球安全回家。",
    "category": "空间想象",
    "difficulty": "中级",
    "tone": "purple",
    "levelCount": 8,
    "artwork": {
      "url": "./gravity-maze-art.svg",
      "position": "50% 50%",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创重力转向、钥匙门与落点规则，八个地图及 SVG 图形；未复制第三方源码。"
    },
    "component": lazy(() => import("../games/GravityMaze"))
  },
  {
    "id": "falling-rocks",
    "title": "落石矿洞",
    "subtitle": "从侧面挖开支撑土，躲开落石，采齐宝石安全出洞。",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "orange",
    "levelCount": 8,
    "artwork": {
      "url": "./falling-rocks-art.svg",
      "position": "50% 50%",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创回合制挖掘、落石支撑规则，八个矿洞与 SVG 图形；未复制第三方源码。"
    },
    "component": lazy(() => import("../games/FallingRocks"))
  },
  {
    "id": "pyramid-cards",
    "title": "金字塔纸牌",
    "subtitle": "拆开层层覆盖，让露出的纸牌结成十三点搭档。",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 8,
    "artwork": {
      "url": "./pyramid-cards-art.svg",
      "position": "50% 50%",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创十三点金字塔规则实现、8 个微型教学牌组及 SVG；非完整随机纸牌局，无第三方代码或牌面素材。"
    },
    "component": lazy(() => import("../games/PyramidCards"))
  },
  {
    "id": "golf-cards",
    "title": "逐张纸牌",
    "subtitle": "让相邻点数接力，珍惜有限储备，清空整条纸牌长廊。",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "purple",
    "levelCount": 8,
    "artwork": {
      "url": "./golf-cards-art.svg",
      "position": "50% 50%",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创邻数废牌接龙规则实现、8 个公开储备顺序的微型教学牌组与 SVG；A/K 不循环，无第三方代码或牌面。"
    },
    "component": lazy(() => import("../games/GolfCards"))
  },
  {
    "id": "dice-combinations",
    "title": "骰子组合",
    "subtitle": "保留、重投与分配栏目，在公开固定骰序中拼出高分组合。",
    "category": "数字推理",
    "difficulty": "中级",
    "tone": "orange",
    "levelCount": 8,
    "artwork": {
      "url": "./dice-combinations-art.svg",
      "position": "50% 50%",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创五骰保留重投及栏目分配规则、8 个公开固定骰序教学场景与 SVG；明确非随机，无金钱或下注，无第三方素材。"
    },
    "component": lazy(() => import("../games/DiceCombinations"))
  },
  {
    "id": "river-pong",
    "title": "河畔乒乓",
    "subtitle": "横向移动球拍，借拍面与边墙，把小球送过对岸。",
    "category": "动作反应",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 8,
    "allowUndo": false,
    "artwork": {
      "url": "./river-pong-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创球拍对打引擎、八个有限计分练习、速度受限的本地电脑与 SVG 插画；无第三方游戏源码或素材。"
    },
    "component": lazy(() => import("../games/RiverPong"))
  },
  {
    "id": "hexapawn",
    "title": "小兵冲线",
    "subtitle": "向前一步、斜吃一步，与聪明的对手争夺冲线和封锁。",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 8,
    "artwork": {
      "url": "./hexapawn-art.svg",
      "position": "50% 50%",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创双向小兵规则、精确本地对弈算法、8 个 3×3/4×4 战术局面与 SVG；有直走、斜吃、冲线和无着法胜负，无第三方棋谱或源码。"
    },
    "component": lazy(() => import("../games/Hexapawn"))
  },
  {
    "id": "mini-golf",
    "title": "草地推杆",
    "subtitle": "调整角度与力度，绕过花坛，把小球轻轻送进洞口。",
    "category": "科学实验",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 8,
    "artwork": {
      "url": "./mini-golf-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创平面推杆、摩擦与反弹模型、八个果岭、轨迹提示及 SVG 图形；无第三方游戏代码或素材。"
    },
    "component": lazy(() => import("../games/MiniGolf"))
  },
  {
    "id": "fence-race",
    "title": "围栏竞走",
    "subtitle": "走一步，筑一墙，为彼此留路，为自己争先。",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 8,
    "allowUndo": true,
    "artwork": {
      "url": "./fence-race-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创 5×5 围栏竞走变体、八课残局、局部电脑与 SVG；无第三方源码或关卡。"
    },
    "component": lazy(() => import("../games/FenceRace"))
  },
  {
    "id": "amazon-garden",
    "title": "箭羽争地",
    "subtitle": "一步一箭，划出花园，给自己留下转身的余地。",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "purple",
    "levelCount": 8,
    "allowUndo": true,
    "artwork": {
      "url": "./amazon-garden-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创 5×5 单子 Amazons 教学变体、八个战术布局、局部电脑与 SVG；无第三方源码或关卡。"
    },
    "component": lazy(() => import("../games/AmazonGarden"))
  },
  {
    "id": "dual-rescue",
    "title": "双伴救援",
    "subtitle": "一位涉水，一位走热地，替伙伴打开回家的门。",
    "category": "逻辑思维",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 8,
    "allowUndo": true,
    "artwork": {
      "url": "./dual-rescue-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创互补能力合作规划、八张开关踏板地图、有限状态提示与 SVG；无第三方代码或关卡。"
    },
    "component": lazy(() => import("../games/DualRescue"))
  },
  {
    "id": "balance-sculpture",
    "title": "平衡雕塑",
    "subtitle": "让每层承住上方的重量，搭出轻巧悬挑的雕塑。",
    "category": "科学实验",
    "difficulty": "进阶",
    "tone": "orange",
    "levelCount": 8,
    "allowUndo": true,
    "artwork": {
      "url": "./balance-sculpture-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创逐界面合重心静力模型、八个有限积木悬挑谜题、偏心配重与 SVG；无第三方源码或素材。"
    },
    "component": lazy(() => import("../games/BalanceSculpture"))
  },
  {
    "id": "maze-chase",
    "title": "星豆迷宫",
    "subtitle": "观察巡逻下一步，收齐星豆，再安全走到出口。",
    "category": "动作反应",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 8,
    "artwork": {
      "url": "./maze-chase-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创回合制追逐规则、八张不同拓扑迷宫及 SVG 图画；固定巡逻而非实时追踪 AI，无第三方素材。"
    },
    "component": lazy(() => import("../games/MazeChase"))
  },
  {
    "id": "cloud-hop",
    "title": "云朵弹跳",
    "subtitle": "在重力中左右飞，真正落上每朵云，跳到云海最高处。",
    "category": "动作反应",
    "difficulty": "中级",
    "tone": "purple",
    "levelCount": 8,
    "artwork": {
      "url": "./cloud-hop-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创竖向平台跳跃物理、八个建设性云梯课程、小鸟和云景 SVG；无外部素材。"
    },
    "allowUndo": false,
    "component": lazy(() => import("../games/CloudHop"))
  },
  {
    "id": "pinball-garden",
    "title": "弹珠花台",
    "subtitle": "用固定左右挡板接住落球，点亮花鼓，完成回击乐章。",
    "category": "动作反应",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 8,
    "artwork": {
      "url": "./pinball-garden-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创重力弹珠、固定线段挡板和花鼓碰撞规则、八种球台布局及 SVG；明确采用玩具物理，无第三方素材。"
    },
    "allowUndo": false,
    "component": lazy(() => import("../games/PinballGarden"))
  },
  {
    "id": "jigsaw-garden",
    "title": "花园拼图",
    "subtitle": "自由移动互补凹凸拼片，旋转归位，拼回八幅原创小风景。",
    "category": "空间想象",
    "difficulty": "初级",
    "tone": "orange",
    "levelCount": 8,
    "artwork": {
      "url": "./jigsaw-garden-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创自由摆放图片拼图、互补凹凸边、八幅独立构图 SVG 风景和关卡；无外部图片或第三方源码。"
    },
    "component": lazy(() => import("../games/JigsawGarden"))
  },
  {
    "id": "interval-notes",
    "title": "音程阶梯",
    "subtitle": "看音名、听两音，把起点和终点一起数进音程。",
    "category": "科学实验",
    "difficulty": "初级",
    "tone": "purple",
    "levelCount": 8,
    "artwork": {
      "url": "./interval-notes-art.svg",
      "position": "50% 50%",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创音程级数辨认规则、八课三题练习、公开音阶位置图、正弦波合成与 SVG 图形；未复制第三方源码或录音。"
    },
    "component": lazy(() => import("../games/IntervalNotes"))
  },
  {
    "id": "pendulum-push",
    "title": "摆钟节拍",
    "subtitle": "在摆锤经过中央时轻推，让左右钟声接力，别让摆幅失控。",
    "category": "科学实验",
    "difficulty": "中级",
    "tone": "orange",
    "levelCount": 8,
    "allowUndo": false,
    "artwork": {
      "url": "./pendulum-push-art.svg",
      "position": "50% 50%",
      "size": "cover"
    },
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创阻尼摆钟物理、定向脉冲规则、八个节拍关卡与 SVG 图形；未复制第三方游戏源码或素材。"
    },
    "component": lazy(() => import("../games/PendulumPush"))
  },
  {
    "id": "perimeter-garden",
    "title": "周长花园",
    "subtitle": "连接花格，设计面积与周长刚好的花圃",
    "category": "数字推理",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 8,
    "artwork": {
      "url": "./perimeter-garden-art.svg",
      "position": "center",
      "size": "cover"
    },
    "allowUndo": true,
    "source": {
      "kind": "original",
      "license": "GPL-3.0-only",
      "notes": "原创面积与周长连通花圃规则实现、八张手工关卡、逐段围栏图示、中文说明与 SVG 插画；未复制第三方源码、关卡或素材。提示示例不是胜利判定。"
    },
    "component": lazy(() => import("../games/PerimeterGarden"))
  },
  {
    "id": "server-survival",
    "title": "云端守护站",
    "subtitle": "从第一台服务器到AI浪潮，亲手建设可靠的云端机房。",
    "category": "编程启蒙",
    "difficulty": "进阶",
    "tone": "green",
    "levelCount": 25,
    "artwork": {
      "url": "./server-survival-art.svg",
      "position": "center",
      "size": "cover"
    },
    "resumeKey": "playgarden.server-survival.full",
    "freePlay": true,
    "freePlayCaption": "原作生存与自由沙盒",
    "modeLabels": {
      "free": "生存 / 沙盒",
      "practice": "原作25关"
    },
    "allowUndo": false,
    "source": {
      "kind": "adapted",
      "license": "MIT",
      "author": "Kostyantyn Pshenychnyy 与贡献者",
      "workTitle": "Server Survival（原作25关本地集成）",
      "url": "https://github.com/pshenok/server-survival/tree/7804e5969e28267cd33837e023eb46fa65da72b7",
      "commit": "7804e5969e28267cd33837e023eb46fa65da72b7",
      "notice": "./server-survival-full/LICENSE.txt",
      "notes": "保留原作全部25关、26类服务和生存/沙盒核心模拟；本地Three r128与静态CSS。项目新增中文外壳、键盘/触屏建设台及SVG遵循GPL-3.0-only；不含上游音频或远程CDN。"
    },
    "component": lazy(() => import("../games/ServerSurvivalOriginal"))
  },
  {
    "id": "coil",
    "title": "光迹围球",
    "subtitle": "让光迹首尾相交，圈住蓝球、避开炸弹，挑战更高分。",
    "category": "动作反应",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 0,
    "endless": true,
    "allowUndo": false,
    "artwork": {
      "url": "./coil-original-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "adapted",
      "license": "MIT",
      "author": "Hakim El Hattab",
      "workTitle": "Coil（完整原作无尽画圈游戏）",
      "url": "https://github.com/leereilly/Coil/tree/ea6fd3afae10a6d8a53b07e82be4211619206ede",
      "commit": "ea6fd3afae10a6d8a53b07e82be4211619206ede",
      "notice": "./coil-original/LICENSE.txt",
      "notes": "保留完整原作45点光迹、自交圈球、炸弹、倍率、计分与无尽生成规则。原代码与程序化图形为MIT；Playgarden中文界面、原生输入/生命周期适配和原创SVG为GPL-3.0-only。排除未清权装饰图片、旧jQuery运行时、社交脚本及远程字体。"
    },
    "component": lazy(() => import("../games/CoilOriginal"))
  },
  {
    "id": "parity",
    "title": "步步同数",
    "subtitle": "走入相邻格，让九个数字相遇；挑战完整原作100关。",
    "category": "数字推理",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 100,
    "allowUndo": true,
    "resumeKey": "playgarden.parity.v1",
    "artwork": {
      "url": "./parity-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "adapted",
      "license": "MIT",
      "author": "Abe Fehr",
      "workTitle": "Parity（完整原作100关）",
      "url": "https://github.com/abejfehr/parity/tree/730ecbd24d4cd821bd236f2a441f4e5e2b22654f",
      "commit": "730ecbd24d4cd821bd236f2a441f4e5e2b22654f",
      "notice": "./parity-LICENSE.txt",
      "notes": "原生移植原作3×3连续行走、落点白+1/黑−1与九格同数规则；完整保留50普通关和50黑白关的原始数值、顺序、起点与颜色。原核心/数据MIT；Playgarden中文界面、输入/暂停/存档/撤销/教学提示与新SVG为GPL-3.0-only。无旧库、社交、统计脚本或远程字体。"
    },
    "component": lazy(() => import("../games/ParityGame"))
  },
  {
    "id": "hextris",
    "title": "六向彩环",
    "subtitle": "旋转六边形接住彩块，让同色相连消除，守住外环并延续连击。",
    "category": "动作反应",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 0,
    "endless": true,
    "allowUndo": false,
    "artwork": {
      "url": "./hextris-original-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "adapted",
      "license": "GPL-3.0-or-later",
      "author": "Logan Engstrom、Garrett Finucane、Noah Moroze、Michael Yang",
      "workTitle": "Hextris（完整原作无尽六向消除游戏）",
      "url": "https://github.com/Hextris/hextris/tree/3f4847dc8fd7dab3d1c87e6324b9159d92fbd396",
      "commit": "3f4847dc8fd7dab3d1c87e6324b9159d92fbd396",
      "notice": "./hextris-original/LICENSE.txt",
      "notes": "完整保留原六向旋转落块、环状同色洪泛、计分连击、六种波形、难度与无尽失败规则。原代码与本站中文离线适配/自绘SVG均GPL-3.0-or-later；禁用远程追踪/广告，纯JSON安全存档；无导入美术、字体、音频或第三方运行库。"
    },
    "component": lazy(() => import("../games/HextrisOriginal"))
  },
  {
    "id": "castn",
    "title": "抛网捕鱼",
    "subtitle": "抛网、收网与水位的较量",
    "category": "动作反应",
    "difficulty": "中级",
    "tone": "green",
    "levelCount": 0,
    "endless": true,
    "allowUndo": false,
    "artwork": {
      "url": "./crisp-original/castn/card.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "adapted",
      "license": "MIT",
      "author": "ABA Games",
      "workTitle": "CAST N",
      "url": "https://github.com/abagames/crisp-game-lib-games/blob/cfb39d2f988feb5918eb83697145b5a35adabf58/docs/castn/main.js",
      "commit": "cfb39d2f988feb5918eb83697145b5a35adabf58",
      "notice": "./crisp-original/LICENSES.txt",
      "notes": "保留完整原作的无尽玩法、生成像素与合成音乐；共享本地引擎，原版 main.js 未改写。"
    },
    "component": lazy(() => import("../games/CastNOriginal"))
  },
  {
    "id": "bamboo",
    "title": "竹林巧收",
    "subtitle": "把握成熟时机，规划往返路线",
    "category": "动作反应",
    "difficulty": "初级",
    "tone": "green",
    "levelCount": 0,
    "endless": true,
    "allowUndo": false,
    "artwork": {
      "url": "./crisp-original/bamboo/card.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "adapted",
      "license": "MIT",
      "author": "ABA Games",
      "workTitle": "BAMBOO",
      "url": "https://github.com/abagames/crisp-game-lib-games/blob/cfb39d2f988feb5918eb83697145b5a35adabf58/docs/bamboo/main.js",
      "commit": "cfb39d2f988feb5918eb83697145b5a35adabf58",
      "notice": "./crisp-original/LICENSES.txt",
      "notes": "保留完整原作的无尽玩法、生成像素与合成音乐；共享本地引擎，原版 main.js 未改写。"
    },
    "component": lazy(() => import("../games/BambooOriginal"))
  },
  {
    "id": "parking",
    "title": "同步泊车",
    "subtitle": "一键同步转向，停好整支车队",
    "category": "动作反应",
    "difficulty": "进阶",
    "tone": "orange",
    "levelCount": 0,
    "endless": true,
    "allowUndo": false,
    "artwork": {
      "url": "./crisp-original/parking/card.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "adapted",
      "license": "MIT",
      "author": "ABA Games",
      "workTitle": "PARKING",
      "url": "https://github.com/abagames/crisp-game-lib-games/blob/cfb39d2f988feb5918eb83697145b5a35adabf58/docs/parking/main.js",
      "commit": "cfb39d2f988feb5918eb83697145b5a35adabf58",
      "notice": "./crisp-original/LICENSES.txt",
      "notes": "保留完整原作的无尽玩法、生成像素与合成音乐；共享本地引擎，原版 main.js 未改写。"
    },
    "component": lazy(() => import("../games/ParkingOriginal"))
  },
  {
    "id": "pizzaarrow",
    "title": "披萨神箭",
    "subtitle": "慢动作拉弓，切开旋转披萨",
    "category": "动作反应",
    "difficulty": "进阶",
    "tone": "orange",
    "levelCount": 0,
    "endless": true,
    "allowUndo": false,
    "artwork": {
      "url": "./crisp-original/pizzaarrow/card.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "adapted",
      "license": "MIT",
      "author": "ABA Games",
      "workTitle": "PIZZA ARROW",
      "url": "https://github.com/abagames/crisp-game-lib-games/blob/cfb39d2f988feb5918eb83697145b5a35adabf58/docs/pizzaarrow/main.js",
      "commit": "cfb39d2f988feb5918eb83697145b5a35adabf58",
      "notice": "./crisp-original/LICENSES.txt",
      "notes": "完整无尽原作，原 main.js 逐字保留；共享本地引擎、生成像素和合成音乐。有限关卡为 0。"
    },
    "component": lazy(() => import("../games/PizzaArrowOriginal"))
  },
  {
    "id": "rps",
    "title": "猜拳四轨",
    "subtitle": "四条轨道与三种手势同步轮换",
    "category": "动作反应",
    "difficulty": "进阶",
    "tone": "purple",
    "levelCount": 0,
    "endless": true,
    "allowUndo": false,
    "artwork": {
      "url": "./crisp-original/rps/card.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "adapted",
      "license": "MIT",
      "author": "ABA Games",
      "workTitle": "RPS",
      "url": "https://github.com/abagames/crisp-game-lib-games/blob/cfb39d2f988feb5918eb83697145b5a35adabf58/docs/rps/main.js",
      "commit": "cfb39d2f988feb5918eb83697145b5a35adabf58",
      "notice": "./crisp-original/LICENSES.txt",
      "notes": "完整无尽原作，原 main.js 逐字保留；共享本地引擎、生成像素和合成音乐。有限关卡为 0。"
    },
    "component": lazy(() => import("../games/RpsOriginal"))
  },
  {
    "id": "swingby",
    "title": "引力远航",
    "subtitle": "侧推转向，飞向离起点更远处",
    "category": "动作反应",
    "difficulty": "进阶",
    "tone": "purple",
    "levelCount": 0,
    "endless": true,
    "allowUndo": false,
    "artwork": {
      "url": "./crisp-original/swingby/card.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "adapted",
      "license": "MIT",
      "author": "ABA Games",
      "workTitle": "SWINGBY",
      "url": "https://github.com/abagames/crisp-game-lib-games/blob/cfb39d2f988feb5918eb83697145b5a35adabf58/docs/swingby/main.js",
      "commit": "cfb39d2f988feb5918eb83697145b5a35adabf58",
      "notice": "./crisp-original/LICENSES.txt",
      "notes": "完整无尽原作，原 main.js 逐字保留；共享本地引擎、生成像素和合成音乐。有限关卡为 0。"
    },
    "component": lazy(() => import("../games/SwingbyOriginal"))
  },
  {
    "id": "cube-composer",
    "title": "方块函数工坊",
    "subtitle": "把替换、筛选与堆叠排成程序，重现完整原作25面方块墙。",
    "category": "编程启蒙",
    "difficulty": "中级",
    "tone": "orange",
    "levelCount": 25,
    "allowUndo": true,
    "resumeKey": "playgarden.cube-composer.v1",
    "artwork": {
      "url": "./cube-composer-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "adapted",
      "license": "MIT",
      "author": "David Peter (sharkdp)",
      "workTitle": "Cube Composer（完整原作25关）",
      "url": "https://github.com/sharkdp/cube-composer/tree/a891ffe5de79b072819da04718820d0452b9a201",
      "commit": "a891ffe5de79b072819da04718820d0452b9a201",
      "notice": "./cube-composer-LICENSE.txt",
      "notes": "完整保留6章25原关的彩色列、函数集与严格二维目标；每个函数只用一次，组合替换、过滤、堆叠、模式匹配、稳定分区与三位模8运算。原核心和数据MIT；Playgarden中文界面、触控/键盘、存档/撤销/提示和新SVG为GPL-3.0-only。无旧编译器运行时、统计、远程字体或社交脚本。"
    },
    "component": lazy(() => import("../games/CubeComposerGame"))
  },
  {
    "id": "a-dark-room",
    "title": "小黑屋远行",
    "subtitle": "从房间的一簇火光出发，建起村落，穿越荒野，走向完整原作的星海结局。",
    "category": "逻辑思维",
    "difficulty": "进阶",
    "tone": "purple",
    "levelCount": 0,
    "campaign": true,
    "allowUndo": false,
    "freePlayCaption": "完整战役 · 自动存档",
    "artwork": {
      "url": "./a-dark-room-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "adapted",
      "license": "MPL-2.0",
      "author": "Michael Townsend、doublespeak games 与贡献者",
      "workTitle": "A Dark Room（2020-08-16完整无音频战役）",
      "url": "https://github.com/doublespeakgames/adarkroom/tree/d6d1c1b9875bb4764cdb950e8cf65ba51847f0e9",
      "commit": "d6d1c1b9875bb4764cdb950e8cf65ba51847f0e9",
      "notice": "./adr-original/LICENSES.txt",
      "notes": "保留完整房间/村落、61×61世界、全部事件、九种武器、造船/升空结局及继承。原作MPL-2.0；本地jQuery/Color各保留MIT。本站安全存档、暂停卸载、响应式触屏与中文外壳GPL-3.0-only。固定2020原版无音频，不冒充当前最新版。完整战役，无编号关卡，不计纯无尽。"
    },
    "component": lazy(() => import("../games/ADarkRoomOriginal"))
  },
  {
    "id": "hexa-battle",
    "title": "六角远征",
    "subtitle": "组建队伍，在六角地牢中走位、施法，把生还者带到更深处。",
    "category": "逻辑思维",
    "difficulty": "进阶",
    "tone": "green",
    "levelCount": 0,
    "endless": true,
    "allowUndo": false,
    "freePlayCaption": "无尽远征 · 自动存档",
    "artwork": {
      "url": "./hexa-battle-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "adapted",
      "license": "MIT",
      "author": "Giacomo Tagliabue",
      "workTitle": "Hexa Battle（完整原作规则）",
      "url": "https://github.com/itajaja/hb/tree/fe97718def25736a4000e93efca6894530ba0c86",
      "commit": "fe97718def25736a4000e93efca6894530ba0c86",
      "notice": "./hexa-battle-LICENSE.txt",
      "notes": "完整保留8种人类、8种怪物、13类技能、六角路径、原AI和递进地图/奖励/招募/生还者循环。无限递进，无有限关卡。原核心MIT；本站中文React界面、存档/暂停/退出适配和重绘棋子为GPL-3.0-only。未使用原game-icons素材、旧UI依赖或外部联网。"
    },
    "component": lazy(() => import("../games/HexaBattleGame"))
  },
  {
    "id": "hexahedral",
    "title": "踏格方阵",
    "subtitle": "踩下再升起，30关原版步数谜题",
    "category": "空间想象",
    "difficulty": "中级",
    "tone": "purple",
    "levelCount": 30,
    "resumeKey": "playgarden.hexahedral.v1",
    "allowUndo": false,
    "artwork": {
      "url": "./hexahedral-art.svg",
      "position": "center",
      "size": "cover"
    },
    "source": {
      "kind": "adapted",
      "license": "MIT",
      "author": "Matthew Miner",
      "workTitle": "Hexahedral（完整30关）",
      "url": "https://github.com/mminer/hexahedral/tree/a2641001e13afe15ca8488be7d739203471fee77",
      "commit": "a2641001e13afe15ca8488be7d739203471fee77",
      "notice": "./hexahedral-LICENSE.txt",
      "notes": "原30关地图、起点、缺口、步数预算和走入翻转规则完整保留。原核心及关卡MIT；本站React界面、存档与自绘方块为GPL-3.0-only。未使用第三方原音效或旧依赖。"
    },
    "component": lazy(() => import("../games/HexahedralGame"))
  },
{
  "id": "asteroids",
  "title": "小行星航场",
  "subtitle": "旋转推进，在环绕星空中击碎层层分裂的陨石。",
  "category": "动作反应",
  "difficulty": "进阶",
  "tone": "green",
  "levelCount": 0,
  "endless": true,
  "allowUndo": false,
  "freePlayCaption": "无尽飞行 · 本机最高分",
  "artwork": {
    "url": "./asteroids-art.svg",
    "position": "center",
    "size": "cover"
  },
  "source": {
    "kind": "adapted",
    "license": "MIT",
    "author": "Doug McInnes",
    "workTitle": "HTML5-Asteroids（完整无尽规则）",
    "url": "https://github.com/dmcinnes/HTML5-Asteroids/tree/930301cbda83ed3b120f64b801d937d077ee2da0",
    "commit": "930301cbda83ed3b120f64b801d937d077ee2da0",
    "notice": "./asteroids-LICENSE.txt",
    "notes": "完整保留780×540惯性飞行、三级三分裂陨石、随机射击飞碟、三艘飞船、原计分和无限递进波次。原第一方核心MIT；本站纯TypeScript适配/中文React界面/输入存储/原创卡片GPL-3.0-only。未再分发原音效、矢量字体、借用字体渲染与动画垫片或旧jQuery。"
  },
  "component": lazy(() => import("../games/AsteroidsGame"))
},
{
  "id": "beatrix",
  "title": "鼓点迷径",
  "subtitle": "移动鼓面、引导节拍，奏出完整原作12段多声部谜题。",
  "category": "逻辑思维",
  "difficulty": "进阶",
  "tone": "green",
  "levelCount": 12,
  "allowUndo": true,
  "artwork": {
    "url": "./beatrix-art.svg",
    "position": "center",
    "size": "cover"
  },
  "source": {
    "kind": "adapted",
    "license": "MIT",
    "author": "Cong",
    "workTitle": "Beatrix（完整原作12关）",
    "url": "https://github.com/cxong/Beatrix/tree/059b74a3e9d9ec2bffee0a72ba8a53be107fe8b3",
    "commit": "059b74a3e9d9ec2bffee0a72ba8a53be107fe8b3",
    "notice": "./beatrix-LICENSE.txt",
    "notes": "完整保留32×32原地图、12个目标节拍、固定源、方向鼓、延迟与折返、多声部精确匹配。原核心和数据MIT；本站中文UI、触屏摆放、存档、原创合成音色与SVG为GPL-3.0-only。未使用原录音样本、图片、字体或Phaser。"
  },
  "component": lazy(() => import("../games/BeatrixGame"))
},
];
export const findGame = (id: string) => games.find((game) => game.id === id);
