import { lazy, type LazyExoticComponent, type ComponentType } from "react";
import type { GameProps } from "./types";
import { firstGameArtwork, expansionArtwork, type GameMeta } from "./catalog";
export type GameDefinition = GameMeta & {
  component: LazyExoticComponent<ComponentType<GameProps>>;
};
const original = {
  kind: "original",
  license: "MIT",
  notes: "原创规则实现、关卡和程序化图形；未复制第三方游戏源码。",
} as const;
export const games: GameDefinition[] = [
  {
    id: "light",
    title: "光线实验室",
    subtitle: "调整镜子与光路，让光线点亮目标吧。",
    category: "逻辑思维",
    difficulty: "初级",
    tone: "green",
    levelCount: 12,
    artwork: firstGameArtwork(0),
    source: original,
    component: lazy(() => import("../games/LightLab")),
  },
  {
    id: "robot",
    title: "机器人路线",
    subtitle: "编写指令，带领小机器人抵达终点。",
    category: "编程启蒙",
    difficulty: "初级",
    tone: "purple",
    levelCount: 12,
    artwork: firstGameArtwork(1),
    source: original,
    component: lazy(() => import("../games/RobotRoutes")),
  },
  {
    id: "bridge",
    title: "积木桥梁",
    subtitle: "旋转积木连接桥面，让小旗帜重逢。",
    category: "空间想象",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    artwork: firstGameArtwork(2),
    source: original,
    component: lazy(() => import("../games/BridgeBlocks")),
  },
  {
    id: "slide",
    title: "数字滑块",
    subtitle: "移动空格，让数字一步步回到自己的位置。",
    category: "空间想象",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    artwork: expansionArtwork(0),
    source: original,
    component: lazy(() => import("../games/SlidingTiles")),
  },
  {
    id: "lights-out",
    title: "熄灯谜阵",
    subtitle: "轻点一个开关，寻找让所有灯熄灭的规律。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: expansionArtwork(1),
    source: original,
    component: lazy(() => import("../games/LightsOut")),
  },
  {
    id: "sudoku",
    title: "四格数独",
    subtitle: "让每行、每列、每个小方格都恰好容纳 1 到 4。",
    category: "数字推理",
    difficulty: "初级",
    tone: "purple",
    levelCount: 12,
    artwork: expansionArtwork(2),
    source: original,
    component: lazy(() => import("../games/SudokuGarden")),
  },
  {
    id: "memory",
    title: "记忆花园",
    subtitle: "翻开卡片，记住形状，找出藏在花园里的伙伴。",
    category: "记忆观察",
    difficulty: "初级",
    tone: "purple",
    levelCount: 12,
    artwork: expansionArtwork(3),
    source: original,
    component: lazy(() => import("../games/MemoryGarden")),
  },
  {
    id: "mines",
    title: "花园侦探",
    subtitle: "用数字找出石头，让每一块安全土地重见阳光。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: expansionArtwork(4),
    source: original,
    component: lazy(() => import("../games/MinesGarden")),
  },
  {
    id: "hanoi",
    title: "圆盘搬家",
    subtitle: "规划圆盘的旅程，解开经典汉诺塔的递归秘密。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "orange",
    levelCount: 12,
    artwork: expansionArtwork(5),
    source: original,
    component: lazy(() => import("../games/HanoiTowers")),
  },
];
export const findGame = (id: string) => games.find((game) => game.id === id);
