import { lazy, type LazyExoticComponent, type ComponentType } from "react";
import type { GameProps } from "./types";
import {
  firstGameArtwork,
  expansionArtwork,
  strategyArtwork,
  discoveryArtwork,
  type GameMeta,
} from "./catalog";
export type GameDefinition = GameMeta & {
  component: LazyExoticComponent<ComponentType<GameProps>>;
};
const original = {
  kind: "original",
  license: "MIT",
  notes: "原创规则实现、关卡和程序化图形；未复制第三方游戏源码。",
} as const;
export const games: GameDefinition[] = [
  {
    id: "light",
    title: "光线实验室",
    subtitle: "调整镜子与光路，让光线点亮目标吧。",
    category: "逻辑思维",
    difficulty: "初级",
    tone: "green",
    levelCount: 12,
    artwork: firstGameArtwork(0),
    source: original,
    component: lazy(() => import("../games/LightLab")),
  },
  {
    id: "robot",
    title: "机器人路线",
    subtitle: "编写指令，带领小机器人抵达终点。",
    category: "编程启蒙",
    difficulty: "初级",
    tone: "purple",
    levelCount: 12,
    artwork: firstGameArtwork(1),
    source: original,
    component: lazy(() => import("../games/RobotRoutes")),
  },
  {
    id: "bridge",
    title: "积木桥梁",
    subtitle: "旋转积木连接桥面，让小旗帜重逢。",
    category: "空间想象",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    artwork: firstGameArtwork(2),
    source: original,
    component: lazy(() => import("../games/BridgeBlocks")),
  },
  {
    id: "slide",
    title: "数字滑块",
    subtitle: "移动空格，让数字一步步回到自己的位置。",
    category: "空间想象",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    artwork: expansionArtwork(0),
    source: original,
    component: lazy(() => import("../games/SlidingTiles")),
  },
  {
    id: "lights-out",
    title: "熄灯谜阵",
    subtitle: "轻点一个开关，寻找让所有灯熄灭的规律。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: expansionArtwork(1),
    source: original,
    component: lazy(() => import("../games/LightsOut")),
  },
  {
    id: "sudoku",
    title: "四格数独",
    subtitle: "让每行、每列、每个小方格都恰好容纳 1 到 4。",
    category: "数字推理",
    difficulty: "初级",
    tone: "purple",
    levelCount: 12,
    artwork: expansionArtwork(2),
    source: original,
    component: lazy(() => import("../games/SudokuGarden")),
  },
  {
    id: "memory",
    title: "记忆花园",
    subtitle: "翻开卡片，记住形状，找出藏在花园里的伙伴。",
    category: "记忆观察",
    difficulty: "初级",
    tone: "purple",
    levelCount: 12,
    artwork: expansionArtwork(3),
    source: original,
    component: lazy(() => import("../games/MemoryGarden")),
  },
  {
    id: "mines",
    title: "花园侦探",
    subtitle: "用数字找出石头，让每一块安全土地重见阳光。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: expansionArtwork(4),
    source: original,
    component: lazy(() => import("../games/MinesGarden")),
  },
  {
    id: "hanoi",
    title: "圆盘搬家",
    subtitle: "规划圆盘的旅程，解开经典汉诺塔的递归秘密。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "orange",
    levelCount: 12,
    artwork: expansionArtwork(5),
    source: original,
    component: lazy(() => import("../games/HanoiTowers")),
  },
  {
    id: "nonogram",
    title: "像素逻辑画",
    subtitle: "读懂行列线索，让隐藏的小图案逐格显现。",
    category: "逻辑思维",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: strategyArtwork(0),
    source: original,
    component: lazy(() => import("../games/NonogramGarden")),
  },
  {
    id: "boxes",
    title: "推箱花园",
    subtitle: "规划每一次推动，把木箱送到花朵标记上。",
    category: "空间想象",
    difficulty: "中级",
    tone: "purple",
    levelCount: 12,
    artwork: strategyArtwork(1),
    source: original,
    component: lazy(() => import("../games/BoxGarden")),
  },
  {
    id: "connect",
    title: "四子花径",
    subtitle: "预判对手的回应，让四颗棋子连成一条线。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "green",
    levelCount: 12,
    artwork: strategyArtwork(2),
    source: original,
    component: lazy(() => import("../games/FourInARow")),
  },
  {
    id: "reversi",
    title: "翻转花园",
    subtitle: "寻找夹击的位置，用一次落子翻转整个局面。",
    category: "逻辑思维",
    difficulty: "进阶",
    tone: "orange",
    levelCount: 12,
    artwork: strategyArtwork(3),
    source: original,
    component: lazy(() => import("../games/ReversiGarden")),
  },
  {
    id: "merge",
    title: "合并花园",
    subtitle: "把相同数字推到一起，规划通向 2048 的路线。",
    category: "数字推理",
    difficulty: "中级",
    tone: "orange",
    levelCount: 12,
    artwork: discoveryArtwork(0),
    source: original,
    component: lazy(() => import("../games/MergeGarden")),
  },
  {
    id: "traffic",
    title: "停车场出口",
    subtitle: "移动挡路的车辆，为目标小车打开出口。",
    category: "空间想象",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: discoveryArtwork(1),
    source: original,
    component: lazy(() => import("../games/TrafficEscape")),
  },

  {
    id: "arithmetic",
    title: "数字工坊",
    subtitle: "组合四个数字与运算符，调配出目标答案。",
    category: "数字推理",
    difficulty: "中级",
    tone: "green",
    levelCount: 12,
    artwork: discoveryArtwork(2),
    source: original,
    component: lazy(() => import("../games/ArithmeticWorkshop")),
  },
  {
    id: "word-search",
    title: "寻词花园",
    subtitle: "在横竖斜向的字格中，找出熟悉的自然词语。",
    category: "记忆观察",
    difficulty: "初级",
    tone: "purple",
    levelCount: 12,
    artwork: discoveryArtwork(3),
    source: original,
    component: lazy(() => import("../games/WordSearchGarden")),
  },
];
export const findGame = (id: string) => games.find((game) => game.id === id);
