// SPDX-License-Identifier: GPL-3.0-only
import {test,expect,type Page,type Locator} from '@playwright/test';
import {openGame,chooseLevel,captureErrors} from './helpers';
import type {BeatrixSnapshot} from '../src/vendor/beatrixCore';
type Reading=BeatrixSnapshot&{running:boolean;paused:boolean;preview:number|null;audio:{state:string;voices:number;strikes:number;enabled:boolean}};
type Position={id:string;x:number;y:number};
const read=(page:Page)=>page.evaluate(()=>{const f=(window as unknown as {__beatrixRead?:()=>Reading}).__beatrixRead;if(!f)throw Error('Missing read-only Beatrix observer');return f();});
const examples = [{"levelId": "level1_1", "kind": "static", "expectedWinningCycleByReasoning": 1, "initialPositions": [{"id": "level1_1:14,9", "x": 14, "y": 11}], "liveEdits": []}, {"levelId": "level2_5", "kind": "static", "expectedWinningCycleByReasoning": 2, "initialPositions": [{"id": "level2_5:10,2", "x": 28, "y": 4}, {"id": "level2_5:5,3", "x": 28, "y": 3}, {"id": "level2_5:15,3", "x": 28, "y": 20}, {"id": "level2_5:13,4", "x": 28, "y": 28}, {"id": "level2_5:20,4", "x": 28, "y": 6}, {"id": "level2_5:8,5", "x": 28, "y": 30}, {"id": "level2_5:12,7", "x": 28, "y": 31}, {"id": "level2_5:17,7", "x": 28, "y": 10}, {"id": "level2_5:9,8", "x": 28, "y": 14}, {"id": "level2_5:13,8", "x": 28, "y": 12}], "liveEdits": []}, {"levelId": "levelbonus_1", "kind": "live-edit", "expectedWinningCycleByReasoning": 2, "initialPositions": [{"id": "levelbonus_1:12,9", "x": 13, "y": 17}, {"id": "levelbonus_1:18,9", "x": 16, "y": 16}, {"id": "levelbonus_1:14,10", "x": 19, "y": 14}, {"id": "levelbonus_1:17,11", "x": 17, "y": 13}, {"id": "levelbonus_1:10,12", "x": 13, "y": 19}, {"id": "levelbonus_1:15,14", "x": 13, "y": 21}, {"id": "levelbonus_1:12,15", "x": 19, "y": 13}, {"id": "levelbonus_1:11,16", "x": 13, "y": 23}, {"id": "levelbonus_1:14,17", "x": 16, "y": 14}, {"id": "levelbonus_1:18,18", "x": 13, "y": 16}], "liveEdits": [{"afterCompletedTicks": 24, "beforeProcessingTick": 24, "moves": [{"id": "levelbonus_1:12,9", "x": 13, "y": 25}, {"id": "levelbonus_1:10,12", "x": 13, "y": 27}, {"id": "levelbonus_1:15,14", "x": 13, "y": 29}, {"id": "levelbonus_1:11,16", "x": 13, "y": 31}]}], "note": "Apply each later move individually without restarting playback. A live-edit solution is not a static solved layout."}] as const;
test('original first, middle and bonus rhythms with real placement, audio and lifecycle',async({page},info)=>{
 test.setTimeout(180000);const mobile=info.project.name==='mobile',errors=captureErrors(page),outside:string[]=[],act=async(l:Locator)=>mobile?l.tap():l.click();
 page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:4173/'))outside.push(r.url());});
 // Observes native audio lifecycle only; no game state, clock, result or rhythm is set.
 await page.addInitScript(()=>{const Native=window.AudioContext,contexts:AudioContext[]=[];(window as unknown as {__btContexts:AudioContext[]}).__btContexts=contexts;window.AudioContext=class extends Native{constructor(options?:AudioContextOptions){super(options);contexts.push(this);}};});
 await openGame(page,'鼓点迷径');const game=page.locator('.bt-game');await expect(page.getByLabel('选择关卡',{exact:true}).locator('option')).toHaveCount(12);
 await page.evaluate(()=>localStorage.setItem('playgarden.beatrix-unrelated','keep'));
 const place=async(p:Position)=>{await act(page.locator(`[data-bt-select="${p.id}"]`));await page.getByLabel('摆放行',{exact:true}).fill(String(p.y+1));await page.getByLabel('摆放列',{exact:true}).fill(String(p.x+1));await act(page.getByRole('button',{name:'移到这里',exact:true}));const d=(await read(page)).drums.find(d=>d.id===p.id);expect(d&&{x:d.x,y:d.y}).toEqual({x:p.x,y:p.y});};
 const arrange=async(positions:readonly Position[])=>{const pending=positions.map(p=>({...p}));while(pending.length){const current=(await read(page)).drums;const i=pending.findIndex(p=>!current.some(d=>d.id!==p.id&&d.x===p.x&&d.y===p.y));if(i<0){const p=pending[0];let cell=0;while(current.some(d=>d.x===cell%32&&d.y===Math.floor(cell/32))||positions.some(d=>d.x===cell%32&&d.y===Math.floor(cell/32)))cell++;await place({id:p.id,x:cell%32,y:Math.floor(cell/32)});}else{await place(pending[i]);pending.splice(i,1);}}};
 const first=(await read(page)).drums.find(d=>!d.fixed)!;await act(page.locator(`[data-bt-select="${first.id}"]`));await page.getByLabel('摆放行',{exact:true}).fill('12');await page.getByLabel('摆放列',{exact:true}).fill('11');await act(page.getByRole('button',{name:'移到这里',exact:true}));expect((await read(page)).drums.find(d=>d.id===first.id)?.y).toBe(9);await expect(page.locator('.bt-message')).toContainText('不能占用');
 await act(page.getByRole('button',{name:'开始演奏',exact:true}));await expect.poll(async()=>(await read(page)).cycle).toBeGreaterThanOrEqual(1);expect((await read(page)).lastCycle?.correct).toBe(false);expect((await read(page)).won).toBe(false);expect((await read(page)).audio.strikes).toBeGreaterThan(0);
 await act(page.getByRole('button',{name:'暂停',exact:true}));const frozen=await read(page);await page.waitForTimeout(450);expect((await read(page)).ticks).toBe(frozen.ticks);expect((await read(page)).audio.voices).toBe(0);await expect(page.getByRole('button',{name:'移到这里',exact:true})).toBeDisabled();await page.screenshot({path:info.outputPath('beatrix-original-negative-rhythm-paused.png'),fullPage:true});
 await act(page.getByRole('button',{name:'继续游戏',exact:true}));await act(page.getByRole('button',{name:'停止演奏',exact:true}));const beforePreview=await read(page);await act(page.getByRole('button',{name:'试听目标',exact:true}));await expect.poll(async()=>(await read(page)).preview).not.toBeNull();await expect(page.getByRole('button',{name:'移到这里',exact:true})).toBeDisabled();await expect.poll(async()=>(await read(page)).preview).toBeNull();expect((await read(page)).ticks).toBe(beforePreview.ticks);expect((await read(page)).audio.strikes).toBeGreaterThan(beforePreview.audio.strikes);
 await act(page.getByRole('button',{name:'静音',exact:true}));const strikes=(await read(page)).audio.strikes;await act(page.getByRole('button',{name:'开始演奏',exact:true}));await page.waitForTimeout(700);expect((await read(page)).audio.strikes).toBe(strikes);expect((await read(page)).audio.voices).toBe(0);await act(page.getByRole('button',{name:'停止演奏',exact:true}));await act(page.getByRole('button',{name:'开启声音',exact:true}));
 await act(page.getByRole('button',{name:'鼓向下',exact:true}));expect((await read(page)).drums.find(d=>d.id===first.id)?.y).toBe(10);await act(page.getByRole('button',{name:'撤销',exact:true}));expect((await read(page)).drums.find(d=>d.id===first.id)?.y).toBe(9);
 await arrange(examples[0].initialPositions);await page.reload();await openGame(page,'鼓点迷径');await chooseLevel(page,0);expect((await read(page)).drums.find(d=>d.id===first.id)?.y).toBe(11);expect((await read(page)).running).toBe(false);await act(page.getByRole('button',{name:'开始演奏',exact:true}));await expect(game).toHaveAttribute('data-bt-won','true',{timeout:15000});await expect(page.locator('.status')).toHaveClass(/success/);await page.screenshot({path:info.outputPath('beatrix-first-earned-rhythm.png'),fullPage:true});
 await chooseLevel(page,6);await arrange(examples[1].initialPositions);
 if(mobile){await expect(page.locator('.bt-score-cue')).toContainText('左右滑动查看全部 16 拍');const score=page.locator('.bt-score');await score.scrollIntoViewIfNeeded();const sb=(await score.boundingBox())!,scdp=await page.context().newCDPSession(page),sx=sb.x+sb.width-20,sy=sb.y+sb.height/2;await scdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:sx,y:sy,id:6}]});for(let i=1;i<=8;i++)await scdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:sx-i*28,y:sy,id:6}]});await scdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(()=>score.evaluate(e=>e.scrollLeft)).toBeGreaterThan(0);await expect.poll(async()=>{const last=(await page.locator('[data-bt-column="15"]').boundingBox())!,box=(await score.boundingBox())!;return last.x>=box.x&&last.x+last.width<=box.x+box.width+1;}).toBe(true);await page.screenshot({path:info.outputPath('beatrix-touch-score-final-columns.png'),fullPage:true});await act(page.getByRole('button',{name:'放大棋盘',exact:true}));const wrap=page.locator('.bt-map-scroll');await wrap.scrollIntoViewIfNeeded();const box=(await wrap.boundingBox())!,cdp=await page.context().newCDPSession(page),before=(await read(page)).drums.map(d=>[d.id,d.x,d.y]);const x0=box.x+box.width-25,y0=box.y+Math.min(box.height-25,300);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x0,y:y0,id:1}]});for(let i=1;i<=7;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x0-i*25,y:y0-i*15,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(()=>wrap.evaluate(e=>e.scrollLeft)).toBeGreaterThan(0);expect((await read(page)).drums.map(d=>[d.id,d.x,d.y])).toEqual(before);await page.screenshot({path:info.outputPath('beatrix-touch-zoom-pan.png'),fullPage:true});await act(page.getByRole('button',{name:'查看全盘',exact:true}));}
 await act(page.getByRole('button',{name:'开始演奏',exact:true}));await expect(game).toHaveAttribute('data-bt-won','true',{timeout:15000});expect((await read(page)).cycle).toBe(2);await page.screenshot({path:info.outputPath('beatrix-middle-delayed-pulse-victory.png'),fullPage:true});
 await chooseLevel(page,11);await arrange(examples[2].initialPositions);await page.screenshot({path:info.outputPath('beatrix-bonus-original-target-layout.png'),fullPage:true});await act(page.getByRole('button',{name:'开始演奏',exact:true}));
 // The original permits live edits. This is deliberately a dynamic solution,
 // using the ordinary stop/resume controls without clearing phase or pulses.
 await page.waitForFunction(()=>{const f=(window as unknown as {__beatrixRead:()=>Reading}).__beatrixRead;return f().ticks>=24;},undefined,{polling:10,timeout:10000});await act(page.getByRole('button',{name:'停止演奏',exact:true}));const midpoint=await read(page);expect(midpoint.ticks).toBe(24);expect(midpoint.won).toBe(false);expect(midpoint.lastCycle?.correct).toBe(false);
 for(const p of examples[2].liveEdits[0].moves)await place(p);expect((await read(page)).ticks).toBe(24);await act(page.getByRole('button',{name:'开始演奏',exact:true}));await expect(game).toHaveAttribute('data-bt-won','true',{timeout:15000});expect((await read(page)).ticks).toBe(32);expect((await read(page)).checks.every(Boolean)).toBe(true);await expect(page.locator('.bt-message')).toContainText('加演关完成');await expect(page.locator('.bt-message')).not.toContainText('十二关全部');await page.screenshot({path:info.outputPath('beatrix-bonus-earned-live-edit-victory.png'),fullPage:true});
 await act(page.getByRole('button',{name:'返回游戏大厅',exact:true}));expect(await page.evaluate(()=>typeof(window as unknown as Record<string,unknown>).__beatrixRead)).toBe('undefined');await expect.poll(()=>page.evaluate(()=>(window as unknown as {__btContexts:AudioContext[]}).__btContexts.every(c=>c.state==='closed'))).toBe(true);
 await openGame(page,'鼓点迷径');await chooseLevel(page,11);expect((await read(page)).running).toBe(false);expect((await read(page)).ticks).toBe(0);expect((await read(page)).won).toBe(false);expect(await page.evaluate(()=>localStorage.getItem('playgarden.beatrix-unrelated'))).toBe('keep');if(mobile){await page.setViewportSize({width:320,height:760});await page.screenshot({path:info.outputPath('beatrix-320px-saved-arrangement.png'),fullPage:true});}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);expect(outside).toEqual([]);
});
