// SPDX-License-Identifier: GPL-3.0-only
import {test,expect,type Page,type TestInfo} from "@playwright/test";
import {openGame,chooseLevel,captureErrors} from "./helpers";
import {cloudHopLevels,type HopState} from "../src/games/cloudHopLogic";
const read=(p:Page)=>p.locator(".chp-game").getAttribute("data-chp-state").then(s=>JSON.parse(s!) as HopState);
async function start(p:Page,i:TestInfo){if(i.project.name==="mobile")await p.getByRole("button",{name:"开始跳跃",exact:true}).tap();else{await p.locator(".chp-stage").focus();await p.keyboard.press("Space");}}
async function win(page:Page,info:TestInfo,level:number){await start(page,info);let held="";const end=Date.now()+55000;while(Date.now()<end){const s=await read(page);if(s.status==="won")break;expect(s.status).not.toBe("lost");const target=cloudHopLevels[level].platforms[Math.min(s.landed+1,cloudHopLevels[level].platforms.length-1)],delta=target.x-s.x;const direction=Math.abs(delta)>13?(delta<0?"ArrowLeft":"ArrowRight"):"";
 if(info.project.name==="mobile"){const control=page.getByRole("button",{name:direction?(direction==="ArrowLeft"?"向左飞":"向右飞"):"停止横移",exact:true});try{await control.tap({timeout:1000});}catch(error){if((await read(page)).status!=="won")throw error;}}else if(direction!==held){if(held)await page.keyboard.up(held);if(direction)await page.keyboard.down(direction);held=direction;}await page.waitForTimeout(45);}
 if(held)await page.keyboard.up(held);await expect(page.locator(".chp-game")).toHaveAttribute("data-chp-won","true");await expect(page.locator(".status")).toHaveClass(/success/);await expect(page.getByRole("button",{name:"撤销",exact:true})).toBeDisabled();const final=await read(page);await page.waitForTimeout(200);expect(await read(page)).toEqual(final);expect(await page.locator(".chp-controls button").evaluateAll(bs=>bs.every(b=>(b as HTMLButtonElement).disabled))).toBe(true);}
test("Cloud hop: real landings reach first and final summits",async({page},info)=>{test.setTimeout(160000);const errors=captureErrors(page);await openGame(page,"云朵弹跳");await page.screenshot({path:info.outputPath("cloud-hop-first-start.png"),fullPage:true});await start(page,info);await page.waitForTimeout(150);await page.getByRole("button",{name:"暂停",exact:true}).click();const frozen=await read(page);await page.waitForTimeout(250);expect(await read(page)).toEqual(frozen);await expect(page.getByRole("button",{name:"向左飞",exact:true})).toBeDisabled();await page.getByRole("button",{name:"继续游戏",exact:true}).click();await page.getByRole("button",{name:"重来",exact:true}).click();expect((await read(page)).status).toBe("idle");await page.getByRole("button",{name:"提示",exact:true}).click();expect((await read(page)).status).toBe("idle");await win(page,info,0);await page.screenshot({path:info.outputPath("cloud-hop-first-win.png"),fullPage:true});await chooseLevel(page,7);await page.screenshot({path:info.outputPath("cloud-hop-final-start.png"),fullPage:true});await win(page,info,7);await page.screenshot({path:info.outputPath("cloud-hop-final-win.png"),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);});
