// SPDX-License-Identifier: GPL-3.0-only
import {test,expect,type Page,type TestInfo} from "@playwright/test";
import {openGame,chooseLevel,captureErrors} from "./helpers";
const root=(page:Page)=>page.locator(".dc-game");
async function press(page:Page,info:TestInfo,selector:string){const b=page.locator(selector);if(info.project.name==="mobile")await b.tap();else{await b.focus();await b.press("Enter");}}
async function hold(page:Page,info:TestInfo,ids:number[]){for(const i of ids)await press(page,info,`[data-die="${i}"]`);}
async function score(page:Page,info:TestInfo,category:string){await press(page,info,`[data-dice-category="${category}"]`);}
async function win(page:Page){await expect(root(page)).toHaveAttribute("data-dice-won","true");await expect(page.locator(".status")).toHaveClass(/success/);await expect(page.getByRole("button",{name:"撤销",exact:true})).toBeDisabled();expect(await root(page).locator("button").evaluateAll(bs=>bs.every(b=>(b as HTMLButtonElement).disabled))).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
test("Dice combinations: fixed-sequence hold/reroll/allocation first and final wins",async({page},info)=>{const errors=captureErrors(page);await openGame(page,"骰子组合");await expect(page.locator(".dc-disclosure")).toContainText("没有随机投掷");const initial=await root(page).getAttribute("data-dice-state");const pips=await page.locator(".dc-pip").evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return {w:r.width,h:r.height};}));expect(pips.length).toBeGreaterThan(0);expect(pips.every(p=>p.w>=3&&p.h>=3)).toBe(true);await page.screenshot({path:info.outputPath("dice-first-start.png"),fullPage:true,animations:"disabled"});
 await hold(page,info,[0]);await page.getByRole("button",{name:"暂停",exact:true}).click();expect(await root(page).locator("button").evaluateAll(bs=>bs.every(b=>(b as HTMLButtonElement).disabled))).toBe(true);await page.getByRole("button",{name:"继续游戏",exact:true}).click();await page.getByRole("button",{name:"撤销",exact:true}).click();await expect(root(page)).toHaveAttribute("data-dice-state",initial!);
 await press(page,info,".dc-roll");await page.getByRole("button",{name:"重来",exact:true}).click();await expect(root(page)).toHaveAttribute("data-dice-state",initial!);await page.getByRole("button",{name:"提示",exact:true}).click();await expect(page.locator(".dc-feedback")).toContainText("最高可达");await expect(root(page)).toHaveAttribute("data-dice-state",initial!);
 // A zero-score choice really uses a category. Failing the goal must not complete the lesson.
 await score(page,info,"triple");await score(page,info,"chance");await expect(root(page)).toHaveAttribute("data-dice-finished","true");await expect(root(page)).toHaveAttribute("data-dice-won","false");await expect(page.locator(".status")).not.toHaveClass(/success/);await page.getByRole("button",{name:"撤销",exact:true}).click();await expect(root(page)).toHaveAttribute("data-dice-finished","false");await page.getByRole("button",{name:"重来",exact:true}).click();
 await hold(page,info,[0,1]);await press(page,info,".dc-roll");await score(page,info,"triple");await press(page,info,".dc-roll");await hold(page,info,[0,1,4]);await press(page,info,".dc-roll");await score(page,info,"chance");await win(page);await page.screenshot({path:info.outputPath("dice-first-win.png"),fullPage:true,animations:"disabled"});
 await chooseLevel(page,7);await page.screenshot({path:info.outputPath("dice-final-start.png"),fullPage:true,animations:"disabled"});await hold(page,info,[0,1,2]);await press(page,info,".dc-roll");await score(page,info,"straight");await hold(page,info,[0,1,2]);await press(page,info,".dc-roll");await score(page,info,"house");await hold(page,info,[0,2]);await press(page,info,".dc-roll");await score(page,info,"chance");await win(page);await page.screenshot({path:info.outputPath("dice-final-win.png"),fullPage:true,animations:"disabled"});
 expect(await root(page).locator("button").evaluateAll(bs=>bs.every(b=>{const r=b.getBoundingClientRect();return r.width>=44&&r.height>=44;}))).toBe(true);const completed=await page.evaluate(()=>JSON.parse(localStorage.getItem("playgarden.progress.v2")!).completed["dice-combinations"]);expect(completed).toEqual(expect.arrayContaining([0,7]));expect(errors).toEqual([]);
});
