// SPDX-License-Identifier: GPL-3.0-only
import {test,expect,type Page,type TestInfo} from "@playwright/test";
import {openGame,chooseLevel,captureErrors} from "./helpers";
import type {GolfState} from "../src/games/golfCardsLogic";
const root=(page:Page)=>page.locator(".gc-game");
async function press(page:Page,info:TestInfo,selector:string){const b=page.locator(selector);if(info.project.name==="mobile")await b.tap();else{await b.focus();await b.press("Enter");}}
async function card(page:Page,info:TestInfo,column:number){const state:GolfState=JSON.parse((await root(page).getAttribute("data-golf-state"))!);await press(page,info,`[data-golf-column="${column}"][data-golf-row="${state.heights[column]-1}"]`);}
async function win(page:Page){await expect(root(page)).toHaveAttribute("data-golf-won","true");await expect(page.locator(".status")).toHaveClass(/success/);await expect(page.getByRole("button",{name:"撤销",exact:true})).toBeDisabled();expect(await root(page).locator("button").evaluateAll(bs=>bs.every(b=>(b as HTMLButtonElement).disabled))).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
test("Golf cards: actual first and final wins with finite stock",async({page},info)=>{const errors=captureErrors(page);await openGame(page,"逐张纸牌");const initial=await root(page).getAttribute("data-golf-state");await page.screenshot({path:info.outputPath("golf-first-start.png"),fullPage:true,animations:"disabled"});
 await card(page,info,0);const after=await root(page).getAttribute("data-golf-state");await card(page,info,2);await expect(page.locator(".gc-feedback")).toContainText("点数必须相差 1");await expect(root(page)).toHaveAttribute("data-golf-state",after!);
 await page.getByRole("button",{name:"暂停",exact:true}).click();expect(await root(page).locator("button").evaluateAll(bs=>bs.every(b=>(b as HTMLButtonElement).disabled))).toBe(true);await page.getByRole("button",{name:"继续游戏",exact:true}).click();await page.getByRole("button",{name:"撤销",exact:true}).click();await expect(root(page)).toHaveAttribute("data-golf-state",initial!);
 await press(page,info,".gc-reserve button");await page.getByRole("button",{name:"重来",exact:true}).click();await expect(root(page)).toHaveAttribute("data-golf-state",initial!);await page.getByRole("button",{name:"提示",exact:true}).click();await expect(page.locator(".gc-hinted")).toHaveCount(1);await expect(root(page)).toHaveAttribute("data-golf-state",initial!);
 for(const c of [0,0,1,1,2,2])await card(page,info,c);await win(page);await page.screenshot({path:info.outputPath("golf-first-win.png"),fullPage:true,animations:"disabled"});
 await chooseLevel(page,7);await page.screenshot({path:info.outputPath("golf-final-start.png"),fullPage:true,animations:"disabled"});for(const c of [0,1,2,0,1,2])await card(page,info,c);await press(page,info,".gc-reserve button");for(const c of [3,3,0,1,2,3])await card(page,info,c);await win(page);await page.screenshot({path:info.outputPath("golf-final-win.png"),fullPage:true,animations:"disabled"});
 expect(await root(page).locator("button").evaluateAll(bs=>bs.every(b=>{const r=b.getBoundingClientRect();return r.width>=44&&r.height>=44;}))).toBe(true);const completed=await page.evaluate(()=>JSON.parse(localStorage.getItem("playgarden.progress.v2")!).completed["golf-cards"]);expect(completed).toEqual(expect.arrayContaining([0,7]));expect(errors).toEqual([]);
});
