// SPDX-License-Identifier: GPL-3.0-only
import {test,expect,type Page,type TestInfo} from "@playwright/test";
import {openGame,chooseLevel,captureErrors} from "./helpers";
const root=(page:Page)=>page.locator(".hp-game");
async function cell(page:Page,info:TestInfo,index:number){const b=page.locator(`[data-hex-cell="${index}"]`);if(info.project.name==="mobile")await b.tap();else{await b.focus();await b.press("Enter");}}
async function move(page:Page,info:TestInfo,from:number,to:number){await cell(page,info,from);await cell(page,info,to);}
async function win(page:Page){await expect(root(page)).toHaveAttribute("data-hexapawn-won","true");await expect(page.locator(".status")).toHaveClass(/success/);await expect(page.getByRole("button",{name:"撤销",exact:true})).toBeDisabled();expect(await root(page).locator("button").evaluateAll(bs=>bs.every(b=>(b as HTMLButtonElement).disabled))).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
test("Hexapawn: exact replies, first and final wins, loss/undo and touch",async({page},info)=>{const errors=captureErrors(page);await openGame(page,"小兵冲线");const initial=await root(page).getAttribute("data-hexapawn-state");await page.screenshot({path:info.outputPath("hexapawn-first-start.png"),fullPage:true,animations:"disabled"});
 await move(page,info,6,4);await expect(page.locator(".hp-feedback")).toContainText("不能横走");await expect(root(page)).toHaveAttribute("data-hexapawn-state",initial!);await cell(page,info,3);await expect(root(page)).toHaveAttribute("data-hexapawn-moves","1");
 await page.getByRole("button",{name:"暂停",exact:true}).click();expect(await root(page).locator("button").evaluateAll(bs=>bs.every(b=>(b as HTMLButtonElement).disabled))).toBe(true);await page.getByRole("button",{name:"继续游戏",exact:true}).click();await page.getByRole("button",{name:"撤销",exact:true}).click();await expect(root(page)).toHaveAttribute("data-hexapawn-state",initial!);
 await move(page,info,6,3);await page.getByRole("button",{name:"重来",exact:true}).click();await expect(root(page)).toHaveAttribute("data-hexapawn-state",initial!);await page.getByRole("button",{name:"提示",exact:true}).click();await expect(page.locator(".hp-hinted")).toHaveCount(2);await expect(root(page)).toHaveAttribute("data-hexapawn-state",initial!);
 await move(page,info,6,3);await move(page,info,3,0);await win(page);await page.screenshot({path:info.outputPath("hexapawn-first-win.png"),fullPage:true,animations:"disabled"});
 // The local opponent takes a genuine forced win after an unsafe advance.
 await chooseLevel(page,5);await move(page,info,13,9);await move(page,info,9,5);await expect(root(page)).toHaveAttribute("data-hexapawn-winner","brown");await expect(page.locator(".status")).not.toHaveClass(/success/);await page.getByRole("button",{name:"撤销",exact:true}).click();await expect(root(page)).toHaveAttribute("data-hexapawn-winner","none");
 await chooseLevel(page,7);await page.screenshot({path:info.outputPath("hexapawn-final-start.png"),fullPage:true,animations:"disabled"});await move(page,info,7,4);await move(page,info,6,4);await move(page,info,8,4);await win(page);await page.screenshot({path:info.outputPath("hexapawn-final-win.png"),fullPage:true,animations:"disabled"});
 expect(await root(page).locator("button").evaluateAll(bs=>bs.every(b=>{const r=b.getBoundingClientRect();return r.width>=44&&r.height>=44;}))).toBe(true);const completed=await page.evaluate(()=>JSON.parse(localStorage.getItem("playgarden.progress.v2")!).completed["hexapawn"]);expect(completed).toEqual(expect.arrayContaining([0,7]));expect(errors).toEqual([]);
});
