// SPDX-License-Identifier: GPL-3.0-only
import {test,expect,type Page,type TestInfo} from "@playwright/test";
import {openGame,chooseLevel,captureErrors} from "./helpers";
import {jigsawGardenLevels,jigsawTarget} from "../src/games/jigsawGardenLogic";
async function select(page:Page,info:TestInfo,id:number){const p=page.locator(`[data-jgg-piece="${id}"]`);if(info.project.name==="mobile"){const table=page.locator(".jgg-table"),box=await table.boundingBox(),x=Number(await p.getAttribute("data-jgg-x")),y=Number(await p.getAttribute("data-jgg-y"));await table.tap({position:{x:x*box!.width/480,y:y*box!.height/650}});}else{await p.focus();await p.press("Enter");await page.locator(".jgg-table").focus();}await expect(p).toHaveAttribute("aria-pressed","true");}
async function rotate(page:Page,info:TestInfo){if(info.project.name==="mobile")await page.getByRole("button",{name:"↻ 旋转 90°",exact:true}).tap();else await page.locator(".jgg-table").press("r");}
async function win(page:Page,info:TestInfo,level:number){const config=jigsawGardenLevels[level];for(let id=0;id<config.columns*config.rows;id++){const p=page.locator(`[data-jgg-piece="${id}"]`);await select(page,info,id);const r=Number(await p.getAttribute("data-jgg-rotation"));for(let t=0;t<(4-r)%4;t++)await rotate(page,info);const target=jigsawTarget(config,id);if(info.project.name==="mobile"){const box=await page.locator(".jgg-table").boundingBox();await page.locator(".jgg-table").tap({position:{x:target.x*box!.width/480,y:target.y*box!.height/650}});}else{for(let n=0;n<80;n++){if(await p.getAttribute("data-jgg-placed")==="true")break;const dx=target.x-Number(await p.getAttribute("data-jgg-x")),dy=target.y-Number(await p.getAttribute("data-jgg-y"));const delta=Math.abs(dx)>5?dx:dy,key=Math.abs(dx)>5?(dx>0?"ArrowRight":"ArrowLeft"):(dy>0?"ArrowDown":"ArrowUp");await page.locator(".jgg-table").press(`${Math.abs(delta)>22?"Shift+":""}${key}`);}}await expect(p).toHaveAttribute("data-jgg-placed","true");}
 await expect(page.locator(".jgg-game")).toHaveAttribute("data-jgg-won","true");await expect(page.locator(".status")).toHaveClass(/success/);await expect(page.getByRole("button",{name:"撤销",exact:true})).toBeDisabled();const final=await page.locator(".jgg-game").getAttribute("data-jgg-board");await page.locator(".jgg-table").press("ArrowDown");await expect(page.locator(".jgg-game")).toHaveAttribute("data-jgg-board",final!);expect(await page.locator(".jgg-game button").evaluateAll(bs=>bs.every(b=>(b as HTMLButtonElement).disabled))).toBe(true);}
test("Jigsaw: freely place and rotate original complementary picture pieces",async({page},info)=>{test.setTimeout(180000);const errors=captureErrors(page);await openGame(page,"花园拼图");const root=page.locator(".jgg-game"),initial=await root.getAttribute("data-jgg-board");await page.screenshot({path:info.outputPath("jigsaw-first-start.png"),fullPage:true});await select(page,info,0);await rotate(page,info);await page.getByRole("button",{name:"撤销",exact:true}).click();await expect(root).toHaveAttribute("data-jgg-board",initial!);await page.getByRole("button",{name:"提示",exact:true}).click();await expect(root).toHaveAttribute("data-jgg-board",initial!);await page.getByRole("button",{name:"暂停",exact:true}).click();await expect(page.getByRole("button",{name:"↻ 旋转 90°",exact:true})).toBeDisabled();await page.locator(".jgg-table").press("r");await expect(root).toHaveAttribute("data-jgg-board",initial!);await page.getByRole("button",{name:"继续游戏",exact:true}).click();await page.getByRole("button",{name:"重来",exact:true}).click();await expect(root).toHaveAttribute("data-jgg-board",initial!);await win(page,info,0);await page.screenshot({path:info.outputPath("jigsaw-first-win.png"),fullPage:true});await chooseLevel(page,7);await page.screenshot({path:info.outputPath("jigsaw-final-start.png"),fullPage:true});await win(page,info,7);await page.screenshot({path:info.outputPath("jigsaw-final-win.png"),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);});
