// SPDX-License-Identifier: GPL-3.0-only
import {test,expect} from '@playwright/test';
import {enterMerge,setMergeRound,verifyMergeMotion,settleMerge,freezeMerge,swipeMerge,mergeLayout,roundKey,bestKey} from './mergeJourney';
import {mergeMove,restoreMergeState,type MergeDirection} from '../src/games/mergeLogic';
test('2048 actual tile slide midpoint, merge pop, spawn, saved score and restart',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await setMergeRound(page);await enterMerge(page);await verifyMergeMotion(page,info);
 const saved=await page.evaluate(key=>localStorage.getItem(key),roundKey);await page.getByRole('button',{name:'返回游戏大厅',exact:true}).click();await enterMerge(page);expect(await page.evaluate(key=>localStorage.getItem(key),roundKey)).toBe(saved);
 await page.reload();await enterMerge(page);expect(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).current.score,roundKey)).toBe(4);
 await page.getByRole('button',{name:'重来',exact:true}).click();await expect(page.locator('[data-merge-score]')).toHaveText('0');await expect(page.locator('[data-merge-best]')).toHaveText('4');expect(await page.locator('[data-tile-id]').count()).toBe(2);expect(errors).toEqual([]);
});
test('2048 queued keyboard moves, touch swipe, pause/undo and hidden cancellation',async({page},info)=>{
 await page.goto('/');const board=[2,2,4,0,...Array(12).fill(0)];await setMergeRound(page,board);await enterMerge(page);await freezeMerge(page);
 const sequence:MergeDirection[]=['left','left','down','right','up'];await page.locator('.merge-board').evaluate((n,dirs)=>{for(const d of dirs)n.dispatchEvent(new KeyboardEvent('keydown',{key:`Arrow${d[0].toUpperCase()+d.slice(1)}`,bubbles:true,cancelable:true}));},sequence);await settleMerge(page,6);
 const expected=sequence.reduce(mergeMove,restoreMergeState({board,score:0,moves:0,seed:21}));const saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).current,roundKey);expect(saved.board).toEqual(expected.board);expect(saved.score).toBe(expected.score);expect(saved.moves).toBe(expected.moves);
 await page.locator('.merge-board').scrollIntoViewIfNeeded();await swipeMerge(page,-85,0);await settleMerge(page);const afterSwipe=mergeMove(expected,'left');expect(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).current.board,roundKey)).toEqual(afterSwipe.board);
 await page.getByRole('button',{name:'撤销',exact:true}).click();await page.locator('.merge-board').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowDown');const accepted=await page.evaluate(key=>localStorage.getItem(key),roundKey);await page.keyboard.press('Escape');await page.clock.runFor(1000);expect(await page.evaluate(key=>localStorage.getItem(key),roundKey)).toBe(accepted);await expect(page.locator('.merge-classic')).toHaveAttribute('data-merge-phase','idle');
 await page.keyboard.press('Escape');await page.locator('.merge-board').focus();await page.keyboard.press('ArrowLeft');await page.keyboard.press('ArrowDown');await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});const hidden=await page.evaluate(key=>localStorage.getItem(key),roundKey);await page.clock.runFor(1000);expect(await page.evaluate(key=>localStorage.getItem(key),roundKey)).toBe(hidden);await page.evaluate(()=>{delete (document as unknown as Record<string,unknown>).hidden;document.dispatchEvent(new Event('visibilitychange'));});await mergeLayout(page);await page.screenshot({path:info.outputPath('merge-interruption-settled.png'),fullPage:true});
});
test('2048 continues beyond its title, ends only when blocked and preserves best in reduced motion',async({page},info)=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');await setMergeRound(page,[1024,1024,...Array(14).fill(0)]);await enterMerge(page);await page.locator('.merge-board').focus();await page.keyboard.press('ArrowLeft');await expect(page.locator('[data-merge-score]')).toHaveText('2,048');await expect(page.locator('.game-win-banner')).toHaveCount(0);await page.keyboard.press('ArrowRight');await expect(page.locator('.merge-classic')).toHaveAttribute('data-merge-moves','2');await expect(page.locator('.merge-classic')).toHaveAttribute('data-merge-phase','idle');
 await page.getByRole('button',{name:'返回游戏大厅',exact:true}).click();await setMergeRound(page,[2,4,2,4,4,2,4,2,2,4,2,4,4,2,4,2],128);await enterMerge(page);await expect(page.locator('.merge-classic')).toHaveAttribute('data-merge-over','true');await expect(page.getByRole('button',{name:'向右合并',exact:true})).toBeDisabled();await page.screenshot({path:info.outputPath('merge-game-over.png'),fullPage:true});await page.getByRole('button',{name:'再来一局',exact:true}).click();await expect(page.locator('[data-merge-score]')).toHaveText('0');await expect(page.locator('[data-merge-best]')).toHaveText('2,048');expect(await page.evaluate(key=>localStorage.getItem(key),bestKey)).toBe('2048');
 for(const width of [320,390,768]){await page.setViewportSize({width,height:844});await mergeLayout(page);await page.screenshot({path:info.outputPath(`merge-${width}-reduced.png`),fullPage:true});}
});
test('2048 legacy favorite and no levels, invalid save, storage denial and modified shortcuts',async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('playgarden.progress.v2',JSON.stringify({version:2,favorites:['merge'],lastPlayed:'merge',completed:{merge:[0,1,11]},muted:true}));localStorage.setItem('playgarden.merge.v1.round.free','broken');});await page.goto('/');await page.getByRole('textbox',{name:'搜索游戏'}).fill('2048');await expect(page.locator('.catalog-count')).not.toContainText('0 个关卡');await expect(page.locator('.game-card')).not.toContainText('/0');await expect(page.getByRole('button',{name:'取消收藏2048'})).toBeVisible();await enterMerge(page);const before=await page.evaluate(key=>localStorage.getItem(key),roundKey);await page.locator('.merge-board').focus();await page.keyboard.press('Control+ArrowLeft');expect(await page.evaluate(key=>localStorage.getItem(key),roundKey)).toBe(before);
 await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new Error('blocked');};});await page.getByRole('button',{name:'重来',exact:true}).click();await expect(page.getByText(/浏览器暂时无法保存/)).toBeVisible();await expect(page.locator('[data-tile-id]')).toHaveCount(2);
});

test('2048 queued slide preserves the same in-flight merge-pop animation',async({page},info)=>{
 await page.goto('/');await setMergeRound(page,[2,2,4,0,...Array(12).fill(0)]);await enterMerge(page);await freezeMerge(page);await page.locator('.merge-board').focus();await page.keyboard.press('ArrowLeft');await page.keyboard.press('ArrowDown');await page.clock.runFor(150);await expect(page.locator('.merge-tile-merged')).toHaveCount(1);
 const inner=await page.locator('.merge-tile-merged').elementHandle();await inner!.evaluate(n=>{const a=n.getAnimations()[0];a.pause();a.currentTime=75;(window as unknown as {mergeTestAnimation:Animation}).mergeTestAnimation=a;});await page.clock.runFor(110);await expect(page.locator('.merge-classic')).toHaveAttribute('data-merge-phase','sliding');
 const retained=await inner!.evaluate(n=>({connected:n.isConnected,animation:n.getAnimations().includes((window as unknown as {mergeTestAnimation:Animation}).mergeTestAnimation),scale:new DOMMatrixReadOnly(getComputedStyle(n).transform).a}));expect(retained.connected).toBe(true);expect(retained.animation).toBe(true);expect(retained.scale).toBeGreaterThan(1.05);
 await page.locator('.merge-tile-position').evaluateAll(nodes=>nodes.forEach(n=>n.getAnimations().forEach(a=>{a.pause();a.currentTime=60;})));await page.screenshot({path:info.outputPath('merge-queued-pop-during-slide.png'),animations:'allow',fullPage:true});await settleMerge(page);
});

test('2048 real-time rapid events finish without lost moves and touch remains responsive',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');const board=[2,2,4,0,...Array(12).fill(0)];await setMergeRound(page,board);await enterMerge(page);await page.locator('.merge-board').scrollIntoViewIfNeeded();
 // Deliberately no page.clock installation here. Five events arrive in one
 // real browser task as synthetic DOM input; the app must drain them and
 // finish its own animations. Other journeys use page.keyboard delivery.
 const dirs:MergeDirection[]=['left','left','down','right','up'];
 const started=await page.locator('.merge-board').evaluate((n,sequence)=>{const started=performance.now();for(const d of sequence)n.dispatchEvent(new KeyboardEvent('keydown',{key:`Arrow${d[0].toUpperCase()+d.slice(1)}`,bubbles:true,cancelable:true}));return started;},dirs);
 const expected=dirs.reduce(mergeMove,restoreMergeState({board,score:0,moves:0,seed:21}));
 await expect(page.locator('.merge-classic')).toHaveAttribute('data-merge-moves',String(expected.moves),{timeout:3500});await expect(page.locator('.merge-classic')).toHaveAttribute('data-merge-phase','idle',{timeout:3500});
 expect(await page.evaluate(start=>performance.now()-start,started)).toBeLessThan(3500);
 const actual=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).current,roundKey);expect(actual.board).toEqual(expected.board);expect(actual.score).toBe(expected.score);expect(actual.moves).toBe(expected.moves);
 const next=mergeMove(expected,'down');expect(next.moves).toBe(expected.moves+1);await swipeMerge(page,0,80);await expect(page.locator('.merge-classic')).toHaveAttribute('data-merge-moves',String(next.moves));await expect(page.locator('.merge-classic')).toHaveAttribute('data-merge-phase','idle');const after=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).current,roundKey);expect(after.board).toEqual(next.board);expect(after.score).toBe(next.score);expect(after.moves).toBe(next.moves);
 await mergeLayout(page);await page.screenshot({path:info.outputPath('merge-real-time-rapid-input.png'),fullPage:true});expect(errors).toEqual([]);
});
