// SPDX-License-Identifier: GPL-3.0-only
import { test,expect,type Locator } from '@playwright/test';
import { openGame,chooseLevel,captureErrors } from './helpers';
test('petal words: letters, repeated positions, hint cost, restore and forgiving retry',async({page},info)=>{
  const errors=captureErrors(page),game=page.locator('[data-petal-game]');
  const activate=async(n:Locator)=>info.project.name==='mobile'?n.tap():n.click();
  const key=(c:string)=>game.locator(`[data-petal-key="${c}"]`);
  const guess=async(word:string)=>{for(const c of [...new Set(word.split(''))])await activate(key(c));};
  await openGame(page,'花瓣猜词');
  await page.screenshot({path:info.outputPath('petal-words-start.png'),fullPage:true});
  if(info.project.name==='desktop'){await game.getByRole('group',{name:/字母花田/}).focus();await page.keyboard.press('s');}else await activate(key('S'));
  await expect(key('S')).toBeDisabled();
  await guess('UN');
  await expect(game).toHaveAttribute('data-petal-won','true');
  await expect(page.locator('.status')).toHaveClass(/success/);
  await chooseLevel(page,1);
  await activate(key('O'));
  await expect(game.locator('[data-petal-letter="O"]')).toHaveCount(2);
  await game.getByRole('group',{name:/字母花田/}).focus();await page.keyboard.press('o');
  await expect(game).toHaveAttribute('data-petal-guessed','O');
  await activate(key('Z'));
  await expect(game).toHaveAttribute('data-petal-errors','1');
  await activate(page.getByRole('button',{name:'提示',exact:true}));
  await expect(game).toHaveAttribute('data-petal-guessed','OZM');
  await expect(game).toHaveAttribute('data-petal-errors','2');
  await activate(page.getByRole('button',{name:'撤销',exact:true}));
  await expect(game).toHaveAttribute('data-petal-guessed','OZ');
  await expect(game).toHaveAttribute('data-petal-errors','1');
  await activate(page.getByRole('button',{name:'暂停',exact:true}));
  await expect(key('N')).toBeDisabled();
  await activate(page.getByRole('button',{name:'继续游戏',exact:true}));
  await openGame(page,'花瓣猜词');
  await expect(game).toHaveAttribute('data-petal-id','moon');
  await expect(game).toHaveAttribute('data-petal-guessed','OZ');
  await guess('MN');
  await expect(game).toHaveAttribute('data-petal-won','true');
  await chooseLevel(page,0);await activate(page.getByRole('button',{name:'重来',exact:true}));
  await guess('ABCDEF');
  await expect(game).toHaveAttribute('data-petal-errors','6');
  await expect(game).toHaveAttribute('data-petal-won','false');
  await expect(key('S')).toBeDisabled();
  await expect(game.locator('.pw-message')).toContainText('答案是 SUN');
  await activate(page.getByRole('button',{name:'撤销',exact:true}));
  await expect(key('S')).toBeEnabled();
  await expect(game).toHaveAttribute('data-petal-errors','5');
  await activate(page.getByRole('button',{name:'重来',exact:true}));
  await expect(game).toHaveAttribute('data-petal-guessed','');
  await chooseLevel(page,11);await guess('PUZLE');
  await expect(game).toHaveAttribute('data-petal-won','true');
  await expect(game.locator('[data-petal-letter="Z"]')).toHaveCount(2);
  await page.screenshot({path:info.outputPath('petal-words-final-complete.png'),fullPage:true});
  const boxes=await game.locator('.pw-keyboard button').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return[r.width,r.height];}));
  for(const[w,h]of boxes){expect(w).toBeGreaterThanOrEqual(44);expect(h).toBeGreaterThanOrEqual(44);}
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
