// SPDX-License-Identifier: GPL-3.0-only
import {test,expect,type Page,type TestInfo} from "@playwright/test";
import {openGame,chooseLevel,captureErrors} from "./helpers";
import {storySequenceLevels} from "../src/games/storySequenceLogic";
const root=(p:Page)=>p.locator(".ss-game");
async function select(p:Page,t:TestInfo,id:number){const b=p.locator(`[data-story-card="${id}"]`);if(t.project.name==="mobile")await b.tap();else{await b.focus();await b.press("Enter");}}
async function up(p:Page,t:TestInfo,id:number){if(t.project.name==="mobile")await p.locator("[data-story-up]").tap();else await p.locator(`[data-story-card="${id}"]`).press("ArrowUp");}
async function solve(p:Page,t:TestInfo,index:number){const order=[...storySequenceLevels[index].initial];for(let target=0;target<order.length;target++){if(order.indexOf(target)===target)continue;await select(p,t,target);while(order.indexOf(target)>target){const at=order.indexOf(target);await up(p,t,target);[order[at],order[at-1]]=[order[at-1],order[at]];}}await expect(root(p)).toHaveAttribute("data-story-won","true");await expect(p.locator(".status")).toHaveClass(/success/);await expect(p.getByRole("button",{name:"撤销",exact:true})).toBeDisabled();expect(await root(p).locator("button").evaluateAll(bs=>bs.every(b=>(b as HTMLButtonElement).disabled))).toBe(true);}
test("Story strips: first and final narrative with causality feedback",async({page},info)=>{const errors=captureErrors(page);await openGame(page,"故事排序");const initial=await root(page).getAttribute("data-story-order");await page.screenshot({path:info.outputPath("story-first-start.png"),fullPage:true,animations:"disabled"});await select(page,info,0);await up(page,info,0);await expect(root(page)).toHaveAttribute("data-story-moves","1");await page.getByRole("button",{name:"暂停",exact:true}).click();expect(await root(page).locator("button").evaluateAll(bs=>bs.every(b=>(b as HTMLButtonElement).disabled))).toBe(true);await page.getByRole("button",{name:"继续游戏",exact:true}).click();await page.getByRole("button",{name:"撤销",exact:true}).click();await expect(root(page)).toHaveAttribute("data-story-order",initial!);await select(page,info,0);await up(page,info,0);await page.getByRole("button",{name:"重来",exact:true}).click();await expect(root(page)).toHaveAttribute("data-story-order",initial!);await page.locator("[data-story-review]").click();await expect(page.locator(".ss-feedback")).toContainText("第一次浇水发生在埋豆子之后");await page.getByRole("button",{name:"提示",exact:true}).click();await expect(page.locator(".ss-hinted")).toHaveCount(1);await expect(root(page)).toHaveAttribute("data-story-order",initial!);await solve(page,info,0);await chooseLevel(page,7);await page.screenshot({path:info.outputPath("story-final-start.png"),fullPage:true,animations:"disabled"});await solve(page,info,7);await expect(page.locator("[data-story-card]").first()).toHaveCSS("opacity","1");await page.screenshot({path:info.outputPath("story-final-win.png"),fullPage:true,animations:"disabled"});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);});
