// SPDX-License-Identifier: GPL-3.0-only
import {test,expect,type Page,type Locator} from '@playwright/test';
import {openGame,chooseLevel,captureErrors} from './helpers';
import type {VikingSnapshot} from '../src/vendor/vikingCore';
type Reading=VikingSnapshot&{intro:boolean;paused:boolean;replayRunning:boolean};
const read=(page:Page)=>page.evaluate(()=>{const f=(window as unknown as {__vikingRead?:()=>Reading}).__vikingRead;if(!f)throw Error('Missing read-only Viking observer');return f();});
const first='L U U L L L L U U L L L L U L U D D R D D D R R R R R D D D D D D D'.split(' '),short='D D D D D L L L L D D'.split(' ');
test('original first middle and final reverse routes, scores, replay and touch lifecycle',async({page},info)=>{
 test.setTimeout(150000);const mobile=info.project.name==='mobile',errors=captureErrors(page),outside:string[]=[],act=async(l:Locator)=>mobile?l.tap():l.click();
 page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:4173/'))outside.push(r.url());});
 await openGame(page,'维京倒行记');await expect(page.getByLabel('选择关卡',{exact:true}).locator('option')).toHaveCount(7);
 await page.evaluate(()=>localStorage.setItem('playgarden.viking-unrelated','keep'));
 const walk=async(letter:string)=>{const labels:Record<string,string>={U:'向上走',D:'向下走',L:'向左走',R:'向右走'},keys:Record<string,string>={U:'ArrowUp',D:'ArrowDown',L:'ArrowLeft',R:'ArrowRight'};if(mobile)await act(page.getByRole('button',{name:labels[letter],exact:true}));else await page.keyboard.press(keys[letter]);};
 const begin=async()=>{await act(page.getByRole('button',{name:'开始回溯',exact:true}));if(!mobile)await expect(page.locator('.vk-board')).toBeFocused();};
 await begin();for(const d of ['L','U','U','D'])await walk(d);let s=await read(page);expect(s.player).toEqual({x:13,y:6});expect(s.lastAction?.blockedBy).toBe('object');expect(s.repaired).toEqual([153]);expect(s.actionCount).toBe(4);await expect(page.locator('.vk-message')).toContainText('挡住');await page.screenshot({path:info.outputPath('viking-first-repaired-object-blocks.png'),fullPage:true});
 await act(page.getByRole('button',{name:'暂停',exact:true}));const frozen=(await read(page)).actionCount;await expect(page.getByRole('button',{name:'向下走',exact:true})).toBeDisabled();await page.waitForTimeout(400);expect((await read(page)).actionCount).toBe(frozen);await act(page.getByRole('button',{name:'继续游戏',exact:true}));await act(page.getByRole('button',{name:'撤销',exact:true}));expect((await read(page)).actionCount).toBe(3);
 await page.reload();await openGame(page,'维京倒行记');await chooseLevel(page,0);expect((await read(page)).player).toEqual({x:13,y:6});expect((await read(page)).actionCount).toBe(3);expect((await read(page)).intro).toBe(false);await act(page.getByRole('button',{name:'重来',exact:true}));await begin();
 for(let i=0;i<first.length;i++){await walk(first[i]);if(i===6){s=await read(page);expect(s.clothed).toBe(false);expect(s.liveScore.pickups).toBe(1);}if(i===11){s=await read(page);expect(s.clothed).toBe(true);expect(s.liveScore.pickups).toBe(2);}if(i===15){s=await read(page);expect(s.player).toEqual({x:4,y:3});expect(s.lastAction?.blockedBy).toBe('wall');expect(s.lastAction?.change).toBe('repair');expect(s.repaired).toContain(44);await page.screenshot({path:info.outputPath('viking-first-upward-wall-repair.png'),fullPage:true});}}
 await expect(page.locator('.vk-game')).toHaveAttribute('data-vk-phase','score');s=await read(page);expect(s.score).toMatchObject({pickups:3,objects:6,pickupPercent:43,objectPercent:27});expect(s.actionCount).toBe(33);await expect(page.locator('.status')).toHaveClass(/success/);await expect(page.locator('.vk-scorecard')).toContainText('没有达到100%也能继续');await page.screenshot({path:info.outputPath('viking-first-earned-score.png'),fullPage:true});
 await act(page.getByRole('button',{name:'观看正向回放',exact:true}));await expect.poll(async()=>(await read(page)).replayCursor).toBeGreaterThan(0);await act(page.getByRole('button',{name:'暂停回放',exact:true}));const cursor=(await read(page)).replayCursor;await expect(page.locator('.vk-replay-progress')).toContainText(`已回放 ${cursor}/33`);await page.waitForTimeout(500);expect((await read(page)).replayCursor).toBe(cursor);await act(page.getByRole('button',{name:'暂停',exact:true}));await expect(page.getByRole('button',{name:'继续回放',exact:true})).toBeDisabled();await act(page.getByRole('button',{name:'继续游戏',exact:true}));await act(page.getByRole('button',{name:'继续回放',exact:true}));await expect(page.locator('.vk-game')).toHaveAttribute('data-vk-phase','replayDone',{timeout:12000});s=await read(page);expect(s.player).toEqual({x:14,y:8});expect(s.liveScore.objects).toBe(0);expect(s.score.objectPercent).toBe(27);await page.screenshot({path:info.outputPath('viking-first-complete-forward-replay.png'),fullPage:true});
 await act(page.getByRole('button',{name:'再看一次回放',exact:true}));await expect.poll(async()=>(await read(page)).replayCursor).toBeGreaterThan(0);await act(page.getByRole('button',{name:'返回游戏大厅',exact:true}));expect(await page.evaluate(()=>typeof(window as unknown as Record<string,unknown>).__vikingRead)).toBe('undefined');const stopped=await page.evaluate(()=>localStorage.getItem('playgarden.viking.v1.0'));await page.waitForTimeout(500);expect(await page.evaluate(()=>localStorage.getItem('playgarden.viking.v1.0'))).toBe(stopped);
 await openGame(page,'维京倒行记');await chooseLevel(page,0);expect((await read(page)).replayRunning).toBe(false);const resumed=(await read(page)).replayCursor;await page.waitForTimeout(350);expect((await read(page)).replayCursor).toBe(resumed);await act(page.getByRole('button',{name:'跳过回放',exact:true}));await expect(page.locator('.vk-game')).toHaveAttribute('data-vk-phase','replayDone');
 await chooseLevel(page,3);await begin();for(const d of short)await walk(d);expect((await read(page)).score).toMatchObject({objects:3,pickups:0,objectPercent:11});await page.screenshot({path:info.outputPath('viking-middle-earned-score.png'),fullPage:true});await act(page.getByRole('button',{name:'观看正向回放',exact:true}));await act(page.getByRole('button',{name:'重来',exact:true}));expect((await read(page)).phase).toBe('playing');expect((await read(page)).actionCount).toBe(0);expect((await read(page)).cleared).toEqual([]);await begin();for(const d of short)await walk(d);await act(page.getByRole('button',{name:'观看正向回放',exact:true}));await act(page.getByRole('button',{name:'跳过回放',exact:true}));await expect(page.locator('.vk-game')).toHaveAttribute('data-vk-phase','replayDone');
 // An impossible save cannot manufacture a completed level. This is the only
 // malformed-storage fixture; gameplay wins still use real directional input.
 await page.evaluate(()=>localStorage.setItem('playgarden.viking.v1.6',JSON.stringify({version:1,levelIndex:6,inputs:[],exitDirection:'down',phase:'complete',replayCursor:0})));await chooseLevel(page,6);expect((await read(page)).phase).toBe('playing');expect((await read(page)).actionCount).toBe(0);await begin();
 if(mobile){await act(page.getByRole('button',{name:'放大地图',exact:true}));const box=page.locator('.vk-scroll');await box.scrollIntoViewIfNeeded();const b=(await box.boundingBox())!,cdp=await page.context().newCDPSession(page),x=b.x+b.width-20,y=b.y+Math.min(220,b.height-20),before=(await read(page)).player;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:4}]});for(let n=1;n<=8;n++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-n*25,y:y-n*12,id:4}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(()=>box.evaluate(e=>e.scrollLeft)).toBeGreaterThan(0);expect((await read(page)).player).toEqual(before);expect((await read(page)).actionCount).toBe(0);await page.screenshot({path:info.outputPath('viking-final-touch-pan.png'),fullPage:true});await act(page.getByRole('button',{name:'查看全盘',exact:true}));}
 for(const d of short)await walk(d);s=await read(page);expect(s.phase).toBe('score');expect(s.score).toMatchObject({objects:4,objectPercent:6,pickups:0});await act(page.getByRole('button',{name:'观看正向回放',exact:true}));await expect(page.getByLabel('第七日结局',{exact:true})).toBeVisible({timeout:8000});s=await read(page);expect(s.liveScore.objects).toBe(0);expect(s.player).toEqual({x:14,y:8});await expect(page.locator('.vk-message')).toContainText('第七日');await expect(page.locator('.status')).toContainText('第七日');await page.screenshot({path:info.outputPath('viking-final-earned-ending.png'),fullPage:true});
 await page.reload();await openGame(page,'维京倒行记');await chooseLevel(page,6);await expect(page.getByLabel('第七日结局',{exact:true})).toBeVisible();expect((await read(page)).replayRunning).toBe(false);if(mobile){await page.setViewportSize({width:320,height:760});await page.screenshot({path:info.outputPath('viking-320px-persisted-ending.png'),fullPage:true});}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(await page.evaluate(()=>localStorage.getItem('playgarden.viking-unrelated'))).toBe('keep');expect(errors).toEqual([]);expect(outside).toEqual([]);
});
