import type { AkariLevel } from "./akariLogic";
export const akariLevels: AkariLevel[] = [
  {
    id: "akari-001",
    title: "初见灯光 · 1",
    chapter: 0,
    size: 4,
    board: "0....1....#.2...",
  },
  {
    id: "akari-002",
    title: "初见灯光 · 2",
    chapter: 0,
    size: 4,
    board: "....0..1.#.#...#",
  },
  {
    id: "akari-003",
    title: "初见灯光 · 3",
    chapter: 0,
    size: 4,
    board: "...2....#0......",
  },
  {
    id: "akari-004",
    title: "初见灯光 · 4",
    chapter: 0,
    size: 4,
    board: "###..0....#...#.",
  },
  {
    id: "akari-005",
    title: "初见灯光 · 5",
    chapter: 0,
    size: 4,
    board: "#..#.1.##....##.",
  },
  {
    id: "akari-006",
    title: "初见灯光 · 6",
    chapter: 0,
    size: 4,
    board: "..#...1#2....#..",
  },
  {
    id: "akari-007",
    title: "初见灯光 · 7",
    chapter: 0,
    size: 4,
    board: ".2.1..#...0.....",
  },
  {
    id: "akari-008",
    title: "初见灯光 · 8",
    chapter: 0,
    size: 4,
    board: "....01....1.#.0.",
  },
  {
    id: "akari-009",
    title: "初见灯光 · 9",
    chapter: 0,
    size: 4,
    board: "#......0#..0.1.#",
  },
  {
    id: "akari-010",
    title: "隔墙相望 · 1",
    chapter: 1,
    size: 5,
    board: "..#.#.1.#..1#......2#..#.",
  },
  {
    id: "akari-011",
    title: "隔墙相望 · 2",
    chapter: 1,
    size: 5,
    board: "#........0#.0..1.....2...",
  },
  {
    id: "akari-012",
    title: "隔墙相望 · 3",
    chapter: 1,
    size: 5,
    board: ".....0.1.....2.##...#0.#.",
  },
  {
    id: "akari-013",
    title: "隔墙相望 · 4",
    chapter: 1,
    size: 5,
    board: ".1..#.#.#..##...000.....#",
  },
  {
    id: "akari-014",
    title: "隔墙相望 · 5",
    chapter: 1,
    size: 5,
    board: "....1..0....1...#0...#..#",
  },
  {
    id: "akari-015",
    title: "隔墙相望 · 6",
    chapter: 1,
    size: 5,
    board: "..0.#....#...2.....#1.1..",
  },
  {
    id: "akari-016",
    title: "隔墙相望 · 7",
    chapter: 1,
    size: 5,
    board: "...#......1..1..0#......#",
  },
  {
    id: "akari-017",
    title: "隔墙相望 · 8",
    chapter: 1,
    size: 5,
    board: ".#........1...00......2..",
  },
  {
    id: "akari-018",
    title: "隔墙相望 · 9",
    chapter: 1,
    size: 5,
    board: "...#...1.#.#.#........2.#",
  },
  {
    id: "akari-019",
    title: "交错光径 · 1",
    chapter: 2,
    size: 6,
    board: "##1....1..0..0.##..0......00.......#",
  },
  {
    id: "akari-020",
    title: "交错光径 · 2",
    chapter: 2,
    size: 6,
    board: ".1.......0.........#..2..#.#..##.#0.",
  },
  {
    id: "akari-021",
    title: "交错光径 · 3",
    chapter: 2,
    size: 6,
    board: "..2........0......#0...#.....0.#0...",
  },
  {
    id: "akari-022",
    title: "交错光径 · 4",
    chapter: 2,
    size: 6,
    board: "#....0....##..3...#...0......#.#..#.",
  },
  {
    id: "akari-023",
    title: "交错光径 · 5",
    chapter: 2,
    size: 6,
    board: "##.00....#0.0.#.......0.##.....1.#0.",
  },
  {
    id: "akari-024",
    title: "交错光径 · 6",
    chapter: 2,
    size: 6,
    board: "#.....#0.....#....2##.1#.#..#..#0.1.",
  },
  {
    id: "akari-025",
    title: "交错光径 · 7",
    chapter: 2,
    size: 6,
    board: "#1...#..##....#..0..1..#.....010....",
  },
  {
    id: "akari-026",
    title: "交错光径 · 8",
    chapter: 2,
    size: 6,
    board: "....#..0..2.....###.11.1#...#.#.....",
  },
  {
    id: "akari-027",
    title: "交错光径 · 9",
    chapter: 2,
    size: 6,
    board: "0....#0...0.###...#..1..#...###..2..",
  },
  {
    id: "akari-028",
    title: "夜园全亮 · 1",
    chapter: 3,
    size: 7,
    board: "....0#.01.####1....0.....1..#..20.#....2........#",
  },
  {
    id: "akari-029",
    title: "夜园全亮 · 2",
    chapter: 3,
    size: 7,
    board: "..1...#.....01..0.....##.#.......3.###.....1..#..",
  },
  {
    id: "akari-030",
    title: "夜园全亮 · 3",
    chapter: 3,
    size: 7,
    board: ".#..###..#.1.......#02....#0#..1....1...0#......#",
  },
  {
    id: "akari-031",
    title: "夜园全亮 · 4",
    chapter: 3,
    size: 7,
    board: ".#....#...0..........3...#.#...#.0...#0.....#....",
  },
  {
    id: "akari-032",
    title: "夜园全亮 · 5",
    chapter: 3,
    size: 7,
    board: "##..1...#...#.##.#.##...#0.#0......#..###.....0..",
  },
  {
    id: "akari-033",
    title: "夜园全亮 · 6",
    chapter: 3,
    size: 7,
    board: "#...#..#.0.....#..#2#.............#.#..0.0..1....",
  },
  {
    id: "akari-034",
    title: "夜园全亮 · 7",
    chapter: 3,
    size: 7,
    board: "#0.##..1..#.0....#.#......1..##.1..#.......#....1",
  },
  {
    id: "akari-035",
    title: "夜园全亮 · 8",
    chapter: 3,
    size: 7,
    board: "#0..#.##.#..1......1.....1...1....#.0#...#.......",
  },
  {
    id: "akari-036",
    title: "夜园全亮 · 9",
    chapter: 3,
    size: 7,
    board: "#1..#...............2##.###..........1.#.....0#0.",
  },
];
