// SPDX-License-Identifier: GPL-3.0-only
import {useEffect,useRef,useState,type KeyboardEvent} from 'react';
import type {GameProps} from '../lib/types';
import {amazonGardenLevels,amznInitial,amznMoves,amznArrows,amznRound,amznChoice,amznLabel,type AmznTurn} from './amazonGardenLogic';
import './amazonGarden.css';
export default function AmazonGarden(p:GameProps){return <AmznBoard key={`${p.level}:${p.resetToken}`} {...p}/>;}
function AmznBoard({level,paused,hintToken,undoToken,onComplete,onStatus}:GameProps){const lesson=amazonGardenLevels[level]??amazonGardenLevels[0];const [history,setHistory]=useState([amznInitial(level)]),[draft,setDraft]=useState<number|null>(null),[hint,setHint]=useState<AmznTurn|null>(null),[message,setMessage]=useState(lesson.tip);const s=history[history.length-1],live=useRef({history,s,draft,paused});live.current={history,s,draft,paused};const tokens=useRef({hintToken,undoToken}),done=useRef(false),callbacks=useRef({onComplete,onStatus});callbacks.current={onComplete,onStatus};const locked=paused||s.result!=='playing',allowed=draft===null?amznMoves(s,0):amznArrows(s,0,draft);function report(t:string){setMessage(t);callbacks.current.onStatus(t);}useEffect(()=>{callbacks.current.onStatus(lesson.tip);},[]);useEffect(()=>{if(s.result==='won'&&!paused&&!done.current){done.current=true;callbacks.current.onComplete();}},[s.result,paused]);function cancel(){if(live.current.paused||live.current.s.result!=='playing')return;live.current.draft=null;setDraft(null);setHint(null);report('已取消尚未射箭的移动，没有消耗回合。');}useEffect(()=>{if(tokens.current.undoToken===undoToken)return;tokens.current.undoToken=undoToken;if(paused||done.current)return;if(draft!==null){cancel();return;}if(history.length>1){setHistory(history.slice(0,-1));setHint(null);report('已撤销你和电脑的完整回合。');}},[undoToken]);useEffect(()=>{if(tokens.current.hintToken===hintToken)return;tokens.current.hintToken=hintToken;if(locked)return;const t=amznChoice(s,0,draft??undefined);setHint(t);report(t?`当前局部建议：${draft===null?`移到 ${amznLabel(t.to)}，再`:''}射向 ${amznLabel(t.arrow)}。按可达空间评分，没有搜索到整局结尾。`:'没有合法的箭路。');},[hintToken]);function choose(p:number){const n=live.current;if(n.paused||n.s.result!=='playing')return;if(n.draft===null){if(!amznMoves(n.s,0).includes(p))return;live.current.draft=p;setDraft(p);setHint(null);report('移动已预览。现在射箭到空格，或取消这一步。');return;}if(!amznArrows(n.s,0,n.draft).includes(p))return;const next=amznRound(n.s,{to:n.draft,arrow:p}),h=[...n.history,next];live.current={history:h,s:next,draft:null,paused};setHistory(h);setDraft(null);setHint(null);report(next.result==='won'?'电脑已经没有合法移动，你赢得这片花园！':next.result==='lost'?'你的棋子没有可走的格子。可以撤销完整回合。':'电脑也完成了移动与射箭。轮到你了。');}function guard(e:KeyboardEvent<HTMLButtonElement>){if((e.repeat||e.ctrlKey||e.metaKey||e.altKey)&&['Enter',' '].includes(e.key))e.preventDefault();}
 return <div className="amzn-game" data-amzn-state={JSON.stringify(s)} data-amzn-result={s.result} data-amzn-turns={s.turns} data-amzn-phase={draft===null?'move':'arrow'}><section className="amzn-panel"><header><div><span className="amzn-kicker">AMAZONS · 一步一箭</span><h3>{lesson.title}</h3></div><b>{level+1} / 8</b></header><p>每回合先沿直线或斜线移动，再从新位置射箭。箭落下的格子永远封闭。让电脑无路可走。</p><div className="amzn-steps"><span className={draft===null?'amzn-active':''}>1 移动花羽</span><span className={draft!==null?'amzn-active':''}>2 射出封格箭</span></div><div className="amzn-board" aria-label="箭羽争地五乘五棋盘">{Array.from({length:25},(_,i)=>{const initialRock=!lesson.open.includes(i),blocked=s.blocked.includes(i),you=i===(draft??s.you),bot=i===s.bot,mark=hint&&(draft===null?hint.to===i:hint.arrow===i);return <button key={i} data-amzn-cell={i} className={`${initialRock?'amzn-rock':blocked?'amzn-arrow':''} ${you?'amzn-you':''} ${bot?'amzn-bot':''} ${allowed.includes(i)?'amzn-legal':''} ${mark?'amzn-hinted':''}`} disabled={locked||!allowed.includes(i)} aria-label={`${amznLabel(i)}，${you?'你的花羽':bot?'电脑花羽':initialRock?'岩石':blocked?'已封箭格':draft===null?'空格，移动到这里':'空格，向这里射箭'}`} onKeyDown={guard} onClick={()=>choose(i)}><span aria-hidden="true">{you?'♛':bot?'♜':initialRock?'':blocked?'✦':draft!==null&&i===s.you?'◌':''}</span><small>{Math.floor(i/5)+1},{i%5+1}</small></button>;})}</div><div className="amzn-controls"><span>{paused?'暂停中':s.result==='won'?'花园属于你':s.result==='lost'?'暂时困住了':`已完成 ${s.turns} 回合`}</span><button type="button" disabled={locked||draft===null} onKeyDown={guard} onClick={cancel}>取消本步</button></div><p className="amzn-message" role="status">{message}</p></section><aside className="amzn-aside"><span className="amzn-kicker">一支箭，改变整片花园</span><h3>留给自己转身的空间</h3><ul><li>移动和射箭都像国际象棋的皇后，沿八方向任意远。</li><li>不能越过岩石、箭或任意棋子；箭不能射中站人的格子。</li><li>刚离开的格子可以射箭。轮到某一方时，如果没有合法移动就输。</li></ul><p>{lesson.tip}</p><details><summary>小棋盘、操作与撤销</summary><p>原创 5×5 教学花园，每方一枚棋子，与常规大棋盘四子赛制不同。电脑只按当前可达空间选择，不是完美对手。Tab、Enter / 空格或轻点格子；暂停保留未完成移动，取消本步可回到射箭前。撤销先取消半步，再撤销双方完整回合。胜利后锁定。</p></details></aside></div>;
}
