import type { BlackboxLevel } from './blackboxLogic';
// Generated by scripts/blackbox/generate.mjs. Evidence certificates stay outside the bundle.
export const blackboxChapters = [
  {
    "id": "first-signals",
    "title": "听懂一颗星",
    "lesson": "先从北边发射。● 表示光束正面碰到星；↩ 表示返回入口；另一侧的编号表示出口。用交叉证据找一颗星。",
    "count": 3
  },
  {
    "id": "two-shadows",
    "title": "两颗星的影子",
    "lesson": "正前方有星会优先吸收；仅前侧有星，会在进入那一行前转弯，远离星。换一边探测，别只看一条线。",
    "count": 9
  },
  {
    "id": "turn-together",
    "title": "转弯遇上转弯",
    "lesson": "两颗星同时在前侧，会让光束掉头。中途可以连续转弯；返回并不说明入口正前方有星。",
    "count": 12
  },
  {
    "id": "wider-sky",
    "title": "把视野放宽",
    "lesson": "一条贯通的路线同时确定入口和出口。点击已有记录可以回看，不会增加探测数。先选能区别多种猜想的入口。",
    "count": 16
  },
  {
    "id": "cross-evidence",
    "title": "让证据交汇",
    "lesson": "★ 是你的猜测，× 是空格笔记。它们不改变光束，也不限制提示的候选。发现冲突就撤销标注，再换一个角度。",
    "count": 20
  },
  {
    "id": "deep-nebula",
    "title": "星雾深处",
    "lesson": "四颗星会遮挡或改变彼此的信号。没有限时或探测上限；验证比较所有边缘响应，任何完全等价的布局都能过关。",
    "count": 24
  }
];
export const blackboxLevels: BlackboxLevel[] = [
  {
    "id": "blackbox-001",
    "title": "听懂一颗星 · 1",
    "chapter": 0,
    "size": 3,
    "atoms": [
      4
    ]
  },
  {
    "id": "blackbox-002",
    "title": "听懂一颗星 · 2",
    "chapter": 0,
    "size": 3,
    "atoms": [
      1
    ]
  },
  {
    "id": "blackbox-003",
    "title": "听懂一颗星 · 3",
    "chapter": 0,
    "size": 3,
    "atoms": [
      0
    ]
  },
  {
    "id": "blackbox-004",
    "title": "两颗星的影子 · 1",
    "chapter": 1,
    "size": 4,
    "atoms": [
      1,
      13
    ]
  },
  {
    "id": "blackbox-005",
    "title": "两颗星的影子 · 2",
    "chapter": 1,
    "size": 4,
    "atoms": [
      1,
      4
    ]
  },
  {
    "id": "blackbox-006",
    "title": "两颗星的影子 · 3",
    "chapter": 1,
    "size": 4,
    "atoms": [
      0,
      10
    ]
  },
  {
    "id": "blackbox-007",
    "title": "两颗星的影子 · 4",
    "chapter": 1,
    "size": 4,
    "atoms": [
      5,
      6
    ]
  },
  {
    "id": "blackbox-008",
    "title": "两颗星的影子 · 5",
    "chapter": 1,
    "size": 4,
    "atoms": [
      0,
      1
    ]
  },
  {
    "id": "blackbox-009",
    "title": "两颗星的影子 · 6",
    "chapter": 1,
    "size": 4,
    "atoms": [
      1,
      11
    ]
  },
  {
    "id": "blackbox-010",
    "title": "两颗星的影子 · 7",
    "chapter": 1,
    "size": 4,
    "atoms": [
      0,
      5
    ]
  },
  {
    "id": "blackbox-011",
    "title": "两颗星的影子 · 8",
    "chapter": 1,
    "size": 4,
    "atoms": [
      1,
      9
    ]
  },
  {
    "id": "blackbox-012",
    "title": "两颗星的影子 · 9",
    "chapter": 1,
    "size": 4,
    "atoms": [
      1,
      5
    ]
  },
  {
    "id": "blackbox-013",
    "title": "转弯遇上转弯 · 1",
    "chapter": 2,
    "size": 4,
    "atoms": [
      1,
      6,
      8
    ]
  },
  {
    "id": "blackbox-014",
    "title": "转弯遇上转弯 · 2",
    "chapter": 2,
    "size": 4,
    "atoms": [
      1,
      2,
      8
    ]
  },
  {
    "id": "blackbox-015",
    "title": "转弯遇上转弯 · 3",
    "chapter": 2,
    "size": 4,
    "atoms": [
      1,
      6,
      14
    ]
  },
  {
    "id": "blackbox-016",
    "title": "转弯遇上转弯 · 4",
    "chapter": 2,
    "size": 4,
    "atoms": [
      1,
      5,
      8
    ]
  },
  {
    "id": "blackbox-017",
    "title": "转弯遇上转弯 · 5",
    "chapter": 2,
    "size": 4,
    "atoms": [
      0,
      6,
      10
    ]
  },
  {
    "id": "blackbox-018",
    "title": "转弯遇上转弯 · 6",
    "chapter": 2,
    "size": 4,
    "atoms": [
      1,
      2,
      5
    ]
  },
  {
    "id": "blackbox-019",
    "title": "转弯遇上转弯 · 7",
    "chapter": 2,
    "size": 4,
    "atoms": [
      0,
      2,
      7
    ]
  },
  {
    "id": "blackbox-020",
    "title": "转弯遇上转弯 · 8",
    "chapter": 2,
    "size": 4,
    "atoms": [
      1,
      5,
      13
    ]
  },
  {
    "id": "blackbox-021",
    "title": "转弯遇上转弯 · 9",
    "chapter": 2,
    "size": 4,
    "atoms": [
      0,
      5,
      6
    ]
  },
  {
    "id": "blackbox-022",
    "title": "转弯遇上转弯 · 10",
    "chapter": 2,
    "size": 4,
    "atoms": [
      0,
      3,
      5
    ]
  },
  {
    "id": "blackbox-023",
    "title": "转弯遇上转弯 · 11",
    "chapter": 2,
    "size": 4,
    "atoms": [
      0,
      2,
      11
    ]
  },
  {
    "id": "blackbox-024",
    "title": "转弯遇上转弯 · 12",
    "chapter": 2,
    "size": 4,
    "atoms": [
      0,
      10,
      11
    ]
  },
  {
    "id": "blackbox-025",
    "title": "把视野放宽 · 1",
    "chapter": 3,
    "size": 5,
    "atoms": [
      1,
      14
    ]
  },
  {
    "id": "blackbox-026",
    "title": "把视野放宽 · 2",
    "chapter": 3,
    "size": 5,
    "atoms": [
      6,
      12
    ]
  },
  {
    "id": "blackbox-027",
    "title": "把视野放宽 · 3",
    "chapter": 3,
    "size": 5,
    "atoms": [
      2,
      17
    ]
  },
  {
    "id": "blackbox-028",
    "title": "把视野放宽 · 4",
    "chapter": 3,
    "size": 5,
    "atoms": [
      0,
      8
    ]
  },
  {
    "id": "blackbox-029",
    "title": "把视野放宽 · 5",
    "chapter": 3,
    "size": 5,
    "atoms": [
      1,
      11
    ]
  },
  {
    "id": "blackbox-030",
    "title": "把视野放宽 · 6",
    "chapter": 3,
    "size": 5,
    "atoms": [
      0,
      14
    ]
  },
  {
    "id": "blackbox-031",
    "title": "把视野放宽 · 7",
    "chapter": 3,
    "size": 5,
    "atoms": [
      6,
      8
    ]
  },
  {
    "id": "blackbox-032",
    "title": "把视野放宽 · 8",
    "chapter": 3,
    "size": 5,
    "atoms": [
      1,
      6
    ]
  },
  {
    "id": "blackbox-033",
    "title": "把视野放宽 · 9",
    "chapter": 3,
    "size": 5,
    "atoms": [
      6,
      7
    ]
  },
  {
    "id": "blackbox-034",
    "title": "把视野放宽 · 10",
    "chapter": 3,
    "size": 5,
    "atoms": [
      0,
      24
    ]
  },
  {
    "id": "blackbox-035",
    "title": "把视野放宽 · 11",
    "chapter": 3,
    "size": 5,
    "atoms": [
      1,
      12
    ]
  },
  {
    "id": "blackbox-036",
    "title": "把视野放宽 · 12",
    "chapter": 3,
    "size": 5,
    "atoms": [
      7,
      11
    ]
  },
  {
    "id": "blackbox-037",
    "title": "把视野放宽 · 13",
    "chapter": 3,
    "size": 5,
    "atoms": [
      0,
      1
    ]
  },
  {
    "id": "blackbox-038",
    "title": "把视野放宽 · 14",
    "chapter": 3,
    "size": 5,
    "atoms": [
      7,
      12
    ]
  },
  {
    "id": "blackbox-039",
    "title": "把视野放宽 · 15",
    "chapter": 3,
    "size": 5,
    "atoms": [
      2,
      11
    ]
  },
  {
    "id": "blackbox-040",
    "title": "把视野放宽 · 16",
    "chapter": 3,
    "size": 5,
    "atoms": [
      2,
      7
    ]
  },
  {
    "id": "blackbox-041",
    "title": "让证据交汇 · 1",
    "chapter": 4,
    "size": 5,
    "atoms": [
      0,
      13,
      19
    ]
  },
  {
    "id": "blackbox-042",
    "title": "让证据交汇 · 2",
    "chapter": 4,
    "size": 5,
    "atoms": [
      0,
      13,
      22
    ]
  },
  {
    "id": "blackbox-043",
    "title": "让证据交汇 · 3",
    "chapter": 4,
    "size": 5,
    "atoms": [
      0,
      1,
      7
    ]
  },
  {
    "id": "blackbox-044",
    "title": "让证据交汇 · 4",
    "chapter": 4,
    "size": 5,
    "atoms": [
      1,
      6,
      12
    ]
  },
  {
    "id": "blackbox-045",
    "title": "让证据交汇 · 5",
    "chapter": 4,
    "size": 5,
    "atoms": [
      0,
      9,
      14
    ]
  },
  {
    "id": "blackbox-046",
    "title": "让证据交汇 · 6",
    "chapter": 4,
    "size": 5,
    "atoms": [
      1,
      6,
      7
    ]
  },
  {
    "id": "blackbox-047",
    "title": "让证据交汇 · 7",
    "chapter": 4,
    "size": 5,
    "atoms": [
      1,
      13,
      16
    ]
  },
  {
    "id": "blackbox-048",
    "title": "让证据交汇 · 8",
    "chapter": 4,
    "size": 5,
    "atoms": [
      0,
      4,
      16
    ]
  },
  {
    "id": "blackbox-049",
    "title": "让证据交汇 · 9",
    "chapter": 4,
    "size": 5,
    "atoms": [
      0,
      2,
      21
    ]
  },
  {
    "id": "blackbox-050",
    "title": "让证据交汇 · 10",
    "chapter": 4,
    "size": 5,
    "atoms": [
      2,
      7,
      11
    ]
  },
  {
    "id": "blackbox-051",
    "title": "让证据交汇 · 11",
    "chapter": 4,
    "size": 5,
    "atoms": [
      6,
      7,
      12
    ]
  },
  {
    "id": "blackbox-052",
    "title": "让证据交汇 · 12",
    "chapter": 4,
    "size": 5,
    "atoms": [
      0,
      6,
      18
    ]
  },
  {
    "id": "blackbox-053",
    "title": "让证据交汇 · 13",
    "chapter": 4,
    "size": 5,
    "atoms": [
      1,
      2,
      22
    ]
  },
  {
    "id": "blackbox-054",
    "title": "让证据交汇 · 14",
    "chapter": 4,
    "size": 5,
    "atoms": [
      1,
      6,
      18
    ]
  },
  {
    "id": "blackbox-055",
    "title": "让证据交汇 · 15",
    "chapter": 4,
    "size": 5,
    "atoms": [
      0,
      1,
      12
    ]
  },
  {
    "id": "blackbox-056",
    "title": "让证据交汇 · 16",
    "chapter": 4,
    "size": 5,
    "atoms": [
      0,
      7,
      9
    ]
  },
  {
    "id": "blackbox-057",
    "title": "让证据交汇 · 17",
    "chapter": 4,
    "size": 5,
    "atoms": [
      6,
      12,
      18
    ]
  },
  {
    "id": "blackbox-058",
    "title": "让证据交汇 · 18",
    "chapter": 4,
    "size": 5,
    "atoms": [
      1,
      16,
      18
    ]
  },
  {
    "id": "blackbox-059",
    "title": "让证据交汇 · 19",
    "chapter": 4,
    "size": 5,
    "atoms": [
      1,
      2,
      23
    ]
  },
  {
    "id": "blackbox-060",
    "title": "让证据交汇 · 20",
    "chapter": 4,
    "size": 5,
    "atoms": [
      1,
      10,
      18
    ]
  },
  {
    "id": "blackbox-061",
    "title": "星雾深处 · 1",
    "chapter": 5,
    "size": 5,
    "atoms": [
      1,
      2,
      8,
      21
    ]
  },
  {
    "id": "blackbox-062",
    "title": "星雾深处 · 2",
    "chapter": 5,
    "size": 5,
    "atoms": [
      0,
      1,
      14,
      21
    ]
  },
  {
    "id": "blackbox-063",
    "title": "星雾深处 · 3",
    "chapter": 5,
    "size": 5,
    "atoms": [
      2,
      6,
      7,
      8
    ]
  },
  {
    "id": "blackbox-064",
    "title": "星雾深处 · 4",
    "chapter": 5,
    "size": 5,
    "atoms": [
      2,
      7,
      11,
      13
    ]
  },
  {
    "id": "blackbox-065",
    "title": "星雾深处 · 5",
    "chapter": 5,
    "size": 5,
    "atoms": [
      1,
      2,
      19,
      21
    ]
  },
  {
    "id": "blackbox-066",
    "title": "星雾深处 · 6",
    "chapter": 5,
    "size": 5,
    "atoms": [
      0,
      12,
      13,
      18
    ]
  },
  {
    "id": "blackbox-067",
    "title": "星雾深处 · 7",
    "chapter": 5,
    "size": 5,
    "atoms": [
      1,
      2,
      5,
      10
    ]
  },
  {
    "id": "blackbox-068",
    "title": "星雾深处 · 8",
    "chapter": 5,
    "size": 5,
    "atoms": [
      1,
      2,
      10,
      23
    ]
  },
  {
    "id": "blackbox-069",
    "title": "星雾深处 · 9",
    "chapter": 5,
    "size": 5,
    "atoms": [
      0,
      1,
      12,
      15
    ]
  },
  {
    "id": "blackbox-070",
    "title": "星雾深处 · 10",
    "chapter": 5,
    "size": 5,
    "atoms": [
      1,
      10,
      11,
      16
    ]
  },
  {
    "id": "blackbox-071",
    "title": "星雾深处 · 11",
    "chapter": 5,
    "size": 5,
    "atoms": [
      2,
      7,
      11,
      12
    ]
  },
  {
    "id": "blackbox-072",
    "title": "星雾深处 · 12",
    "chapter": 5,
    "size": 5,
    "atoms": [
      6,
      7,
      11,
      12
    ]
  },
  {
    "id": "blackbox-073",
    "title": "星雾深处 · 13",
    "chapter": 5,
    "size": 5,
    "atoms": [
      0,
      3,
      9,
      17
    ]
  },
  {
    "id": "blackbox-074",
    "title": "星雾深处 · 14",
    "chapter": 5,
    "size": 5,
    "atoms": [
      0,
      6,
      12,
      18
    ]
  },
  {
    "id": "blackbox-075",
    "title": "星雾深处 · 15",
    "chapter": 5,
    "size": 5,
    "atoms": [
      0,
      4,
      11,
      16
    ]
  },
  {
    "id": "blackbox-076",
    "title": "星雾深处 · 16",
    "chapter": 5,
    "size": 5,
    "atoms": [
      0,
      1,
      16,
      17
    ]
  },
  {
    "id": "blackbox-077",
    "title": "星雾深处 · 17",
    "chapter": 5,
    "size": 5,
    "atoms": [
      0,
      1,
      19,
      22
    ]
  },
  {
    "id": "blackbox-078",
    "title": "星雾深处 · 18",
    "chapter": 5,
    "size": 5,
    "atoms": [
      0,
      1,
      7,
      16
    ]
  },
  {
    "id": "blackbox-079",
    "title": "星雾深处 · 19",
    "chapter": 5,
    "size": 5,
    "atoms": [
      1,
      6,
      7,
      15
    ]
  },
  {
    "id": "blackbox-080",
    "title": "星雾深处 · 20",
    "chapter": 5,
    "size": 5,
    "atoms": [
      1,
      2,
      9,
      16
    ]
  },
  {
    "id": "blackbox-081",
    "title": "星雾深处 · 21",
    "chapter": 5,
    "size": 5,
    "atoms": [
      0,
      7,
      8,
      11
    ]
  },
  {
    "id": "blackbox-082",
    "title": "星雾深处 · 22",
    "chapter": 5,
    "size": 5,
    "atoms": [
      0,
      12,
      13,
      14
    ]
  },
  {
    "id": "blackbox-083",
    "title": "星雾深处 · 23",
    "chapter": 5,
    "size": 5,
    "atoms": [
      0,
      2,
      4,
      16
    ]
  },
  {
    "id": "blackbox-084",
    "title": "星雾深处 · 24",
    "chapter": 5,
    "size": 5,
    "atoms": [
      0,
      2,
      16,
      24
    ]
  }
];
