// SPDX-License-Identifier: GPL-3.0-only
// Twelve original, hand-authored maps. Certificates independently enumerated offline.
import type { BudgetTownLevel } from "./budgetTownLogic";
export const budgetTownLevels: BudgetTownLevel[] = [
  {
    title: "两端的小屋",
    width: 5,
    height: 3,
    budget: 3,
    homes: [
      {
        id: "H1",
        x: 0,
        y: 1,
        needs: ["g"],
      },
      {
        id: "H2",
        x: 4,
        y: 1,
        needs: ["g"],
      },
    ],
    proposals: [
      {
        id: "A",
        x: 0,
        y: 0,
        kind: "g",
      },
      {
        id: "B",
        x: 2,
        y: 0,
        kind: "G",
      },
      {
        id: "C",
        x: 4,
        y: 0,
        kind: "g",
      },
      {
        id: "D",
        x: 2,
        y: 1,
        kind: "g",
      },
    ],
    lesson: "先试一个共享设施。距离相加不超过半径，才算覆盖。",
    discovery: "居中的花园让两个住区共享一笔支出；更大的半径不一定值得多花币。",
    certificate: {
      built: ["D"],
      cost: 3,
      minimumCost: 3,
      optimalPlans: 1,
    },
  },
  {
    title: "两条短街",
    width: 5,
    height: 4,
    budget: 6,
    homes: [
      {
        id: "H1",
        x: 0,
        y: 0,
        needs: ["g"],
      },
      {
        id: "H2",
        x: 0,
        y: 3,
        needs: ["g"],
      },
      {
        id: "H3",
        x: 4,
        y: 0,
        needs: ["g"],
      },
      {
        id: "H4",
        x: 4,
        y: 3,
        needs: ["g"],
      },
    ],
    proposals: [
      {
        id: "A",
        x: 0,
        y: 1,
        kind: "g",
      },
      {
        id: "B",
        x: 2,
        y: 1,
        kind: "G",
      },
      {
        id: "C",
        x: 4,
        y: 1,
        kind: "g",
      },
      {
        id: "D",
        x: 0,
        y: 2,
        kind: "g",
      },
      {
        id: "E",
        x: 2,
        y: 2,
        kind: "G",
      },
      {
        id: "F",
        x: 4,
        y: 2,
        kind: "g",
      },
    ],
    lesson: "同一条街可能有多个好位置。寻找能一处照顾两端的地块。",
    discovery: "左右两侧各有不止一个有效位置。不同布局也能达到相同预算。",
    certificate: {
      built: ["A", "C"],
      cost: 6,
      minimumCost: 6,
      optimalPlans: 4,
    },
  },
  {
    title: "花园里读书",
    width: 5,
    height: 4,
    budget: 5,
    homes: [
      {
        id: "H1",
        x: 0,
        y: 1,
        needs: ["g", "r"],
      },
      {
        id: "H2",
        x: 4,
        y: 1,
        needs: ["g", "r"],
      },
    ],
    proposals: [
      {
        id: "A",
        x: 0,
        y: 0,
        kind: "r",
      },
      {
        id: "B",
        x: 2,
        y: 0,
        kind: "G",
      },
      {
        id: "C",
        x: 4,
        y: 0,
        kind: "g",
      },
      {
        id: "D",
        x: 1,
        y: 1,
        kind: "g",
      },
      {
        id: "E",
        x: 2,
        y: 1,
        kind: "gr",
      },
      {
        id: "F",
        x: 3,
        y: 1,
        kind: "r",
      },
      {
        id: "G",
        x: 2,
        y: 2,
        kind: "R",
      },
    ],
    lesson: "住区出现两项需求。比较双服务设施与单服务设施的总花费。",
    discovery:
      "一次覆盖两项服务可能比两座单服务设施便宜，但前提是两项都用得上。",
    certificate: {
      built: ["E"],
      cost: 5,
      minimumCost: 5,
      optimalPlans: 1,
    },
  },
  {
    title: "街角与支路",
    width: 6,
    height: 4,
    budget: 15,
    homes: [
      {
        id: "H1",
        x: 0,
        y: 0,
        needs: ["g", "r"],
      },
      {
        id: "H2",
        x: 0,
        y: 3,
        needs: ["g", "r"],
      },
      {
        id: "H3",
        x: 5,
        y: 0,
        needs: ["g", "r"],
      },
      {
        id: "H4",
        x: 5,
        y: 3,
        needs: ["g", "r"],
      },
      {
        id: "H5",
        x: 3,
        y: 3,
        needs: ["g", "r"],
      },
    ],
    proposals: [
      {
        id: "A",
        x: 0,
        y: 1,
        kind: "gr",
      },
      {
        id: "B",
        x: 3,
        y: 1,
        kind: "R",
      },
      {
        id: "C",
        x: 5,
        y: 1,
        kind: "gr",
      },
      {
        id: "D",
        x: 0,
        y: 2,
        kind: "gr",
      },
      {
        id: "E",
        x: 2,
        y: 2,
        kind: "G",
      },
      {
        id: "F",
        x: 3,
        y: 2,
        kind: "gr",
      },
      {
        id: "G",
        x: 5,
        y: 2,
        kind: "gr",
      },
      {
        id: "H",
        x: 2,
        y: 3,
        kind: "gr",
      },
    ],
    lesson: "新住区改变了覆盖边界。别把看起来相邻误当成半径以内。",
    discovery:
      "先查看最难到达的服务，再考虑共享覆盖，可以避免只照顾显眼的角落。",
    certificate: {
      built: ["A", "C", "F"],
      cost: 15,
      minimumCost: 15,
      optimalPlans: 8,
    },
  },
  {
    title: "水边新街区",
    width: 7,
    height: 5,
    budget: 15,
    homes: [
      {
        id: "H1",
        x: 0,
        y: 0,
        needs: ["g", "w"],
      },
      {
        id: "H2",
        x: 0,
        y: 4,
        needs: ["g"],
      },
      {
        id: "H3",
        x: 6,
        y: 0,
        needs: ["w"],
      },
      {
        id: "H4",
        x: 6,
        y: 4,
        needs: ["g", "w"],
      },
      {
        id: "H5",
        x: 3,
        y: 2,
        needs: ["g", "w"],
      },
    ],
    proposals: [
      {
        id: "A",
        x: 1,
        y: 0,
        kind: "w",
      },
      {
        id: "B",
        x: 2,
        y: 1,
        kind: "gw",
      },
      {
        id: "C",
        x: 4,
        y: 1,
        kind: "W",
      },
      {
        id: "D",
        x: 5,
        y: 1,
        kind: "w",
      },
      {
        id: "E",
        x: 0,
        y: 2,
        kind: "gw",
      },
      {
        id: "F",
        x: 6,
        y: 2,
        kind: "gw",
      },
      {
        id: "G",
        x: 1,
        y: 3,
        kind: "g",
      },
      {
        id: "H",
        x: 2,
        y: 3,
        kind: "G",
      },
      {
        id: "I",
        x: 4,
        y: 3,
        kind: "gw",
      },
      {
        id: "J",
        x: 5,
        y: 4,
        kind: "g",
      },
    ],
    lesson: "绿地和供水要分别核对。半径更大的设施只提供标注的服务。",
    discovery:
      "覆盖远处不等于服务齐全。看清服务种类与距离，才能组合互补的设施。",
    certificate: {
      built: ["B", "E", "F"],
      cost: 15,
      minimumCost: 15,
      optimalPlans: 2,
    },
  },
  {
    title: "三色服务单",
    width: 7,
    height: 5,
    budget: 21,
    homes: [
      {
        id: "H1",
        x: 0,
        y: 0,
        needs: ["g", "r"],
      },
      {
        id: "H2",
        x: 0,
        y: 4,
        needs: ["g", "w"],
      },
      {
        id: "H3",
        x: 6,
        y: 0,
        needs: ["r", "w"],
      },
      {
        id: "H4",
        x: 6,
        y: 4,
        needs: ["g", "r"],
      },
      {
        id: "H5",
        x: 3,
        y: 2,
        needs: ["g", "r", "w"],
      },
    ],
    proposals: [
      {
        id: "A",
        x: 1,
        y: 0,
        kind: "gr",
      },
      {
        id: "B",
        x: 5,
        y: 0,
        kind: "rw",
      },
      {
        id: "C",
        x: 2,
        y: 1,
        kind: "all",
      },
      {
        id: "D",
        x: 4,
        y: 1,
        kind: "R",
      },
      {
        id: "E",
        x: 0,
        y: 2,
        kind: "all",
      },
      {
        id: "F",
        x: 4,
        y: 2,
        kind: "W",
      },
      {
        id: "G",
        x: 6,
        y: 2,
        kind: "all",
      },
      {
        id: "H",
        x: 2,
        y: 3,
        kind: "G",
      },
      {
        id: "I",
        x: 4,
        y: 3,
        kind: "all",
      },
      {
        id: "J",
        x: 1,
        y: 4,
        kind: "gw",
      },
      {
        id: "K",
        x: 5,
        y: 4,
        kind: "gr",
      },
    ],
    lesson: "每个住区的需求不同。共享站提供三种服务，也花更多游戏币。",
    discovery: "多服务设施省不省预算取决于实际被使用的服务，不能只看图标数量。",
    certificate: {
      built: ["C", "E", "G"],
      cost: 21,
      minimumCost: 21,
      optimalPlans: 2,
    },
  },
  {
    title: "中央留白",
    width: 7,
    height: 5,
    budget: 21,
    homes: [
      {
        id: "H1",
        x: 0,
        y: 0,
        needs: ["g", "r"],
      },
      {
        id: "H2",
        x: 0,
        y: 4,
        needs: ["r", "w"],
      },
      {
        id: "H3",
        x: 6,
        y: 0,
        needs: ["g", "w"],
      },
      {
        id: "H4",
        x: 6,
        y: 4,
        needs: ["g", "r"],
      },
      {
        id: "H5",
        x: 3,
        y: 2,
        needs: ["g", "r", "w"],
      },
    ],
    proposals: [
      {
        id: "A",
        x: 1,
        y: 0,
        kind: "gr",
      },
      {
        id: "B",
        x: 3,
        y: 0,
        kind: "W",
      },
      {
        id: "C",
        x: 5,
        y: 0,
        kind: "gw",
      },
      {
        id: "D",
        x: 3,
        y: 1,
        kind: "all",
      },
      {
        id: "E",
        x: 0,
        y: 2,
        kind: "all",
      },
      {
        id: "F",
        x: 2,
        y: 2,
        kind: "G",
      },
      {
        id: "G",
        x: 4,
        y: 2,
        kind: "R",
      },
      {
        id: "H",
        x: 6,
        y: 2,
        kind: "all",
      },
      {
        id: "I",
        x: 3,
        y: 3,
        kind: "all",
      },
      {
        id: "J",
        x: 1,
        y: 4,
        kind: "rw",
      },
      {
        id: "K",
        x: 3,
        y: 4,
        kind: "w",
      },
      {
        id: "L",
        x: 5,
        y: 4,
        kind: "gr",
      },
    ],
    lesson: "边缘住区与中央住区需要一起考虑，重复覆盖不会额外加分。",
    discovery: "重复覆盖是允许的，但它不抵消遗漏。预算应花在完整覆盖的组合上。",
    certificate: {
      built: ["D", "E", "H"],
      cost: 21,
      minimumCost: 21,
      optimalPlans: 2,
    },
  },
  {
    title: "错开的街角",
    width: 7,
    height: 5,
    budget: 29,
    homes: [
      {
        id: "H1",
        x: 0,
        y: 1,
        needs: ["g", "r", "w"],
      },
      {
        id: "H2",
        x: 1,
        y: 4,
        needs: ["g", "r"],
      },
      {
        id: "H3",
        x: 3,
        y: 0,
        needs: ["r", "w"],
      },
      {
        id: "H4",
        x: 3,
        y: 3,
        needs: ["g", "w"],
      },
      {
        id: "H5",
        x: 6,
        y: 1,
        needs: ["g", "r", "w"],
      },
      {
        id: "H6",
        x: 6,
        y: 4,
        needs: ["r", "w"],
      },
    ],
    proposals: [
      {
        id: "A",
        x: 2,
        y: 0,
        kind: "rw",
      },
      {
        id: "B",
        x: 4,
        y: 0,
        kind: "rw",
      },
      {
        id: "C",
        x: 1,
        y: 1,
        kind: "all",
      },
      {
        id: "D",
        x: 5,
        y: 1,
        kind: "all",
      },
      {
        id: "E",
        x: 2,
        y: 2,
        kind: "R",
      },
      {
        id: "F",
        x: 3,
        y: 2,
        kind: "all",
      },
      {
        id: "G",
        x: 4,
        y: 2,
        kind: "g",
      },
      {
        id: "H",
        x: 0,
        y: 3,
        kind: "G",
      },
      {
        id: "I",
        x: 1,
        y: 3,
        kind: "gr",
      },
      {
        id: "J",
        x: 5,
        y: 3,
        kind: "rw",
      },
      {
        id: "K",
        x: 6,
        y: 3,
        kind: "W",
      },
      {
        id: "L",
        x: 3,
        y: 4,
        kind: "gw",
      },
      {
        id: "M",
        x: 4,
        y: 4,
        kind: "w",
      },
    ],
    lesson: "地图不再对称。试着找出哪项需求只有少数设施够得着。",
    discovery:
      "从稀缺覆盖入手，再用共享部分连接两侧，比总选覆盖数量最多的设施可靠。",
    certificate: {
      built: ["A", "C", "D", "I", "J"],
      cost: 29,
      minimumCost: 29,
      optimalPlans: 2,
    },
  },
  {
    title: "长街的两端",
    width: 7,
    height: 6,
    budget: 24,
    homes: [
      {
        id: "H1",
        x: 0,
        y: 0,
        needs: ["g", "r"],
      },
      {
        id: "H2",
        x: 0,
        y: 5,
        needs: ["g", "w"],
      },
      {
        id: "H3",
        x: 6,
        y: 0,
        needs: ["g", "w"],
      },
      {
        id: "H4",
        x: 6,
        y: 5,
        needs: ["r", "w"],
      },
      {
        id: "H5",
        x: 2,
        y: 2,
        needs: ["r", "w"],
      },
      {
        id: "H6",
        x: 4,
        y: 3,
        needs: ["g", "r"],
      },
    ],
    proposals: [
      {
        id: "A",
        x: 1,
        y: 0,
        kind: "gr",
      },
      {
        id: "B",
        x: 5,
        y: 0,
        kind: "gw",
      },
      {
        id: "C",
        x: 2,
        y: 1,
        kind: "rw",
      },
      {
        id: "D",
        x: 0,
        y: 2,
        kind: "all",
      },
      {
        id: "E",
        x: 3,
        y: 2,
        kind: "R",
      },
      {
        id: "F",
        x: 6,
        y: 2,
        kind: "all",
      },
      {
        id: "G",
        x: 0,
        y: 3,
        kind: "all",
      },
      {
        id: "H",
        x: 3,
        y: 3,
        kind: "G",
      },
      {
        id: "I",
        x: 6,
        y: 3,
        kind: "all",
      },
      {
        id: "J",
        x: 2,
        y: 4,
        kind: "W",
      },
      {
        id: "K",
        x: 4,
        y: 4,
        kind: "gr",
      },
      {
        id: "L",
        x: 1,
        y: 5,
        kind: "gw",
      },
      {
        id: "M",
        x: 5,
        y: 5,
        kind: "rw",
      },
    ],
    lesson: "便宜的小设施也可能完成关键一环。比较整组的价格，而非单座大小。",
    discovery: "紧凑设施与广范围设施可以互补。最便宜的完整组合不一定长得对称。",
    certificate: {
      built: ["B", "D", "I", "L"],
      cost: 24,
      minimumCost: 24,
      optimalPlans: 1,
    },
  },
  {
    title: "重叠的选择",
    width: 7,
    height: 6,
    budget: 29,
    homes: [
      {
        id: "H1",
        x: 0,
        y: 0,
        needs: ["g", "r", "w"],
      },
      {
        id: "H2",
        x: 0,
        y: 5,
        needs: ["g", "r"],
      },
      {
        id: "H3",
        x: 6,
        y: 0,
        needs: ["r", "w"],
      },
      {
        id: "H4",
        x: 6,
        y: 5,
        needs: ["g", "r", "w"],
      },
      {
        id: "H5",
        x: 2,
        y: 2,
        needs: ["g", "w"],
      },
      {
        id: "H6",
        x: 4,
        y: 3,
        needs: ["r", "w"],
      },
      {
        id: "H7",
        x: 3,
        y: 5,
        needs: ["g"],
      },
    ],
    proposals: [
      {
        id: "A",
        x: 1,
        y: 0,
        kind: "all",
      },
      {
        id: "B",
        x: 2,
        y: 1,
        kind: "gw",
      },
      {
        id: "C",
        x: 4,
        y: 1,
        kind: "W",
      },
      {
        id: "D",
        x: 5,
        y: 1,
        kind: "rw",
      },
      {
        id: "E",
        x: 0,
        y: 2,
        kind: "all",
      },
      {
        id: "F",
        x: 1,
        y: 2,
        kind: "R",
      },
      {
        id: "G",
        x: 3,
        y: 2,
        kind: "all",
      },
      {
        id: "H",
        x: 3,
        y: 3,
        kind: "all",
      },
      {
        id: "I",
        x: 5,
        y: 3,
        kind: "R",
      },
      {
        id: "J",
        x: 6,
        y: 3,
        kind: "all",
      },
      {
        id: "K",
        x: 1,
        y: 4,
        kind: "gr",
      },
      {
        id: "L",
        x: 2,
        y: 4,
        kind: "G",
      },
      {
        id: "M",
        x: 4,
        y: 4,
        kind: "rw",
      },
      {
        id: "N",
        x: 5,
        y: 5,
        kind: "all",
      },
    ],
    lesson: "一个位置的改动可能让另一座设施变得多余。随时查看每个住区的明细。",
    discovery: "当预算刚好时，替换需要连着思考：撤下一座，再补上它独有的服务。",
    certificate: {
      built: ["D", "E", "J", "K", "L"],
      cost: 29,
      minimumCost: 29,
      optimalPlans: 2,
    },
  },
  {
    title: "八个住区",
    width: 7,
    height: 6,
    budget: 31,
    homes: [
      {
        id: "H1",
        x: 0,
        y: 0,
        needs: ["g", "r"],
      },
      {
        id: "H2",
        x: 0,
        y: 3,
        needs: ["r", "w"],
      },
      {
        id: "H3",
        x: 1,
        y: 5,
        needs: ["g", "w"],
      },
      {
        id: "H4",
        x: 3,
        y: 0,
        needs: ["g", "w"],
      },
      {
        id: "H5",
        x: 3,
        y: 3,
        needs: ["g", "r", "w"],
      },
      {
        id: "H6",
        x: 6,
        y: 0,
        needs: ["r", "w"],
      },
      {
        id: "H7",
        x: 6,
        y: 3,
        needs: ["g", "r"],
      },
      {
        id: "H8",
        x: 5,
        y: 5,
        needs: ["g", "r", "w"],
      },
    ],
    proposals: [
      {
        id: "A",
        x: 2,
        y: 0,
        kind: "gw",
      },
      {
        id: "B",
        x: 0,
        y: 1,
        kind: "gr",
      },
      {
        id: "C",
        x: 1,
        y: 1,
        kind: "all",
      },
      {
        id: "D",
        x: 5,
        y: 1,
        kind: "all",
      },
      {
        id: "E",
        x: 6,
        y: 1,
        kind: "rw",
      },
      {
        id: "F",
        x: 3,
        y: 2,
        kind: "all",
      },
      {
        id: "G",
        x: 2,
        y: 3,
        kind: "W",
      },
      {
        id: "H",
        x: 4,
        y: 3,
        kind: "R",
      },
      {
        id: "I",
        x: 0,
        y: 4,
        kind: "rw",
      },
      {
        id: "J",
        x: 1,
        y: 4,
        kind: "all",
      },
      {
        id: "K",
        x: 3,
        y: 4,
        kind: "all",
      },
      {
        id: "L",
        x: 5,
        y: 4,
        kind: "all",
      },
      {
        id: "M",
        x: 6,
        y: 4,
        kind: "gr",
      },
      {
        id: "N",
        x: 2,
        y: 5,
        kind: "gw",
      },
      {
        id: "O",
        x: 4,
        y: 5,
        kind: "all",
      },
    ],
    lesson: "逐项核对八张服务单。花在已经满足的服务上的钱不能填补别处的空缺。",
    discovery:
      "整体规划把空间与服务类型同时考虑；局部很划算的选择也可能挤掉关键设施。",
    certificate: {
      built: ["B", "E", "F", "J", "L"],
      cost: 31,
      minimumCost: 31,
      optimalPlans: 1,
    },
  },
  {
    title: "小镇规划师",
    width: 7,
    height: 6,
    budget: 38,
    homes: [
      {
        id: "H1",
        x: 0,
        y: 0,
        needs: ["g", "r", "w"],
      },
      {
        id: "H2",
        x: 0,
        y: 5,
        needs: ["g", "r", "w"],
      },
      {
        id: "H3",
        x: 6,
        y: 0,
        needs: ["g", "r", "w"],
      },
      {
        id: "H4",
        x: 6,
        y: 5,
        needs: ["g", "r", "w"],
      },
      {
        id: "H5",
        x: 2,
        y: 2,
        needs: ["g", "w"],
      },
      {
        id: "H6",
        x: 4,
        y: 3,
        needs: ["g", "r"],
      },
      {
        id: "H7",
        x: 3,
        y: 0,
        needs: ["r", "w"],
      },
      {
        id: "H8",
        x: 3,
        y: 5,
        needs: ["r", "w"],
      },
    ],
    proposals: [
      {
        id: "A",
        x: 2,
        y: 0,
        kind: "rw",
      },
      {
        id: "B",
        x: 4,
        y: 0,
        kind: "rw",
      },
      {
        id: "C",
        x: 1,
        y: 1,
        kind: "all",
      },
      {
        id: "D",
        x: 3,
        y: 1,
        kind: "R",
      },
      {
        id: "E",
        x: 5,
        y: 1,
        kind: "all",
      },
      {
        id: "F",
        x: 0,
        y: 2,
        kind: "all",
      },
      {
        id: "G",
        x: 3,
        y: 2,
        kind: "all",
      },
      {
        id: "H",
        x: 4,
        y: 2,
        kind: "W",
      },
      {
        id: "I",
        x: 2,
        y: 3,
        kind: "G",
      },
      {
        id: "J",
        x: 3,
        y: 3,
        kind: "all",
      },
      {
        id: "K",
        x: 6,
        y: 3,
        kind: "all",
      },
      {
        id: "L",
        x: 1,
        y: 4,
        kind: "all",
      },
      {
        id: "M",
        x: 5,
        y: 4,
        kind: "all",
      },
      {
        id: "N",
        x: 2,
        y: 5,
        kind: "rw",
      },
      {
        id: "O",
        x: 4,
        y: 5,
        kind: "rw",
      },
    ],
    lesson: "把距离、服务组合与有限预算合在一起。所有合法的完整方案都会通过。",
    discovery:
      "完整覆盖是共同目标，但布局可以不同。你已经在比较一整组设施的机会与代价。",
    certificate: {
      built: ["A", "C", "E", "K", "L", "N"],
      cost: 38,
      minimumCost: 38,
      optimalPlans: 16,
    },
  },
];
