// SPDX-License-Identifier: GPL-3.0-only
import {useEffect,useRef,useState} from "react";
import type {GameProps} from "../lib/types";
import {advanceCloudHop,cloudHopLevels,initialCloudHop} from "./cloudHopLogic";
import type {HopState} from "./cloudHopLogic";
import "./cloudHop.css";
export default function CloudHop(props:GameProps){return <Round key={`${props.level}:${props.resetToken}`} {...props}/>;}
function Round({level,paused,hintToken,undoToken,onStatus,onComplete}:GameProps){
 const config=cloudHopLevels[level]??cloudHopLevels[0], [state,setState]=useState(initialCloudHop),[message,setMessage]=useState("按“开始跳跃”，在空中左右调整落点。");const live=useRef(state),input=useRef({key:0,pointer:0,pulse:0,until:0}),frame=useRef(0),seenHint=useRef(hintToken),seenUndo=useRef(undoToken),done=useRef(false);const locked=paused||state.status==="lost"||state.status==="won",bottom=Math.max(-30,state.highest-340),toY=(y:number)=>450-(y-bottom);
 function save(s:HopState){live.current=s;setState(s);}function clear(){input.current={key:0,pointer:0,pulse:0,until:0};}
 useEffect(()=>{onStatus("自动从实际落到的云面弹起；方向键或触屏左右控制落点。登上最高旗帜云才通关。");return ()=>{clear();cancelAnimationFrame(frame.current);};},[]);
 useEffect(()=>{clear();if(paused||state.status!=="playing")return;let last=0;const tick=(now:number)=>{if(last){const controls=input.current,dir=controls.key||controls.pointer||(now<controls.until?controls.pulse:0);save(advanceCloudHop(config,live.current,dir,Math.min((now-last)/1000,.034)));}last=now;if(live.current.status==="playing")frame.current=requestAnimationFrame(tick);};frame.current=requestAnimationFrame(tick);return ()=>{cancelAnimationFrame(frame.current);clear();};},[paused,state.status,config]);
 useEffect(()=>{if(seenHint.current===hintToken)return;seenHint.current=hintToken;if(locked)return;const p=Math.min(state.landed+1,config.platforms.length-1),ledge=config.platforms[p];const text=state.status==="idle"?"先开始跳跃。每次落到云面都会自动再次起跳。":`下一朵目标是 ${p} 号云，中心横坐标 ${ledge.x}，比上次落点高 ${ledge.y-config.platforms[state.landed].y}。${Math.abs(state.x-ledge.x)<18?"已接近中心，停止横移等待下落。":state.x<ledge.x?"向右调整。":"向左调整。"} 这是当前落点建议，不会替你跳跃。`;setMessage(text);onStatus(text);},[hintToken,locked,state,config,onStatus]);
 useEffect(()=>{if(seenUndo.current===undoToken)return;seenUndo.current=undoToken;if(!locked)onStatus("实时弹跳没有撤销；按重来可从地面重新开始。");},[undoToken,locked,onStatus]);
 useEffect(()=>{if(state.status==="won"&&!paused&&!done.current){done.current=true;clear();onStatus("稳稳落在山顶旗帜云上！");onComplete();}else if(state.status==="lost")onStatus("落到镜头下方了，请重来，再找准云面。");},[state.status,paused,onStatus,onComplete]);
 function pulse(dir:number){if(locked||state.status!=="playing")return;input.current.pulse=dir;input.current.until=performance.now()+220;}function start(){if(locked||state.status!=="idle")return;save({...state,vy:440,status:"playing"});setMessage("先瞄准下一朵更高的云。轻点方向短移，按住可持续移动。");}
 return <div className="puzzle-layout chp-game" data-chp-state={JSON.stringify(state)} data-chp-won={state.status==="won"}>
 <section className="chp-workbench"><header><span className="mini-label">云朵弹跳 · {config.title}</span><b>落点 {state.landed}/{config.platforms.length-1}</b></header><div className="chp-stage" tabIndex={locked?-1:0} role="group" aria-label="云梯画面，左右方向键控制，空格开始或停止横移" onBlur={clear} onKeyDown={e=>{if(e.ctrlKey||e.metaKey||e.altKey||locked)return;if(["ArrowLeft","ArrowRight"," "].includes(e.key)){e.preventDefault();if(e.key===" "){if(state.status==="idle")start();else clear();}else if(state.status==="playing")input.current.key=e.key==="ArrowLeft"?-1:1;}}} onKeyUp={e=>{if(e.key==="ArrowLeft"||e.key==="ArrowRight")input.current.key=0;}}>
 <svg viewBox="0 0 360 480" role="img" aria-label={`小鸟横坐标 ${Math.round(state.x)}，高度 ${Math.round(state.y)}。下一朵云 ${state.landed+1}。`}><defs><linearGradient id={`chp-sky-${level}`} x2="0" y2="1"><stop stopColor="#b3dcec"/><stop offset="1" stopColor="#f7f2db"/></linearGradient></defs><rect width="360" height="480" fill={`url(#chp-sky-${level})`}/><g opacity=".42" fill="#fff">{[0,1,2,3,4].map(i=><ellipse key={i} cx={i%2?280:55} cy={(i*125+state.highest*.15)%520} rx={40+i*3} ry="13"/>)}</g>
 {config.platforms.map((p,i)=>{const y=toY(p.y);return <g key={i} data-chp-platform={i} data-chp-x={p.x} data-chp-y={p.y} data-chp-width={p.width} opacity={y<-35||y>515?0:1}><path d={`M${p.x-p.width/2} ${y} Q${p.x-p.width/2-7} ${y+16} ${p.x-p.width/2+16} ${y+18} H${p.x+p.width/2-16} Q${p.x+p.width/2+7} ${y+16} ${p.x+p.width/2} ${y} Z`} fill={i===config.platforms.length-1?"#edc56c":"#fff"} stroke="#7cabb7" strokeWidth="2"/><text x={p.x} y={y+13} textAnchor="middle" fontSize="11" fill="#36606d">{i===0?"起点":`${i} 号云`}</text>{i===config.platforms.length-1?<g transform={`translate(${p.x},${y})`}><path d="M0 0V-49L30-39 0-28" fill="#cd765c" stroke="#875838" strokeWidth="3"/></g>:null}</g>;})}
 <g transform={`translate(${state.x},${toY(state.y)})`}><ellipse rx="11" ry="12" fill="#f8ca65" stroke="#967b35" strokeWidth="2"/><path d="M8-3l9 4-9 4" fill="#cb7745"/><circle cx="4" cy="-4" r="2" fill="#384b50"/><path d="M-8 1q-10-9-12 1" fill="#fff0b0" stroke="#967b35"/></g>
 {paused?<g><rect width="360" height="480" fill="#fff" opacity=".65"/><text x="180" y="240" textAnchor="middle" fill="#315b70" fontSize="26">已暂停</text></g>:null}</svg></div>
 <div className="chp-controls"><button data-chp-left disabled={locked||state.status!=="playing"} onPointerDown={e=>{if(locked)return;e.preventDefault();input.current.pointer=-1;e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={()=>{input.current.pointer=0;}} onPointerCancel={clear} onLostPointerCapture={()=>{input.current.pointer=0;input.current.pulse=0;input.current.until=0;}} onClick={()=>pulse(-1)} aria-label="向左飞">← 左移</button><button disabled={locked} onClick={()=>state.status==="idle"?start():clear()} aria-label={state.status==="idle"?"开始跳跃":"停止横移"}>{state.status==="idle"?"开始跳跃":"停止横移"}</button><button data-chp-right disabled={locked||state.status!=="playing"} onPointerDown={e=>{if(locked)return;e.preventDefault();input.current.pointer=1;e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={()=>{input.current.pointer=0;}} onPointerCancel={clear} onLostPointerCapture={()=>{input.current.pointer=0;input.current.pulse=0;input.current.until=0;}} onClick={()=>pulse(1)} aria-label="向右飞">右移 →</button></div><p className="chp-feedback" role="status">{paused?"已暂停，松开方向后再继续。":state.status==="won"?"到达云海之巅！":state.status==="lost"?"这次掉下云海了，请重来。":message}</p></section>
 <aside className="game-notes"><span className="mini-label">重力 · 平台落点 · 横向控制</span><h3>一朵一朵，跳上云端。</h3><p>{config.lesson}</p><ol><li>开始后，小鸟受重力影响。只有向下落到云面才会弹起。</li><li>左右移动瞄准更高的平台。轻点短移，长按持续飞；停止键松开方向并减速。</li><li>镜头随最高到达位置上移。跌到镜头下方会失败，必须真实落到最高旗帜云才通关。</li></ol><p>这是有限的竖向平台课程，没有跑道切换或自动通关。八关的平台位置、宽度和高度间距不同。实时运动不支持撤销，重来可立即回到起点。</p><p>键盘：聚焦画面后用 ← / →，空格开始或停止横移。切换焦点和暂停都会清除按住状态。</p></aside></div>;
}
