// SPDX-License-Identifier: MIT
import type { CompressionLevel, PostPacket } from "./compressionPostLogic";
// Original public messages/dictionaries. Certificates are separate audit fixtures only.
const level = (
  title: string,
  lesson: string,
  message: string,
  budget: number,
  runs: boolean,
  dictionary: string[],
  certificate: PostPacket[],
): CompressionLevel => ({
  title,
  lesson,
  message,
  budget,
  runs,
  dictionary,
  maxLiteral: 6,
  maxRun: 9,
  certificate,
});
export const compressionPostLevels: CompressionLevel[] = [
  level(
    "信封也占空间",
    "每个原文包都要付 1 单位包头。连续短符号合成一包，就能少付包头。",
    "ABC",
    4,
    false,
    [],
    [{ kind: "literal", text: "ABC" }],
  ),
  level(
    "六次铃声",
    "连写包记录类型、符号和次数，固定 3 单位。长连写能节约空间。",
    "AAAAAA",
    3,
    true,
    [],
    [{ kind: "run", symbol: "A", count: 6 }],
  ),
  level(
    "夹心短连写",
    "看到重复不一定要拆包。拆出中间的 BBB，会让两边多付包头。",
    "ABBBC",
    6,
    true,
    [],
    [{ kind: "literal", text: "ABBBC" }],
  ),
  level(
    "在边界换包装",
    "长连写和短尾巴可以采用不同包装。不要让每个符号都单独付包头。",
    "AAAAABC",
    6,
    true,
    [],
    [
      { kind: "run", symbol: "A", count: 5 },
      { kind: "literal", text: "BC" },
    ],
  ),
  level(
    "两侧小纸条",
    "连写节省的空间，要抵得过两侧新产生的包头。把左右短纸条各自合并。",
    "ABCCCCDE",
    9,
    true,
    [],
    [
      { kind: "literal", text: "AB" },
      { kind: "run", symbol: "C", count: 4 },
      { kind: "literal", text: "DE" },
    ],
  ),
  level(
    "小重复的陷阱",
    "每一对相同符号都可连写，但四个连写包不够省。原文包最长只有六符号。",
    "AABBAABB",
    10,
    true,
    [],
    [
      { kind: "literal", text: "AA" },
      { kind: "literal", text: "BBAABB" },
    ],
  ),
  level(
    "约好的短语",
    "收件人已持有公开词典。引用只需类型和编号，共 2 单位，不必再次发送短语。",
    "ABCABCABC",
    6,
    true,
    ["ABC"],
    [
      { kind: "dict", index: 0 },
      { kind: "dict", index: 0 },
      { kind: "dict", index: 0 },
    ],
  ),
  level(
    "短语长一点",
    "同一个位置可能匹配多个词典短语。观察剩余消息，选择让下一包也能复用的边界。",
    "ABCABCD",
    4,
    true,
    ["ABC", "ABCD"],
    [
      { kind: "dict", index: 0 },
      { kind: "dict", index: 1 },
    ],
  ),
  level(
    "重叠的地址",
    "长连写看着诱人，但短语可以跨过连写边缘。为后面的词典匹配保留一个符号。",
    "AAAABCAAAABC",
    8,
    true,
    ["AAAB", "CAAA", "ABC"],
    [
      { kind: "literal", text: "A" },
      { kind: "dict", index: 0 },
      { kind: "dict", index: 1 },
      { kind: "dict", index: 2 },
    ],
  ),
  level(
    "三种包协作",
    "词典覆盖边框，连写覆盖中央。并不是每个可匹配的词典项都值得立即选择。",
    "ABABAAAAABAB",
    7,
    true,
    ["ABAB", "ABAA", "AAA"],
    [
      { kind: "dict", index: 0 },
      { kind: "run", symbol: "A", count: 4 },
      { kind: "dict", index: 0 },
    ],
  ),
  level(
    "别被前缀带走",
    "即使短语 ABC 在当前位置匹配，发出它也可能让下一段更贵。先查看整段的分界。",
    "ABCDABCEABCD",
    8,
    true,
    ["ABC", "ABCD", "BCE"],
    [
      { kind: "dict", index: 1 },
      { kind: "literal", text: "A" },
      { kind: "dict", index: 2 },
      { kind: "dict", index: 1 },
    ],
  ),
  level(
    "无损邮政专家",
    "最长连写会吞掉下一条短语的开头。把包长、词典重叠和原文包头一起考虑。",
    "AAAAAABCABCDABCAAAAAA",
    12,
    true,
    ["ABC", "ABCD", "BCA"],
    [
      { kind: "run", symbol: "A", count: 5 },
      { kind: "dict", index: 0 },
      { kind: "dict", index: 1 },
      { kind: "dict", index: 0 },
      { kind: "run", symbol: "A", count: 6 },
    ],
  ),
];
