// SPDX-License-Identifier: GPL-3.0-only
import type {
  KitchenLevel,
  KitchenStation,
  KitchenTask,
} from "./concurrentKitchenLogic";
const task = (
  id: string,
  name: string,
  station: KitchenStation,
  duration: number,
  after = "",
): KitchenTask => ({ id, name, station, duration, after: [...after] });
const level = (
  title: string,
  deadline: number,
  lesson: string,
  tasks: KitchenTask[],
  starts: number[],
): KitchenLevel => ({
  title,
  deadline,
  lesson,
  tasks,
  solution: tasks.map((item, i) => ({ task: item.id, start: starts[i] })),
});
/** Twelve original handcrafted task graphs; independent tests certify deadlines. */
export const concurrentKitchenLevels: KitchenLevel[] = [
  level(
    "先后两步",
    4,
    "先选工序，再选开始刻度。A 用两格，结束后 B 才能接力；前一步恰好结束的刻度就能开始下一步。",
    [task("A", "星星配料", "prep", 2), task("B", "星星烘焙", "oven", 2, "A")],
    [0, 2],
  ),
  level(
    "让空台帮忙",
    5,
    "不同工作台可以同时忙。C 没有前置工序，可以和 A 或 B 并行，不必等整条链结束。",
    [
      task("A", "月亮配料", "prep", 2),
      task("B", "月亮烘焙", "oven", 3, "A"),
      task("C", "摆星形餐盘", "plate", 2),
    ],
    [0, 2, 0],
  ),
  level(
    "谁先用配料台",
    6,
    "同一台只能做一件事。想一想：哪份配料后面还接着更长的工作？先给它腾出路。",
    [
      task("A", "云朵配料", "prep", 2),
      task("B", "云朵烘焙", "oven", 3, "A"),
      task("C", "彩色配料", "prep", 2),
      task("D", "云彩装盘", "plate", 1, "BC"),
    ],
    [0, 2, 2, 5],
  ),
  level(
    "填上烤箱空档",
    6,
    "有的工序一开始就能做，有的要等配料。比较两种烤箱顺序，利用等待的空档。",
    [
      task("A", "新月配料", "prep", 1),
      task("B", "新月烘焙", "oven", 3, "A"),
      task("C", "星环烘焙", "oven", 2),
      task("D", "星月合盘", "plate", 1, "BC"),
    ],
    [0, 2, 0, 5],
  ),
  level(
    "先喂饱哪条线",
    7,
    "短工序也可能值得先做：它能否尽早让另一台开工？比较整张时间表，不只比较工序长短。",
    [
      task("A", "长条配料", "prep", 2),
      task("B", "长条烘焙", "oven", 3, "A"),
      task("C", "圆点配料", "prep", 1),
      task("D", "圆点烘焙", "oven", 2, "C"),
      task("E", "双色合盘", "plate", 1, "BD"),
    ],
    [1, 3, 0, 1, 6],
  ),
  level(
    "另一条长尾巴",
    6,
    "真正耗时的链可能通向装盘台。先看每条链剩下多长，再决定谁占用配料台。",
    [
      task("A", "方块配料", "prep", 2),
      task("B", "方块烘焙", "oven", 2, "A"),
      task("C", "花瓣配料", "prep", 1),
      task("D", "花瓣拼盘", "plate", 3, "C"),
      task("E", "方花合盘", "plate", 1, "BD"),
    ],
    [1, 3, 0, 1, 5],
  ),
  level(
    "交错的出餐线",
    8,
    "烘焙完成不等于整条链完成。把后续装盘也画进时间表，别让看似高效的顺序拖住最后的汇合。",
    [
      task("A", "日光配料", "prep", 2),
      task("B", "日光烘焙", "oven", 3, "A"),
      task("C", "星点配料", "prep", 1),
      task("D", "星点烘焙", "oven", 2, "C"),
      task("E", "日光装盘", "plate", 2, "B"),
      task("F", "星日合盘", "plate", 1, "DE"),
    ],
    [0, 2, 2, 5, 5, 7],
  ),
  level(
    "绕回烤箱",
    8,
    "工序可以跨台后再回到烤箱。沿着前置关系读完整条链，再找两条链能同时前进的区间。",
    [
      task("A", "流星配料", "prep", 1),
      task("B", "流星烘焙", "oven", 3, "A"),
      task("C", "彗星配料", "prep", 2),
      task("D", "彗星造型", "plate", 2, "C"),
      task("E", "彗星烘焙", "oven", 2, "D"),
      task("F", "双星合盘", "plate", 1, "BE"),
    ],
    [0, 1, 1, 3, 5, 7],
  ),
  level(
    "双线回收",
    9,
    "配料台在后半程还会被再次需要。汇合工序必须等两条线都结束，空台并不总表示它已经可开始。",
    [
      task("A", "蓝队配料", "prep", 2),
      task("B", "蓝队烘焙", "oven", 3, "A"),
      task("C", "蓝队装盘", "plate", 2, "B"),
      task("D", "橙队配料", "prep", 1),
      task("E", "橙队烘焙", "oven", 2, "D"),
      task("F", "橙队装盘", "plate", 1, "E"),
      task("G", "双队配饰", "prep", 1, "CF"),
    ],
    [0, 2, 5, 2, 5, 7, 8],
  ),
  level(
    "烤箱最后一格",
    9,
    "最后一次烘焙要等两份装盘。先给最后工序留位置，再向前检查两条支线能否赶到。",
    [
      task("A", "方队配料", "prep", 2),
      task("B", "方队烘焙", "oven", 2, "A"),
      task("C", "方队造型", "plate", 2, "B"),
      task("D", "圆队配料", "prep", 1),
      task("E", "圆队烘焙", "oven", 3, "D"),
      task("F", "圆队造型", "plate", 1, "E"),
      task("G", "双队收尾", "oven", 1, "CF"),
    ],
    [0, 2, 4, 2, 4, 7, 8],
  ),
  level(
    "八步交响",
    8,
    "找出几乎没有余量的长链，再把短链嵌入空档。注意返工位的工序也会争用同一个工作台。",
    [
      task("A", "晨星配料", "prep", 1),
      task("B", "晨星烘焙", "oven", 3, "A"),
      task("C", "晨星造型", "plate", 2, "B"),
      task("D", "夜星配料", "prep", 2),
      task("E", "夜星烘焙", "oven", 2, "D"),
      task("F", "夜星造型", "plate", 1, "E"),
      task("G", "晨星配饰", "prep", 1, "C"),
      task("H", "星空收尾", "oven", 1, "FG"),
    ],
    [0, 1, 4, 1, 4, 6, 6, 7],
  ),
  level(
    "厨房调度师",
    11,
    "把期限从最后一次汇合向前推，再检查三台的占用。长工序优先或短工序优先都不是万能规则；要看它释放了哪条后续链。",
    [
      task("A", "银河配料", "prep", 2),
      task("B", "银河烘焙", "oven", 3, "A"),
      task("C", "银河造型", "plate", 2, "B"),
      task("D", "星云配料", "prep", 1),
      task("E", "星云烘焙", "oven", 2, "D"),
      task("F", "星云造型", "plate", 3, "E"),
      task("G", "星河配饰", "prep", 1, "CF"),
      task("H", "星河收尾", "oven", 2, "G"),
    ],
    [1, 3, 6, 0, 1, 3, 8, 9],
  ),
];
