// SPDX-License-Identifier: GPL-3.0-only
import {useEffect,useRef,useState} from "react";
import type {GameProps} from "../lib/types";
import {diceCategoryInfo,diceCombinationsLevels,diceFinished,diceHint,diceInitial,diceMove,diceScore,diceTotal,diceWon,type DiceAction,type DiceState} from "./diceCombinationsLogic";
import "./diceCombinations.css";
const pipPositions:Record<number,number[]>={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]};
export default function DiceCombinations(props:GameProps){return <Round key={`${props.level}:${props.resetToken}`} {...props}/>;}
function Round({level,paused,hintToken,undoToken,onStatus,onComplete}:GameProps){
 const config=diceCombinationsLevels[level]??diceCombinationsLevels[0];const[state,setState]=useState(()=>diceInitial(config)),[history,setHistory]=useState<DiceState[]>([]),[hint,setHint]=useState<ReturnType<typeof diceHint>|null>(null),[feedback,setFeedback]=useState("点骰子保留，再重投未保留的骰子。合适时点栏目记分。");const seenHint=useRef(hintToken),seenUndo=useRef(undoToken),done=useRef(false);const finished=diceFinished(config,state),won=diceWon(config,state),locked=paused||finished,total=diceTotal(state);
 useEffect(()=>{onStatus("固定教学骰序，非随机。每轮最多重投两次；每个栏目只记一次，填完全部栏目并达到目标分数获胜。");},[]);
 useEffect(()=>{if(seenHint.current===hintToken)return;seenHint.current=hintToken;if(paused||won)return;const next=diceHint(config,state);setHint(next);setFeedback(next.text);onStatus(next.text);},[hintToken,paused,won,config,state,onStatus]);
 useEffect(()=>{if(seenUndo.current===undoToken)return;seenUndo.current=undoToken;if(paused||won)return;if(history.length){setState(history[history.length-1]);setHistory(history.slice(0,-1));setHint(null);setFeedback("已撤销一次保留、重投或记分，固定骰序也已恢复。");}else setFeedback("还没有可以撤销的操作。");},[undoToken,paused,won,history]);
 useEffect(()=>{if(won&&!paused&&!done.current){done.current=true;onStatus(`组合完成！${total} 分，达到 ${config.target} 分目标。`);onComplete();}},[won,paused,total,config.target,onStatus,onComplete]);
 function act(action:DiceAction){if(locked)return;const next=diceMove(config,state,action);if(!next)return;setHistory([...history,state]);setState(next);setHint(null);setFeedback(action.kind==="score"?`“${diceCategoryInfo[action.category].title}”记入 ${diceScore(action.category,state.dice)} 分。${diceFinished(config,next)?"全部栏目已填完。":"进入下一轮，重新选择保留。"}`:action.kind==="roll"?"已按公开的固定序列重投；保留的骰子点数不变。":"已更新保留。未保留的骰子会被下一行固定点数替换。");}
 return <div className="puzzle-layout dc-game" data-dice-state={JSON.stringify(state)} data-dice-won={won} data-dice-finished={finished} data-dice-moves={history.length}><section className="dc-workbench" aria-label="骰子组合工作台"><header><span className="mini-label">DICE LAB · {config.title}</span><strong>{total} / {config.target} 分</strong></header><p className="dc-disclosure">固定教学骰序 · 没有随机投掷 · 无金钱或下注</p><div className="dc-round"><span>第 {Math.min(state.round+1,config.rounds.length)} / {config.rounds.length} 轮</span><span>剩余重投 {finished?0:2-state.roll} 次</span></div>
 <div className="dc-dice">{state.dice.map((value,i)=><button key={i} data-die={i} className={`dc-die ${state.held&(1<<i)?"dc-held":""} ${hint?.holdMask!==null&&hint?.holdMask!==undefined&&(hint.holdMask&(1<<i))?"dc-hinted":""}`} disabled={locked||state.roll>=2} aria-pressed={Boolean(state.held&(1<<i))} aria-label={`第 ${i+1} 颗骰子，${value} 点，${state.held&(1<<i)?"已保留":"未保留"}`} onClick={()=>act({kind:"hold",index:i})}><span className="dc-face" aria-hidden="true">{Array.from({length:9},(_,p)=><i key={p} className={pipPositions[value].includes(p)?"dc-pip":""}/>)}</span><small>{state.held&(1<<i)?"保留":"可重投"}</small></button>)}</div>
 <button className={`dc-roll ${hint?.holdMask!==null&&hint?.holdMask!==undefined?"dc-hinted":""}`} disabled={locked||state.roll>=2||state.held===31} onClick={()=>act({kind:"roll"})}>重投未保留骰子</button><p className="dc-next">{finished?"本课已结束":state.roll<2?`下一行固定点数：${config.rounds[state.round][state.roll+1].join(" · ")}（从左到右）`:"重投机会已用完，请选择一个未用栏目记分。"}</p>
 <div className="dc-scorecard" aria-label="每个栏目只能记分一次">{config.categories.map(category=>{const used=state.scores[category]!==undefined,score=used?state.scores[category]!:diceScore(category,state.dice);return <button key={category} data-dice-category={category} className={`${used?"dc-used":""} ${hint?.category===category?"dc-hinted":""}`} disabled={locked||used} onClick={()=>act({kind:"score",category})} aria-label={`${diceCategoryInfo[category].title}，${used?"已记":"当前可记"} ${score} 分`}><span><strong>{diceCategoryInfo[category].title}</strong><small>{diceCategoryInfo[category].rule}</small></span><b>{score}<small>{used?"已记分":"记分"}</small></b></button>;})}</div>
 <p className="dc-feedback" role="status">{paused?"已暂停，骰子和记分栏已锁定。":won?`花束完成！总分 ${total}，目标 ${config.target}。`:finished?`本课得到 ${total} 分，未达到 ${config.target} 分。可以撤销记分，或重来。`:feedback}</p>
 </section><aside className="game-notes dc-notes"><span className="mini-label">保留 · 重投 · 分配栏目</span><h3>每颗骰子都有去处。</h3><p>{config.lesson}</p><ol><li>每轮起手五颗骰子，最多重投两次。点骰子切换保留；重投只替换没保留的骰子。</li><li>任何时候都能选择一个未用栏目记分，不符合组合时该栏得 0 分，也会被用掉。</li><li>每个栏目整课仅用一次。全部填完且总分达到目标才算成功；不足可以撤销。</li></ol><p>8 课是预先固定、公开的教学骰序，不是真随机游戏，不提供中奖概率。每行第 1–5 个数字对应同一颗骰子；保留项不替换。没有金钱、奖励或下注。</p><details><summary>查看本课完整固定骰序</summary>{config.rounds.map((frames,r)=><div className="dc-sequence" key={r}><strong>第 {r+1} 轮</strong>{frames.map((frame,f)=><p key={f}>{f===0?"起手":`重投 ${f}`}：{frame.join(" · ")}</p>)}</div>)}</details><p>点按或 Tab + Enter / 空格。提示会计算当前固定序列下的最高可达分；它不会改变骰子或保留状态。</p></aside></div>;
}
