// SPDX-License-Identifier: GPL-3.0-only
import {useEffect,useRef,useState} from "react";
import type {GameProps} from "../lib/types";
import {fallingRocksLevels,initialMine,mineArrows,mineDirectionNames,mineHint,mineStep,mineTotal,mineWon} from "./fallingRocksLogic";
import type {MineAction,MineState} from "./fallingRocksLogic";
import "./fallingRocks.css";
export default function FallingRocks(props:GameProps){return <Round key={`${props.level}:${props.resetToken}`} {...props}/>;}
function Round({level,paused,hintToken,undoToken,onStatus,onComplete}:GameProps){
 const config=fallingRocksLevels[level]??fallingRocksLevels[0],width=config.map[0].length,total=mineTotal(config);
 const [state,setState]=useState(()=>initialMine(config)),[history,setHistory]=useState<MineState[]>([]),[mode,setMode]=useState<"walk"|"dig">("walk"),[hint,setHint]=useState<MineAction|null>(null),[message,setMessage]=useState("先看头顶有没有岩石。侧挖只挖相邻泥土，矿工留在原地。");
 const seenHint=useRef(hintToken),seenUndo=useRef(undoToken),done=useRef(false),won=mineWon(config,state),locked=paused||won||state.lost;
 useEffect(()=>{onStatus("行走或侧挖一步后，所有失去支撑的岩石下落一格。收齐宝石，安全走进出口。岩石不能推动。");},[]);
 useEffect(()=>{if(seenHint.current===hintToken)return;seenHint.current=hintToken;if(paused||won)return;const result=mineHint(config,state);let text="";setHint(null);if(result.status==="route"){setHint(result.action);if(result.action.kind!=="wait")setMode(result.action.kind);text=`下一步${result.action.kind==="wait"?"原地等待一回合":`向${mineDirectionNames[result.action.direction]}${result.action.kind==="dig"?"侧挖泥土（人不移动）":"走一格"}`}。当前有一条 ${result.length} 回合的安全路线。`;}else if(result.status==="lost")text="被落石碰到了。撤销最近一步，改用侧挖或换一条路。";else if(result.status==="dead-end")text="当前状态没有可通关路线。撤销到岩石落下前，再安排挖掘顺序。";else if(result.status==="budget")text="这次有限搜索还没找到完整路线，不能判定无解。先观察岩石正下方的支撑土，必要时撤销。";setMessage(text);onStatus(text);},[hintToken,paused,won,state,config,onStatus]);
 useEffect(()=>{if(seenUndo.current===undoToken)return;seenUndo.current=undoToken;if(paused||won)return;if(history.length){setState(history.at(-1)!);setHistory(history.slice(0,-1));setHint(null);setMessage("已撤销。岩石、泥土、宝石与矿工位置都恢复了。");}else onStatus("还没有回合可以撤销。");},[undoToken,paused,won,history,onStatus]);
 useEffect(()=>{if(won&&!paused&&!done.current){done.current=true;onStatus("宝石采齐，矿工安全出洞！");onComplete();}},[won,paused,onStatus,onComplete]);
 function act(action:MineAction){if(locked)return;const next=mineStep(config,state,action);if(next===state){setMessage(action.kind==="dig"?"这个方向没有相邻的支撑土。侧挖不会挖岩石、墙壁或宝石。":"这个方向被挡住了，岩石不能推动。无效操作不会推进回合。");return;}setHistory([...history,state]);setState(next);setHint(null);setMessage(next.lost?"落石碰到了矿工。可以撤销，再从侧面挖或先离开危险位置。":next.gems>state.gems?`找到一颗宝石！还差 ${total-next.gems} 颗。`:action.kind==="dig"?"泥土挖开了，观察岩石的新位置。":action.kind==="wait"?"等了一回合，岩石最多再落一格。":"走稳一步。下回合前，看看头顶。");}
 return <div className="puzzle-layout fr-game" data-fr-state={JSON.stringify(state)} data-fr-won={won} data-fr-lost={state.lost} data-fr-moves={history.length}>
  <section className="fr-workbench"><header><span className="mini-label">落石矿洞 · {config.title}</span><strong>{history.length} 回合</strong></header><div className="fr-meter"><span>✦ 宝石 {state.gems}/{total}</span><span>岩石每回合 ↓ 一格</span></div>
   <div className="fr-board" style={{gridTemplateColumns:`repeat(${width},1fr)`}} tabIndex={locked?-1:0} role="group" aria-label={`矿洞棋盘，当前${mode==="walk"?"行走":"侧挖"}模式。方向键操作，D 切换模式，句号等待。`} onKeyDown={e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;const direction=["ArrowUp","ArrowRight","ArrowDown","ArrowLeft"].indexOf(e.key);if(direction>=0){e.preventDefault();act({kind:mode,direction});}else if(e.key.toLowerCase()==="d"&&!locked){e.preventDefault();setMode(mode==="walk"?"dig":"walk");setHint(null);}else if(e.key==="."){e.preventDefault();act({kind:"wait"});}}}>{[...state.cells].map((ch,i)=><div key={i} className={`fr-cell ${ch==="#"?"fr-wall":"fr-floor"} ${ch===":"?"fr-soil":""} ${ch==="E"?"fr-exit":""}`} aria-label={i===state.player?state.lost?"矿工被落石碰到":"矿工":ch==="#"?"墙壁":ch==="o"?"岩石":ch===":"?"支撑土":ch==="*"?"宝石":ch==="E"?"出口":"空地"}>{i===state.player?<span className={`fr-miner ${state.lost?"fr-hurt":""}`}>{state.lost?"×":"●"}</span>:ch==="o"?<span className="fr-rock">◆</span>:ch==="*"?<span className="fr-gem">✦</span>:ch==="E"?<span>⌂</span>:ch===":"?<span className="fr-dirt-dots">∴</span>:null}</div>)}</div>
   <div className="fr-modes" aria-label="操作模式"><button data-fr-mode="walk" aria-pressed={mode==="walk"} disabled={locked} onClick={()=>{setMode("walk");setHint(null);}}>行走 · 人会移动</button><button data-fr-mode="dig" aria-pressed={mode==="dig"} disabled={locked} onClick={()=>{setMode("dig");setHint(null);}}>侧挖 · 留在原地</button></div>
   <div className="fr-controls" aria-label="方向控制">{[0,3,2,1].map(d=><button key={d} data-fr-direction={d} className={`${d===0?"fr-up":""} ${hint&&hint.kind!=="wait"&&hint.direction===d?"fr-hinted":""}`} disabled={locked} onClick={()=>act({kind:mode,direction:d})} aria-label={`向${mineDirectionNames[d]}${mode==="walk"?"走":"侧挖"}`}>{mineArrows[d]}</button>)}<button data-fr-wait className={`fr-wait ${hint?.kind==="wait"?"fr-hinted":""}`} disabled={locked} onClick={()=>act({kind:"wait"})}>等一回合</button></div>
   <p className="fr-feedback" role="status">{paused?"已暂停，矿洞里的时间停住了。":won?"每一颗宝石都带出来了，安全最重要。":message}</p>
  </section><aside className="game-notes"><span className="mini-label">挖掘 · 支撑 · 回合规划</span><h3>挖开之前，先看上面。</h3><p>{config.lesson}</p><ol><li>行走时能挖开脚前泥土、拾取宝石，但不能推动岩石。</li><li>侧挖模式只移除相邻泥土，人留在原位。用它安全地拆掉岩石的支撑。</li><li>每次有效行走、侧挖或等待后，岩石从下往上结算，各下落至多一格。土、墙、宝石和出口都能支撑岩石。</li><li>落石碰到矿工会失败，可以撤销。采齐所有宝石再走进出口才通关。</li></ol><p>触屏使用模式和方向按钮。键盘聚焦棋盘后用方向键，D 切换行走/侧挖，句号等一回合。无效操作不推进时间。</p><p>只有你行动，矿洞才变化。没有实时倒计时。</p></aside>
 </div>;
}
