// SPDX-License-Identifier: GPL-3.0-only
import {useEffect,useRef,useState} from 'react';
import type {GameProps} from '../lib/types';
import {foxHoundsLevels,foxMoves,foxMove,foxResult,foxSearch,houndMove,foxRow,foxCol,type FoxPosition} from './foxHoundsLogic';
import './foxHoundsGarden.css';
type Turn={position:FoxPosition;turns:number;result:'playing'|'won'|'lost'|'draw';lastHound:number|null};
const steps=[{label:'左上',key:'q',dx:-1,dy:-1,glyph:'↖'},{label:'右上',key:'e',dx:1,dy:-1,glyph:'↗'},{label:'左下',key:'z',dx:-1,dy:1,glyph:'↙'},{label:'右下',key:'c',dx:1,dy:1,glyph:'↘'}];
export default function FoxHoundsGarden(props:GameProps){return <FoxRound key={`${props.level}:${props.resetToken}`} {...props}/>;}
function FoxRound({level,paused,hintToken,undoToken,onComplete,onStatus}:GameProps){const l=foxHoundsLevels[level]??foxHoundsLevels[0];const [history,setHistory]=useState<Turn[]>([{position:l.position,turns:0,result:'playing',lastHound:null}]),[message,setMessage]=useState(l.tip),[hint,setHint]=useState<number|null>(null);const p=history[history.length-1],done=useRef(false),tokens=useRef({hintToken,undoToken}),state=useRef({p,history,paused});state.current={p,history,paused};const callbacks=useRef({onComplete,onStatus});callbacks.current={onComplete,onStatus};const report=(text:string)=>{setMessage(text);callbacks.current.onStatus(text);};
 useEffect(()=>{callbacks.current.onStatus(l.tip);},[]);useEffect(()=>{if(p.result==='won'&&!paused&&!done.current){done.current=true;callbacks.current.onComplete();}},[p.result,paused]);
 useEffect(()=>{if(tokens.current.undoToken===undoToken)return;tokens.current.undoToken=undoToken;if(paused||done.current)return;if(history.length>1){setHistory(history.slice(0,-1));setHint(null);report('狐狸和猎犬一起退回上一轮之前。');}},[undoToken]);
 useEffect(()=>{if(tokens.current.hintToken===hintToken)return;tokens.current.hintToken=hintToken;if(paused||p.result!=='playing')return;const suggestion=foxSearch(p.position,'fox');setHint(suggestion.fox);report(suggestion.fox===null?'狐狸已无路可走，可以撤销。':`六层本地搜索建议：走到第 ${foxRow(suggestion.fox)+1} 行、第 ${foxCol(suggestion.fox)+1} 列。${suggestion.value>=10000?'这条路线能突破围堵。':'这是有限深度建议，不保证必胜。'}`);},[hintToken]);
 function move(to:number){const now=state.current;if(now.paused||now.p.result!=='playing'||!foxMoves(now.p.position).includes(to))return;let position=foxMove(now.p.position,to),result:Turn['result']=foxResult(position),lastHound:number|null=null;let reply='';if(result==='playing'){const ai=foxSearch(position,'hound').hound;if(ai){position=houndMove(position,ai);lastHound=ai.to;reply=`猎犬走到 ${foxRow(ai.to)+1} 行 ${foxCol(ai.to)+1} 列。`;result=foxResult(position);}else reply='猎犬无路可走，这轮跳过。';}const turns=now.p.turns+1;if(result==='playing'&&turns>=40)result='draw';const next={position,result,lastHound,turns},h=[...now.history,next];state.current={p:next,history:h,paused};setHistory(h);setHint(null);report(result==='won'?'狐狸到达最下方出口，成功穿过森林！':result==='lost'?'四条斜路都被封住了。狐狸被围住，可以撤销整轮再试。':result==='draw'?'40 轮仍未到达出口，这盘结束。没有计为通关，可以撤销或重来。':`${reply}轮到狐狸。`);}
 const legal=foxMoves(p.position),locked=paused||p.result!=='playing';return <div className="fox-hounds" data-fox-position={JSON.stringify(p.position)} data-fox-result={p.result} data-fox-turns={p.turns} tabIndex={0} onKeyDown={e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;const d=steps.find(s=>s.key===e.key.toLowerCase());if(d){e.preventDefault();move(p.position.fox+d.dy*8+d.dx);}}}>
 <section className="fox-main"><header><div><span className="fox-eyebrow">FOX & HOUNDS · 森林小残局</span><h3>{l.title}</h3></div><b>{level+1} / {foxHoundsLevels.length}</b></header><p>你是橙色狐狸，四只猎犬由电脑控制。沿深色格子<strong>斜走一格</strong>，到达最下方的森林出口。</p><div className="fox-meter"><span>{paused?'已暂停':p.result==='won'?'狐狸逃出森林':p.result==='lost'?'狐狸被围住':p.result==='draw'?'本盘结束':'狐狸可前进，也可后退'}</span><b>{p.turns} / 40 轮</b></div>
 <div className="fox-frame"><div className="fox-board" role="img" aria-label={`森林棋盘，狐狸在 ${foxRow(p.position.fox)+1} 行 ${foxCol(p.position.fox)+1} 列，猎犬在 ${p.position.hounds.map(h=>`${foxRow(h)+1}行${foxCol(h)+1}列`).join('、')}。最下方为出口。`}>{Array.from({length:64},(_,i)=>{const dark=(foxRow(i)+foxCol(i))%2===1,fox=p.position.fox===i,hound=p.position.hounds.includes(i);return <div key={i} className={`fox-cell ${dark?'trail':'grass'} ${foxRow(i)===7&&dark?'exit':''} ${legal.includes(i)&&!locked?'reachable':''} ${hint===i?'hinted':''} ${p.lastHound===i?'last-hound':''}`} aria-hidden="true">{fox?<span className="fox-piece">◆<i>● ●</i></span>:hound?<span className="hound-piece">▲</span>:dark&&foxRow(i)===7?<span className="fox-exit">⌄</span>:legal.includes(i)&&!locked?<span className="fox-target">·</span>:null}</div>;})}</div><div className="fox-exit-label">↓ 森林出口 · 到达任意深色底格 ↓</div></div>
 <div className="fox-controls" aria-label="狐狸斜向移动">{steps.map(d=>{const x=foxCol(p.position.fox)+d.dx,y=foxRow(p.position.fox)+d.dy,to=y*8+x,available=x>=0&&x<8&&y>=0&&y<8&&legal.includes(to);return <button type="button" key={d.label} data-to={to} disabled={locked||!available} className={hint===to?'hinted':''} onClick={()=>move(to)} aria-label={`向${d.label}`}><span aria-hidden="true">{d.glyph}</span><b>{d.label}</b><small>{d.key.toUpperCase()}</small></button>;})}</div><p className="fox-message" role="status">{message}</p>{p.result==='won'&&<div className="fox-victory">✦ 狐狸轻轻穿过了树林</div>}</section>
 <aside className="fox-notes"><span className="fox-eyebrow">不同的脚步，同一片森林</span><h3>狐狸聪明在哪里？</h3><ol><li><b>狐狸：</b>斜走一格，四个方向都可以。</li><li><b>猎犬：</b>每轮只走一只，只能向上斜走，不能后退。</li><li><b>没有吃子：</b>不能落在其他棋子上，也不能跨越它们。</li><li><b>到达出口：</b>狐狸必须实际走到底行；被围住则失败。</li></ol><p>{l.tip}</p><details><summary>策略与操作说明</summary><p>电脑搜索未来六手，不保证最优。提示针对当前棋盘重新计算，并用金色标出建议目标。猎犬无路时跳过，狐狸仍须到达出口。40 轮内未逃出则结束，不计通关。</p><p>四个大按钮支持触摸和 Enter / 空格。聚焦游戏区域后，Q / E 斜向上，Z / C 斜向下。暂停禁用所有操作，撤销整轮，重来恢复残局；胜利后锁定。</p></details></aside></div>;}
