// SPDX-License-Identifier: GPL-3.0-only
import type { FactoryLevel } from "./functionFactoryLogic";
// Public directed stroke strings are authored fixtures, not derived at runtime from certificates.
export const functionFactoryLevels: FactoryLevel[] = [
  {
    title: "同一个转角",
    lesson: "把画一格再右转收进函数；同一份定义会从不同朝向执行。",
    lengths: [2, 0],
    calls: 3,
    target: "ESW",
    finalHeading: "N",
    certificate: { A: "FR", B: "", main: "AAA" },
  },
  {
    title: "左旋印章",
    lesson: "四次调用画出闭合轮廓，最后朝向也要回到东。",
    lengths: [2, 0],
    calls: 4,
    target: "ENWS",
    finalHeading: "E",
    certificate: { A: "FL", B: "", main: "AAAA" },
  },
  {
    title: "加长边框",
    lesson: "函数不只有两个动作。一个定义控制每条边的长度。",
    lengths: [3, 0],
    calls: 4,
    target: "EESSWWNN",
    finalHeading: "E",
    certificate: { A: "FFR", B: "", main: "AAAA" },
  },
  {
    title: "阶梯零件",
    lesson: "函数可以在内部转弯后恢复朝向；复用的是相对动作。",
    lengths: [4, 0],
    calls: 3,
    target: "ENENEN",
    finalHeading: "E",
    certificate: { A: "FLFR", B: "", main: "AAA" },
  },
  {
    title: "两种转角",
    lesson: "从现在起需要两个不同函数，每个至少调用两次。主程序决定拼接顺序。",
    lengths: [2, 2],
    calls: 4,
    target: "ESWS",
    finalHeading: "E",
    certificate: { A: "FR", B: "FL", main: "AABB" },
  },
  {
    title: "长短节拍",
    lesson: "长边和短边各是一块可复用零件；检查调用边界处的朝向。",
    lengths: [3, 2],
    calls: 4,
    target: "EESEES",
    finalHeading: "E",
    certificate: { A: "FFR", B: "FL", main: "ABAB" },
  },
  {
    title: "转弯的接口",
    lesson: "函数可以从转弯开始。调用结束的朝向，就是下一次调用的输入。",
    lengths: [3, 3],
    calls: 4,
    target: "ESENEN",
    finalHeading: "W",
    certificate: { A: "FRF", B: "LFL", main: "ABAB" },
  },
  {
    title: "插入小零件",
    lesson: "相同图案不一定连续调用；把短零件夹在长零件中间。",
    lengths: [4, 2],
    calls: 4,
    target: "ENESWS",
    finalHeading: "W",
    certificate: { A: "FLFR", B: "FR", main: "ABBA" },
  },
  {
    title: "双长与双折",
    lesson: "两种三格定义可以分组调用。画过同一条边也算一次有顺序的笔画。",
    lengths: [3, 3],
    calls: 4,
    target: "EENNWNNE",
    finalHeading: "E",
    certificate: { A: "FFL", B: "FRF", main: "AABB" },
  },
  {
    title: "回笔与移位",
    lesson: "掉头回描不是擦除。来回经过的每一段都要与目标次序一致。",
    lengths: [4, 4],
    calls: 4,
    target: "EWSSEWSS",
    finalHeading: "E",
    certificate: { A: "FRRF", B: "LFFL", main: "ABAB" },
  },
  {
    title: "错落编排",
    lesson: "六次调用共享七格定义。先找可以跨朝向复用的零件，再安排调用。",
    lengths: [4, 3],
    calls: 6,
    target: "ENNESEEENNEW",
    finalHeading: "N",
    certificate: { A: "FLFF", B: "RFR", main: "ABAABB" },
  },
  {
    title: "复用设计师",
    lesson:
      "只有八格定义，却要完成十五段有序笔画。两个不同零件都必须反复使用。",
    lengths: [4, 4],
    calls: 6,
    target: "ESEESSSWWNWWNNE",
    finalHeading: "N",
    certificate: { A: "FRFL", B: "FFRF", main: "ABBABA" },
  },
];
