// SPDX-License-Identifier: GPL-3.0-only
import {useEffect,useRef,useState} from "react";
import type {GameProps} from "../lib/types";
import {golfActions,golfCardsLevels,golfHint,golfInitial,golfMove,golfRank,golfWon,type GolfAction,type GolfState} from "./golfCardsLogic";
import "./golfCards.css";
export default function GolfCards(props:GameProps){return <Round key={`${props.level}:${props.resetToken}`} {...props}/>;}
function Round({level,paused,hintToken,undoToken,onStatus,onComplete}:GameProps){
 const config=golfCardsLevels[level]??golfCardsLevels[0];const[state,setState]=useState(()=>golfInitial(config)),[history,setHistory]=useState<GolfState[]>([]),[hint,setHint]=useState<ReturnType<typeof golfHint>|null>(null),[feedback,setFeedback]=useState("从牌列底部取出比废牌大 1 或小 1 的牌。");const seenHint=useRef(hintToken),seenUndo=useRef(undoToken),done=useRef(false);const won=golfWon(state),locked=paused||won;
 useEffect(()=>{onStatus("逐张接龙：底牌比废牌大 1 或小 1 即可取走。A 与 K 不循环；清空所有牌列获胜。");},[]);
 useEffect(()=>{if(seenHint.current===hintToken)return;seenHint.current=hintToken;if(locked)return;const next=golfHint(config,state);setHint(next);setFeedback(next.text);onStatus(next.text);},[hintToken,locked,config,state,onStatus]);
 useEffect(()=>{if(seenUndo.current===undoToken)return;seenUndo.current=undoToken;if(locked)return;if(history.length){setState(history[history.length-1]);setHistory(history.slice(0,-1));setHint(null);setFeedback("已恢复取牌或翻牌前的完整牌桌。");}else setFeedback("还没有可以撤销的动作。");},[undoToken,locked,history]);
 useEffect(()=>{if(won&&!paused&&!done.current){done.current=true;onStatus("长廊清空！每张牌都接上了回家的路。");onComplete();}},[won,paused,onStatus,onComplete]);
 function act(action:GolfAction){if(locked)return;const next=golfMove(config,state,action);if(!next){setFeedback("点数必须相差 1；A 和 K 不能相接，同点也不能相接。");setHint(null);return;}setHistory([...history,state]);setState(next);setHint(null);setFeedback(action.kind==="draw"?"储备牌已替换废牌。它不会循环；必要时可撤销。":"接上了！新的废牌点数已经改变，继续观察各列底部。");}
 const total=config.columns.reduce((n,c)=>n+c.length,0),remaining=state.heights.reduce((a,b)=>a+b,0),available=golfActions(config,state).filter(a=>a.kind==="play").length;
 return <div className="puzzle-layout gc-game" data-golf-state={JSON.stringify(state)} data-golf-won={won} data-golf-moves={history.length}><section className="gc-table" aria-label="逐张纸牌牌桌"><header><span className="mini-label">GOLF · {config.title}</span><strong>已清 {total-remaining}/{total}</strong></header><div className="gc-strip"><span>可接底牌 {available} 张</span><span>A ← 2 ··· Q → K</span><span>首尾不循环</span></div>
 <div className="gc-columns" style={{gridTemplateColumns:`repeat(${config.columns.length},1fr)`}}>{config.columns.map((column,c)=><div className="gc-column" key={c}><span className="gc-column-name">第 {c+1} 列</span>{column.map((rank,r)=>{const removed=r>=state.heights[c],exposed=r===state.heights[c]-1;return <button key={r} data-golf-column={c} data-golf-row={r} className={`gc-card ${removed?"gc-empty":""} ${!exposed?"gc-covered":""} ${exposed&&hint?.action?.kind==="play"&&hint.action.column===c?"gc-hinted":""}`} disabled={locked||!exposed} onClick={()=>act({kind:"play",column:c})} aria-label={`第 ${c+1} 列第 ${r+1} 张，${golfRank(rank)}，${removed?"已移除":exposed?"可选底牌":"被下方牌覆盖"}`}><span>{removed?"·":golfRank(rank)}</span><small>{removed?"空位":exposed?"底牌":"等待"}</small></button>;})}</div>)}</div>
 <div className="gc-bottom"><div className="gc-waste" aria-label={`当前废牌 ${golfRank(state.waste)}`}><span>当前废牌</span><strong>{golfRank(state.waste)}</strong><small>只接相差 1</small></div><div className="gc-reserve"><button className={hint?.action?.kind==="draw"?"gc-hinted":""} onClick={()=>act({kind:"draw"})} disabled={locked||state.stockIndex>=config.stock.length}>翻储备牌 · 剩 {config.stock.length-state.stockIndex}</button><p>接下来：{config.stock.slice(state.stockIndex).map(golfRank).join(" → ")||"已用完"}</p><small>翻牌会替换当前废牌</small></div></div>
 <p className="gc-feedback" role="status">{paused?"已暂停，牌列与储备牌已锁定。":won?"所有牌列都清空啦！":feedback}</p></section><aside className="game-notes gc-notes"><span className="mini-label">邻数接龙 · 顺序规划</span><h3>差一步，就能接上。</h3><p>{config.lesson}</p><ol><li>只能取每列最下方还在的牌。点数比当前废牌大 1 或小 1，就能放到废牌上。</li><li>A=1，J=11，Q=12，K=13；没有 K↔A 循环，同点不能相接。花色无关。</li><li>随时可以翻下一张储备牌，但原废牌就不能再用了。储备不循环，用完就没有了。</li><li>清空所有牌列获胜，剩余储备牌可以不用。</li></ol><p>8 个原创微型教学牌组，每课 6–12 张列牌。为了练习规划，全部牌列与储备次序公开；不是完整随机纸牌局。</p><p>点按或 Tab + Enter / 空格操作。提示从当前状态寻找清场路线；走不通时可以撤销。</p></aside></div>;
}
