// SPDX-License-Identifier: GPL-3.0-only
import {useEffect,useRef,useState} from "react";
import type {GameProps} from "../lib/types";
import {gravityArrows,gravityMazeLevels,gravityNames,gravityPlan,gravityWon,gravityWorld,initialGravity,rotateGravity} from "./gravityMazeLogic";
import type {GravityState} from "./gravityMazeLogic";
import "./gravityMaze.css";
export default function GravityMaze(props:GameProps){return <Round key={`${props.level}:${props.resetToken}`} {...props}/>;}
function Round({level,paused,hintToken,undoToken,onStatus,onComplete}:GameProps){
 const config=gravityMazeLevels[level]??gravityMazeLevels[0],world=gravityWorld(config);
 const [state,setState]=useState(()=>initialGravity(config)),[history,setHistory]=useState<GravityState[]>([]),[hint,setHint]=useState<-1|1|null>(null),[message,setMessage]=useState("转动重力，小球会一直落到墙壁或锁门旁。");
 const seenHint=useRef(hintToken),seenUndo=useRef(undoToken),done=useRef(false),won=gravityWon(config,state),locked=paused||won||state.lost;
 useEffect(()=>{onStatus("每次把重力转 90°，小球沿新方向落到底。收集全部钥匙打开对应字母的门，再进入出口。");},[]);
 useEffect(()=>{if(seenHint.current===hintToken)return;seenHint.current=hintToken;if(paused||won)return;const plan=gravityPlan(config,state);const text=state.lost?"碰到荆棘了。撤销最后一次转动，就能回到安全位置。":plan?.length?`下一步${plan[0]===1?"顺时针":"逆时针"}转动，让重力朝${gravityNames[(state.direction+plan[0]+4)%4]}。当前还有 ${plan.length} 次转动的一条可行路线。`:"这个落点已经没有通关路线。请撤销，回到之前的岔路再试。";setHint(plan?.[0]??null);setMessage(text);onStatus(text);},[hintToken,paused,won,state,config,onStatus]);
 useEffect(()=>{if(seenUndo.current===undoToken)return;seenUndo.current=undoToken;if(paused||won)return;if(history.length){setState(history.at(-1)!);setHistory(history.slice(0,-1));setHint(null);setMessage("已撤销，钥匙、位置与重力方向一起恢复。");}else onStatus("还没有转动可以撤销。");},[undoToken,paused,won,history,onStatus]);
 useEffect(()=>{if(won&&!paused&&!done.current){done.current=true;onStatus("带齐钥匙，安全抵达出口！");onComplete();}},[won,paused,onStatus,onComplete]);
 function turn(value:-1|1){if(locked)return;const next=rotateGravity(config,state,value);setHistory([...history,state]);setState(next);setHint(null);setMessage(next.lost?"碰到荆棘了。可以撤销这一步，再找别的路。":`重力朝${gravityNames[next.direction]}，已停稳。${next.keys!==state.keys?"新钥匙已收好，对应的门打开了。":""}`);}
 return <div className="puzzle-layout gm-game" data-gm-state={JSON.stringify(state)} data-gm-won={won} data-gm-lost={state.lost} data-gm-moves={history.length}>
  <section className="gm-workbench"><header><span className="mini-label">重力回廊 · {config.title}</span><strong>{history.length} 次转动</strong></header><div className="gm-meter"><span className="gm-compass">{gravityArrows[state.direction]} <b>重力朝{gravityNames[state.direction]}</b></span><div className="gm-keys">{[0,1,2].filter(k=>world.allKeys&(1<<k)).map(k=><span key={k} className={state.keys&(1<<k)?"gm-collected":""}>{String.fromCharCode(65+k)} {state.keys&(1<<k)?"✓":"钥匙"}</span>)}</div></div>
   <div className="gm-board" style={{gridTemplateColumns:`repeat(${world.width},1fr)`}} tabIndex={locked?-1:0} role="group" aria-label={`重力棋盘，当前朝${gravityNames[state.direction]}。左右方向键旋转重力。`} onKeyDown={e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;if(e.key==="ArrowLeft"||e.key==="ArrowRight"){e.preventDefault();turn(e.key==="ArrowLeft"?-1:1);}}}>{world.cells.map((ch,i)=>{const key=ch>="a"&&ch<="c",gate=ch>="A"&&ch<="C",bit=key?1<<(ch.charCodeAt(0)-97):gate?1<<(ch.charCodeAt(0)-65):0,open=gate&&!!(state.keys&bit);return <div key={i} className={`gm-cell ${ch==="#"?"gm-wall":"gm-floor"} ${gate?`gm-gate ${open?"gm-open":""}`:""} ${ch==="X"?"gm-thorn":""} ${ch==="E"?"gm-exit":""}`} aria-label={i===state.position?"小球":ch==="#"?"墙":gate?`${ch} 门${open?"已开":"上锁"}`:key&&!(state.keys&bit)?`${ch.toUpperCase()} 钥匙`:ch==="E"?"出口":ch==="X"?"荆棘":"通道"}>{i===state.position?<span className={`gm-ball ${state.lost?"gm-hurt":""}`}>●</span>:gate?<span>{ch}<small>{open?"开":"锁"}</small></span>:key&&!(state.keys&bit)?<span className="gm-key">⚿<small>{ch.toUpperCase()}</small></span>:ch==="E"?<span>⌂</span>:ch==="X"?<span>✹</span>:null}</div>;})}</div>
   <div className="gm-controls"><button data-gm-turn="-1" className={hint===-1?"gm-hinted":""} disabled={locked} onClick={()=>turn(-1)}>↶ 逆时针 90°</button><button data-gm-turn="1" className={hint===1?"gm-hinted":""} disabled={locked} onClick={()=>turn(1)}>↷ 顺时针 90°</button></div><p className="gm-feedback" role="status">{paused?"已暂停，重力锁定。":won?"所有钥匙都在，小球到家了。":message}</p>
  </section><aside className="game-notes"><span className="mini-label">重力 · 钥匙 · 方向规划</span><h3>转动方向，改变落点。</h3><p>{config.lesson}</p><ol><li>每次只将重力顺时针或逆时针转 90°。小球沿该方向一直落到墙或锁门旁。</li><li>途中碰到钥匙就会收集，并永久打开同字母的所有门。已收集钥匙会随撤销恢复。</li><li>集齐每一把钥匙后，出口会接住小球。未集齐时，经过出口不会通关。</li></ol><p>✹ 是荆棘，碰到会结束这次尝试，仍可撤销或重来。转向墙壁也会改变重力方向，可能是必要的一步。</p><p>没有计时或自动下落。触屏点旋转按钮；键盘聚焦棋盘后按 ← / →，或者 Tab 和 Enter 操作按钮。</p></aside>
 </div>;
}
