// SPDX-License-Identifier: GPL-3.0-only
import {useEffect,useRef,useState} from 'react';
import type {GameProps} from '../lib/types';
import {BattleController,Unit,Hex,Terrain,UnitStatus,keyOf,races,type TypeKey} from './hexaBattleController';
import type {IUnitType} from '../vendor/hexaBattle/engine/unit';
import './hexaBattle.css';
const names:Record<string,string>={Archer:'弓手',Barbarian:'狂战士',Catapult:'投石车',Cleric:'牧师',Horseman:'骑兵',Knight:'骑士',Mage:'法师',Warrior:'战士',Bat:'蝙蝠',Demon:'恶魔',Dragon:'巨龙',Giant:'巨人',Orc:'兽人','Orc Archer':'兽人弓手',Spider:'蜘蛛',Troll:'山怪','Melee Attack':'近战','Ranged Attack':'远射','Fire Breath':'龙息',Fireball:'火球',Guard:'防御',Heal:'治疗',Jump:'跳跃','Rolling Stone':'滚石',Sleep:'催眠','Stone Throw':'投石',Teleport:'传送','Two Handed Sword Attack':'横扫',Web:'蛛网'};
const actionHelp:Record<string,string>={'Melee Attack':'攻击相邻格。','Ranged Attack':'射击高亮范围，近距离盲区不可选。','Fire Breath':'伤害相邻目标，附加持续燃烧。',Fireball:'沿六方向施放，爆炸覆盖目标周围七格。',Guard:'本次防守提升1点抗性。',Heal:'恢复相邻单位3点生命，消耗1魔力。',Jump:'跳到两格内空地，越过障碍。','Rolling Stone':'沿直线连续撞击多个目标。',Sleep:'使目标陷入睡眠，消耗2魔力。','Stone Throw':'远距投石，周边单位也会受伤。',Teleport:'传送到六格内空地，消耗2魔力。','Two Handed Sword Attack':'同时横扫前方三个相邻格。',Web:'远距伤害并减速目标。'};
const name=(s:string)=>names[s]||s;
const statuses:Record<number,string>={[UnitStatus.Guard]:'防御',[UnitStatus.Sleeping]:'睡眠',[UnitStatus.Burning]:'燃烧',[UnitStatus.Slowed]:'减速'};
const position=(q:number,r:number)=>({x:Math.sqrt(3)*28*(q+r/2),y:42*r});
const points=Array.from({length:6},(_,i)=>{const a=(60*i-30)*Math.PI/180;return`${28*Math.cos(a)},${28*Math.sin(a)}`;}).join(' ');
function UnitCard({unit}:{unit:IUnitType}){return <><b>{name(unit.name)}</b><span>生命{unit.hp} · 移动{unit.mp} · 魔力{unit.mana} · 抗性{unit.resistance}</span><small>{unit.actions.map(A=>name(new A(null as never,null as never).name)).join(' / ')}{unit.traits?.length?' · 飞行':''}</small></>;}
export default function HexaBattleGame({paused,freshStart,hintToken,onStatus}:GameProps){
 const [model,setModel]=useState<BattleController|null>(null),[,redraw]=useState(0),[shop,setShop]=useState(false),[cart,setCart]=useState<TypeKey[]>([]),[saveOpen,setSaveOpen]=useState(false),[saveText,setSaveText]=useState(''),[confirmReset,setConfirmReset]=useState(false),[confirmRetreat,setConfirmRetreat]=useState(false);
 const board=useRef<HTMLDivElement>(null),status=useRef(onStatus),pause=useRef(paused),hint=useRef(hintToken);status.current=onStatus;pause.current=paused;
 useEffect(()=>{const m=new BattleController(()=>redraw(n=>n+1));m.setPaused(pause.current);setModel(m);if(freshStart)setConfirmReset(true);const read=()=>m.snapshot();(window as unknown as {__hbRead?:typeof read}).__hbRead=read;return()=>{m.dispose();const w=window as unknown as {__hbRead?:typeof read};if(w.__hbRead===read)delete w.__hbRead;};},[]);
 useEffect(()=>{model?.setPaused(paused||document.hidden);},[model,paused]);
 useEffect(()=>{if(!model)return;const visibility=()=>model.setPaused(pause.current||document.hidden);document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility);},[model]);
 useEffect(()=>{if(model)status.current(model.message);},[model,model?.message]);
 useEffect(()=>{if(hint.current===hintToken)return;hint.current=hintToken;status.current('优先集中攻击一名敌人。移动后仍可用一次技能；弓手留出两格距离，范围技能会伤到队友。保存生还者，再用战利品招募。');},[hintToken]);
 useEffect(()=>{if(!model)return;const key=(e:KeyboardEvent)=>{if(document.querySelector('.hb-dialog')||(e.target as HTMLElement).closest('input,textarea,select,button,[role="button"]'))return;if(e.key===' '){e.preventDefault();model.nextUnit();}else if(/^[1-9]$/.test(e.key)){model.selectAction(Number(e.key)-1);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[model]);
 useEffect(()=>{if(!model?.selected)return;const el=board.current?.querySelector(`[data-unit="${model.selected}"]`);el?.scrollIntoView({block:'nearest',inline:'nearest'});},[model?.selected,model?.game]);
 if(!model)return <p>正在准备远征…</p>;
 const m=model,game=m.game,selected=m.selectedUnit,disabled=paused||m.busy,action=selected?.actions[m.action];
 const allTypes=races.humans,cartCost=cart.reduce((sum,k)=>sum+(allTypes.find(u=>keyOf(u)===k)?.cost||0),0),moves=new Set(m.moveTargets.map(h=>h.toString())),targets=new Set(m.actionTargets.map(h=>h.toString()));
 const mapSize=game?.map instanceof Object&&'size'in game.map?Number(game.map.size):5,w=Math.sqrt(3)*28*mapSize*2+70,h=84*mapSize+70;
 const modalOpen=shop||saveOpen||confirmReset||confirmRetreat||!!m.result;
 return <section className="hb-game" data-hb-ready="true" data-hb-phase={m.result||(!game?'camp':m.busy?'busy':'battle')} aria-label="六角远征"><div inert={modalOpen}>
  <header className="hb-heading"><div><span>HEXA BATTLE · 完整规则</span><h3>带上生还者，向深处前进</h3></div><b>无尽远征 · 无编号关卡</b></header>
  <div className="hb-summary"><span>深入第 <b>{m.campaign.depth+1}</b> 层</span><span>金币 <b>{m.campaign.money}</b></span><span>胜场 <b>{m.campaign.wins}</b></span><span>{game?`回合 ${game.epoch+1}`:`队伍 ${m.campaign.party.length} 人`}</span></div>
  <p className="hb-status" role="status">{m.message}</p>
  {!m.storageAvailable&&<p role="alert">浏览器无法保存，请用导出备份保留远征。</p>}
  {!game?<div className="hb-camp"><div className="hb-camp-art" aria-hidden="true">⬡ <span>营地</span> ⬡</div><h4>整备队伍</h4><p>每场胜利获得金币，只有生还者进入下一层。全员恢复后再次出发。失败可从出发队伍重试。</p><div className="hb-roster">{m.campaign.party.map((k,i)=>{const unit=allTypes.find(u=>keyOf(u)===k)!;return <article key={i}><UnitCard unit={unit}/></article>;})}</div><div className="hb-controls"><button disabled={disabled} onClick={()=>m.start()}>开始战斗</button><button disabled={disabled} onClick={()=>{setCart([]);setShop(true);}}>招募队员</button><button disabled={disabled} onClick={()=>setConfirmReset(true)}>重置远征</button></div></div>:<>
   <div className="hb-battle-layout"><div className="hb-map-column"><p className="hb-map-help">绿队 / 红队 · 高亮格可移动，橙色格为技能目标。手机可拖动地图。</p><div ref={board} className="hb-board" aria-label="可滚动六角战场"><svg width={w} height={h} viewBox={`${-w/2} ${-h/2} ${w} ${h}`} aria-label="战场地图" role="group">{game.map.cells.map(cell=>{const at=position(cell.pos.q,cell.pos.r),u=cell.thing instanceof Unit?cell.thing:null,id=cell.pos.toString(),can=targets.has(id),move=moves.has(id),own=u?.factionId===m.player;return <g key={id} transform={`translate(${at.x},${at.y})`} className={`hb-cell ${cell.terrain===Terrain.Pit?'hb-pit':''} ${move?'hb-move':''} ${can?'hb-target':''} ${u?.id===m.selected?'hb-selected':''}`} data-hex={id} data-unit={u?.id} data-side={u?(own?'player':'enemy'):undefined} role="button" tabIndex={disabled?-1:0} aria-label={`${cell.pos.q},${cell.pos.r} ${u?`${own?'我方':'敌方'}${name(u.type.name)} 生命${u.hp}`:cell.terrain===Terrain.Pit?'深坑':'空地'}`} onClick={()=>void m.cell(cell.pos.q,cell.pos.r)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();void m.cell(cell.pos.q,cell.pos.r);}else{const keys:Record<string,[number,number]>={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};const d=keys[e.key];if(d){e.preventDefault();board.current?.querySelector<SVGGElement>(`[data-hex="${cell.pos.q+d[0]},${cell.pos.r+d[1]}"]`)?.focus();}}}}><polygon points={points}/>{u?<><circle r={19} className={own?'hb-friendly':'hb-hostile'}/><text y={4} className="hb-token">{name(u.type.name).slice(0,1)}</text><rect x={-19} y={21} width={38} height={4} fill="#d0d8d2"/><rect x={-19} y={21} width={38*u.hp/u.type.hp} height={4} fill={own?'#25855b':'#b64a47'}/>{u.actionPerformed&&<text x={15} y={-11} className="hb-acted">✓</text>}</>:cell.terrain===Terrain.Pit?<path d="M-10,-5 0,10 10,-5Z"/>:null}</g>;})}</svg></div><div className="hb-controls"><button disabled={disabled||!!m.result} onClick={()=>m.nextUnit()}>下一队员</button><button disabled={disabled||!!m.result} onClick={()=>void m.endTurn()}>结束回合</button><button disabled={disabled||!!m.result} onClick={()=>setConfirmRetreat(true)}>撤回营地</button></div></div>
   <aside className="hb-inspector">{selected?<><h4>{selected.factionId===m.player?'我方':'敌方'} · {name(selected.type.name)}</h4><p>生命 {selected.hp}/{selected.type.hp} · 移动 {selected.mp} · 魔力 {selected.mana} · 抗性 {selected.resistance}</p><p>{[...selected.status].map(([s,n])=>`${statuses[s]}(${n})`).join(' · ')||'状态正常'}{selected.type.traits?.length?' · 可飞越深坑':''}</p>{selected.factionId===m.player?<div className="hb-actions">{selected.actions.map((a,i)=><button key={i} data-action={i} className={m.action===i?'selected':''} disabled={disabled||!a.canExecute||!!m.result} onClick={()=>m.selectAction(i)}>{i+1}. {name(a.name)}{a.manaCost?` · 魔力${a.manaCost}`:''}</button>)}</div>:<p>观察敌方技能与射程，点击我方单位继续。</p>}<p>{action?actionHelp[action.name]:selected.actionPerformed?'本回合已使用技能。':'先点高亮格移动，再选技能与目标。'}</p>{action&&<p className="hb-warning">范围技能与直接攻击都可能伤到队友，选目标前请确认。</p>}</>:<><h4>选择一个单位</h4><p>点击棋子查看状态。选中我方单位后，可以移动，再执行一次技能。</p></>}</aside></div>
  </>}
  <div className="hb-controls"><button disabled={disabled||!!m.result} onClick={()=>{setSaveText(m.export());setSaveOpen(true);}}>存档与导入</button></div>
  {paused&&<div className="hb-pause">已暂停，敌我行动均已停止。请使用上方“继续游戏”。</div>}</div>
  {modalOpen&&<div className="hb-modal-backdrop" aria-hidden="true"/>}
  {m.result&&<div className="hb-dialog" role="dialog" aria-modal="true" aria-label="战斗结果"><h4>{m.result==='win'?'战斗胜利':'队伍倒下了'}</h4><p>{m.result==='win'?'确认后领取原作奖励，生还者进入下一层。':'出发前的队伍仍保留，可以重新规划战术。'}</p><button disabled={disabled} onClick={()=>m.acceptResult()}>返回营地</button></div>}
  {shop&&<div className="hb-dialog" role="dialog" aria-modal="true" aria-label="招募队员"><h4>招募队员</h4><p>可用 {m.campaign.money} 金币 · 已选 {cartCost} 金币</p><div className="hb-shop">{allTypes.map(u=><button key={u.name} disabled={disabled||cartCost+u.cost>m.campaign.money} onClick={()=>setCart([...cart,keyOf(u)])}><UnitCard unit={u}/><b>{u.cost} 金币</b></button>)}</div><p>已选：{cart.map(k=>name(allTypes.find(u=>keyOf(u)===k)!.name)).join('、')||'无'}</p><div className="hb-controls"><button disabled={disabled||!cart.length} onClick={()=>{if(m.purchase(cart))setShop(false);}}>确认招募</button><button onClick={()=>setCart([])}>清空选择</button><button onClick={()=>setShop(false)}>取消</button></div></div>}
  {saveOpen&&<div className="hb-dialog" role="dialog" aria-modal="true" aria-label="远征存档"><h4>远征存档</h4><p>可复制当前存档备份，或粘贴此前的本游戏存档。无效内容不会替换进度。</p><textarea aria-label="远征存档内容" value={saveText} onChange={e=>setSaveText(e.target.value)}/><div className="hb-controls"><button disabled={disabled} onClick={()=>{m.import(saveText);setSaveOpen(false);}}>导入存档</button><button onClick={()=>setSaveOpen(false)}>关闭存档</button></div></div>}
  {(confirmReset||confirmRetreat)&&<div className="hb-dialog" role="dialog" aria-modal="true" aria-label="确认远征操作"><h4>{confirmReset?'重新开始远征？':'离开本次战斗？'}</h4><p>{confirmReset?'本游戏的队伍、金币和深度会重置。其他游戏存档不受影响。':'当前战斗会结束，营地仍保留出发时的队伍。'}</p><div className="hb-controls"><button disabled={disabled} onClick={()=>{if(confirmReset)m.reset();else m.retreat();setConfirmReset(false);setConfirmRetreat(false);}}>确认</button><button onClick={()=>{setConfirmReset(false);setConfirmRetreat(false);}}>取消</button></div></div>}
  <details className="hb-help"><summary>完整规则、操作与来源</summary><p>每名队员在回合开始恢复移动力，可以先走路再使用一次技能；技能会用完剩余移动力。全歼红队获胜，绿队全部倒下则失败。飞行单位能越过深坑。燃烧、睡眠、减速与防御按原作回合计时。</p><p>弓手、狂战士、投石车、牧师、骑兵、骑士、法师和战士均可招募；八种怪物与十三类技能完整保留。金币奖励、原AI与递进地图预算沿用固定原作。没有人为补出的有限关卡。</p><p>键盘：空格选择下一个队员，数字1–9选技能；格子聚焦时用方向键选择邻格，回车操作。每次稳定行动自动保存；离开时若敌人尚在行动，将保留最近完整行动的存档。</p><p>改编自 Giacomo Tagliabue 的 Hexa Battle，固定 fe97718，MIT。原游戏图标未再分发，本界面的汉字棋子与六角图形为本站重绘。<a href="./hexa-battle-LICENSE.txt" target="_blank" rel="noreferrer">原作许可证</a>。</p></details>
 </section>;
}
