// SPDX-License-Identifier: GPL-3.0-only
import {useEffect,useRef,useState} from "react";
import type {GameProps} from "../lib/types";
import {hexapawnLevels,hexHint,hexInitial,hexMoves,hexPlayTurn,hexSquare,type HexState} from "./hexapawnLogic";
import "./hexapawn.css";
export default function Hexapawn(props:GameProps){return <Round key={`${props.level}:${props.resetToken}`} {...props}/>;}
function Round({level,paused,hintToken,undoToken,onStatus,onComplete}:GameProps){
 const config=hexapawnLevels[level]??hexapawnLevels[0];const[state,setState]=useState(()=>hexInitial(config)),[history,setHistory]=useState<HexState[]>([]),[selected,setSelected]=useState<number|null>(null),[hint,setHint]=useState<ReturnType<typeof hexHint>|null>(null),[feedback,setFeedback]=useState("选一枚绿色小兵，再选落点。绿色向上，棕色向下。");const seenHint=useRef(hintToken),seenUndo=useRef(undoToken),done=useRef(false);const won=state.winner==="green",locked=paused||state.winner!==null,legal=state.winner?[]:hexMoves(state.board,config.size,"green");
 useEffect(()=>{onStatus("你执绿色向上：直走一格不吃子，斜前方一格只吃对手。先冲线，或让对手无合法着法，即获胜。");},[]);
 useEffect(()=>{if(seenHint.current===hintToken)return;seenHint.current=hintToken;if(paused||won)return;const next=hexHint(config,state);setHint(next);setSelected(null);setFeedback(next.text);onStatus(next.text);},[hintToken,paused,won,config,state,onStatus]);
 useEffect(()=>{if(seenUndo.current===undoToken)return;seenUndo.current=undoToken;if(paused||won)return;if(history.length){setState(history[history.length-1]);setHistory(history.slice(0,-1));setSelected(null);setHint(null);setFeedback("已撤销一整轮：你的着法和棕色的回应都已恢复。");}else setFeedback("还没有完整回合可以撤销。");},[undoToken,paused,won,history]);
 useEffect(()=>{if(won&&!paused&&!done.current){done.current=true;onStatus("绿色获胜！小兵冲线，或让对手没有合法着法。");onComplete();}},[won,paused,onStatus,onComplete]);
 function pick(cell:number){if(locked)return;if(state.board[cell]==="green"){setSelected(selected===cell?null:cell);setHint(null);setFeedback(legal.some(m=>m.from===cell)?"绿色已选。亮点可以直走，斜前方的棕色可以吃。":"这枚小兵被挡住了，没有合法落点；选另一枚试试。");return;}if(selected===null){setFeedback("请先选择一枚绿色小兵。");return;}const next=hexPlayTurn(config,state,{from:selected,to:cell});if(!next){setFeedback("只能向前直走到空格，或斜前方吃对手；不能横走、后退或斜走到空格。");return;}setHistory([...history,state]);setState(next);setSelected(null);setHint(null);setFeedback(next.winner==="brown"?"棕色获胜了。可撤销整轮，想想怎样防守冲线。":next.lastBrown?`棕色回应：${hexSquare(next.lastBrown.from,config.size)} → ${hexSquare(next.lastBrown.to,config.size)}。现在轮到绿色。`:"这一手结束了棋局。");}
 return <div className="puzzle-layout hp-game" data-hexapawn-state={JSON.stringify(state)} data-hexapawn-won={won} data-hexapawn-winner={state.winner??"none"} data-hexapawn-moves={history.length}><section className="hp-workbench" aria-label="小兵冲线棋盘"><header><span className="mini-label">HEXAPAWN · {config.title}</span><strong>{history.length} 轮</strong></header><div className="hp-direction"><span>↑ 绿色的终点</span><span>棕色向下 ↓</span></div>
 <div className="hp-board" style={{gridTemplateColumns:`repeat(${config.size},1fr)`}}>{state.board.map((piece,i)=>{const target=selected!==null&&legal.some(m=>m.from===selected&&m.to===i),hinted=hint?.move?.from===i||hint?.move?.to===i;return <button key={i} data-hex-cell={i} className={`hp-cell ${(Math.floor(i/config.size)+i%config.size)%2?"hp-dark":""} ${selected===i?"hp-selected":""} ${target?"hp-target":""} ${hinted?"hp-hinted":""} ${state.lastBrown?.to===i?"hp-last":""}`} disabled={locked} onClick={()=>pick(i)} aria-pressed={selected===i} aria-label={`${hexSquare(i,config.size)}，${piece==="green"?"绿色小兵":piece==="brown"?"棕色小兵":"空格"}${target?"，可走落点":""}`}><small>{hexSquare(i,config.size)}</small>{piece?<span className={`hp-pawn hp-${piece}`} aria-hidden="true"><svg viewBox="0 0 64 76"><circle cx="32" cy="15" r="10"/><path d="M23 29h18l-3 14 9 18H17l9-18z"/><path d="M15 64h34v7H15z"/></svg><b>{piece==="green"?"↑":"↓"}</b></span>:target?<span className="hp-dot" aria-hidden="true"/>:null}</button>;})}</div>
 <div className="hp-legend"><span><i className="hp-green-dot"/> 你 · 绿色向上</span><span><i className="hp-brown-dot"/> 对手 · 棕色向下</span></div><p className="hp-feedback" role="status">{paused?"已暂停，双方棋盘已锁定。":won?"绿色获胜！这片花园向你开放。":state.winner==="brown"?"棕色获胜。可以撤销一整轮，重新规划。":feedback}</p>
 </section><aside className="game-notes hp-notes"><span className="mini-label">前进 · 斜吃 · 先手与阻挡</span><h3>小兵也能下大棋。</h3><p>{config.lesson}</p><ol><li>绿色向上，棕色向下；每次只能直走一格到空格。</li><li>只有斜前方一格有对手时才能斜吃。不能直吃、横走、后退、起步两格或吃过路兵。</li><li>任何小兵到达对岸立即获胜；轮到一方而没有合法着法时，该方输。吃光对手也符合无着法规则。</li></ol><p>你先走，电脑立即回应。电脑对这些小棋盘作完整搜索，优先尽快赢；必败时尽量拖延，不会故意让棋。撤销一次会同时撤回双方的一整轮。</p><p>8 个原创战术局面，使用 3×3 或 4×4 棋盘，不是完整国际象棋。没有将军、王或平局；提示从当前局面分析，失误后不会假称仍能强制赢。</p><p>点按棋子再点落点，或 Tab + Enter / 空格。金色框为提示，落点圆点为合法直走，棕色最近落点有小边框。</p></aside></div>;
}
