// SPDX-License-Identifier: GPL-3.0-only
import {useEffect,useRef,useState} from "react";
import type {GameProps} from "../lib/types";
import {mazeChaseLevels,mazeWorld,mazeMoves,initialMazeChase,moveMazeChase,mazeChaseWon,mazeChaseHint} from "./mazeChaseLogic";
import type {MazeChaseState} from "./mazeChaseLogic";
import "./mazeChase.css";
export default function MazeChase(props:GameProps){return <Round key={`${props.level}:${props.resetToken}`} {...props}/>;}
function Round({level,paused,hintToken,undoToken,onComplete,onStatus}:GameProps){
 const config=mazeChaseLevels[level]??mazeChaseLevels[0],world=mazeWorld(config);const [state,setState]=useState(()=>initialMazeChase(config)),[history,setHistory]=useState<MazeChaseState[]>([]),[hint,setHint]=useState<ReturnType<typeof mazeChaseHint>|null>(null);const done=useRef(false),seenHint=useRef(hintToken),seenUndo=useRef(undoToken);const won=mazeChaseWon(config,state),locked=paused||won||state.caught;
 useEffect(()=>{onStatus("每走一步或等待一回合，守卫也沿标好的路线走一步。收齐星豆再到出口，不能与守卫碰面或交换位置。");},[]);
 useEffect(()=>{if(hintToken===seenHint.current)return;seenHint.current=hintToken;if(locked)return;const h=mazeChaseHint(config,state);setHint(h);onStatus(h.text);},[hintToken,locked,state,config,onStatus]);
 useEffect(()=>{if(undoToken===seenUndo.current)return;seenUndo.current=undoToken;if(locked)return;if(history.length){setState(history.at(-1)!);setHistory(history.slice(0,-1));setHint(null);onStatus("已撤销一回合，守卫与星豆一起恢复。");}else onStatus("还没有行动可以撤销。");},[undoToken,locked,history,onStatus]);
 useEffect(()=>{if(won&&!paused&&!done.current){done.current=true;onStatus("星豆全部收齐，安全到家！");onComplete();}},[won,paused,onComplete,onStatus]);
 function move(m:number){if(locked)return;const n=moveMazeChase(config,state,m);if(!n){onStatus("这里是花篱，回合没有推进。");return;}setHistory([...history,state]);setState(n);setHint(null);if(n.caught)onStatus("碰到守卫了。这次旅程结束，请重来。");}
 return <div className="puzzle-layout mch-game" data-mch-state={JSON.stringify(state)} data-mch-won={won} data-mch-caught={state.caught}>
 <section className="mch-workbench"><header><span className="mini-label">星豆迷宫 · {config.title}</span><b>回合 {state.turn}</b></header><div className="mch-summary"><span>星豆 {world.pellets.filter((_,i)=>state.mask&(1<<i)).length}/{world.pellets.length}</span><span>出口 {state.mask===(1<<world.pellets.length)-1?"已开启":"需收齐星豆"}</span></div>
 <div className="mch-board" style={{gridTemplateColumns:`repeat(${world.width},1fr)`}} tabIndex={locked?-1:0} role="group" aria-label="星豆迷宫，方向键移动，空格等待" onKeyDown={e=>{if(e.altKey||e.ctrlKey||e.metaKey||e.repeat)return;const m=mazeMoves.findIndex(d=>d.key===e.key);if(m>=0){e.preventDefault();move(m);}}}>
 {world.cells.map((c,i)=>{const guard=config.patrols.findIndex(p=>p[state.turn%p.length]===i),next=config.patrols.findIndex(p=>p[(state.turn+1)%p.length]===i),pellet=world.pellets.indexOf(i);return <div key={i} className={`mch-cell ${c==="#"?"mch-wall":"mch-floor"} ${next>=0?"mch-next":""}`} aria-label={`${Math.floor(i/world.width)+1}行${i%world.width+1}列 ${i===state.cell?"你 ":""}${guard>=0?`守卫${guard+1} `:""}${next>=0?"下一回合守卫到这里 ":""}${c==="#"?"花篱":c==="E"?"出口":pellet>=0&&!(state.mask&(1<<pellet))?"星豆":"通道"}`}>{i===state.cell?<span className="mch-player">{state.caught?"×":"●"}</span>:guard>=0?<span className="mch-guard">◆<small>{guard+1}</small></span>:c==="E"?<span className="mch-exit">⌂</span>:pellet>=0&&!(state.mask&(1<<pellet))?<span className="mch-pellet">✦</span>:null}{next>=0&&c!=="#"?<span className="mch-shadow">{next+1}</span>:null}</div>;})}</div>
 <div className="mch-controls">{mazeMoves.map((d,i)=><button key={d.name} data-mch-move={i} disabled={locked} className={hint?.move===i?"mch-hinted":""} onClick={()=>move(i)} aria-label={d.name}>{d.icon}<small>{d.name}</small></button>)}</div><p className="mch-feedback" role="status">{paused?"已暂停。":won?"每颗星豆都带回家了！":state.caught?"被守卫碰到了，请重来。":hint?.text??"◆ 是守卫；虚线小圈标出它下一回合的位置。"}</p></section>
 <aside className="game-notes"><span className="mini-label">路线 · 时机 · 回合制追逐</span><h3>看清下一步，再出发。</h3><p>{config.lesson}</p><ol><li>方向键或下方箭头移动一格。碰墙不消耗回合。</li><li>守卫按固定路线巡逻，不会随机追人。空格或“等待”也会让守卫前进一步。</li><li>同格相撞、迎面交换位置都会失败。集齐所有星豆后进入 ⌂ 出口才算成功。</li></ol><p>没有倒计时。提示从当前局面进行有界搜索；若找不到完整路线会明确说明。暂停和结束时方向控制锁定。失败请重来。</p><details><summary>查看巡逻路线</summary>{config.patrols.map((p,i)=><p key={i}>守卫 {i+1}：{p.map(n=>`${Math.floor(n/world.width)+1},${n%world.width+1}`).join(" → ")}，然后循环。</p>)}</details></aside></div>;
}
