// SPDX-License-Identifier: MIT
import type { MemoryRouteLevel } from "./memoryRoutesLogic";
/** Each public walk is authored separately; no answer certificate is imported by runtime. */
export const memoryRoutesLevels: readonly MemoryRouteLevel[] = [
  {
    id: "mr-01",
    title: "沿着花径",
    lesson: "先记起点，再记方向。第一条路线沿着第一行走过三站。",
    size: 3,
    start: 0,
    walk: ["E", "E"],
  },
  {
    id: "mr-02",
    title: "拐一个弯",
    lesson: "把四站分成“向下、向右”两小段，比逐格背诵更容易。",
    size: 3,
    start: 0,
    walk: ["S", "S", "E"],
  },
  {
    id: "mr-03",
    title: "小小阶梯",
    lesson: "上下与左右交替，像走一段小楼梯。",
    size: 3,
    start: 6,
    walk: ["E", "N", "E", "N"],
  },
  {
    id: "mr-04",
    title: "绕过池塘",
    lesson: "路线沿着池塘外侧连续转弯，留意终点在起点的哪一边。",
    size: 3,
    start: 3,
    walk: ["N", "E", "E", "S", "S"],
  },
  {
    id: "mr-05",
    title: "原路回来",
    lesson: "有些格子会重复到访。每次经过都算一站，同一格会标出多个站号。",
    size: 3,
    start: 6,
    walk: ["N", "N", "E", "W", "S"],
  },
  {
    id: "mr-06",
    title: "中心路口",
    lesson: "中心是路线的锚点：先到左边，再穿过中心到右边。",
    size: 3,
    start: 1,
    walk: ["S", "W", "E", "E", "W", "S"],
  },
  {
    id: "mr-07",
    title: "横穿新花园",
    lesson: "花园扩大了。把长直线和折返分开记，不必一下记住整条路线。",
    size: 4,
    start: 12,
    walk: ["N", "N", "N", "E", "S", "S"],
  },
  {
    id: "mr-08",
    title: "方形小回环",
    lesson: "记住一个小方环，再记住离开环的位置。回到原点也要再点一次。",
    size: 4,
    start: 5,
    walk: ["E", "S", "W", "N", "W", "N", "E"],
  },
  {
    id: "mr-09",
    title: "两段折线",
    lesson: "两段折线方向相似。用“向右两步，再向下”作为记忆小块。",
    size: 4,
    start: 0,
    walk: ["E", "E", "S", "W", "S", "E", "S"],
  },
  {
    id: "mr-10",
    title: "桥上折返",
    lesson: "去程和回程共用一座桥。把中间的回头位置当作分界。",
    size: 4,
    start: 12,
    walk: ["N", "E", "E", "N", "S", "W", "W", "S"],
  },
  {
    id: "mr-11",
    title: "双叶花径",
    lesson: "两个小环在同一个路口相遇。记清先绕哪一片叶子。",
    size: 4,
    start: 5,
    walk: ["N", "E", "S", "W", "S", "W", "N", "E"],
  },
  {
    id: "mr-12",
    title: "花园回信",
    lesson: "先绕外侧，再转入中心，最后折返一站。用转弯和重复地点给路线分段。",
    size: 4,
    start: 12,
    walk: ["E", "E", "N", "N", "W", "W", "S", "E", "W"],
  },
];
