import type { PancakeLevel } from './pancakeLogic';
// Generated by scripts/pancake/generate.mjs. Certificates stay in docs/.
export const pancakeChapters = [
  {
    "id": "first-flip",
    "title": "认准翻面范围",
    "lesson": "目标是小在上、大在下。点第几层，就会把它和上面所有煎饼一起翻过来。先看虚线框，再确认。",
    "count": 8
  },
  {
    "id": "overlapping-flips",
    "title": "两次翻转相遇",
    "lesson": "一次翻转会改动一整段顺序。试着先把想放下去的煎饼带到顶端，再选新的层数。",
    "count": 12
  },
  {
    "id": "place-largest",
    "title": "把大饼送到底",
    "lesson": "先把最大的一片翻到顶部，再翻整叠，就能把它送到底部。这个方法总能整理好，但不一定最省步。",
    "count": 18
  },
  {
    "id": "keep-neighbors",
    "title": "留住好邻居",
    "lesson": "连续相邻的大小可以当作一组来观察。翻转可能拆散它们，也可能让两组刚好接上。",
    "count": 24
  },
  {
    "id": "compare-routes",
    "title": "换条路线试试",
    "lesson": "比较不同的首翻。眼前整齐不一定离目标更近；撤销和当前局面提示都能帮你检验想法。",
    "count": 26
  },
  {
    "id": "whole-stack",
    "title": "整叠的计划",
    "lesson": "8 片有 40,320 种排列。先整理成功，再挑战开局的最少步数；没有限时，超步也能通关。",
    "count": 32
  }
];
export const pancakeLevels: PancakeLevel[] = [
  {
    "id": "pancake-001",
    "title": "认准翻面范围 · 1",
    "chapter": 0,
    "stack": [
      2,
      1,
      3
    ],
    "minMoves": 1
  },
  {
    "id": "pancake-002",
    "title": "认准翻面范围 · 2",
    "chapter": 0,
    "stack": [
      3,
      2,
      1
    ],
    "minMoves": 1
  },
  {
    "id": "pancake-003",
    "title": "认准翻面范围 · 3",
    "chapter": 0,
    "stack": [
      2,
      3,
      1
    ],
    "minMoves": 2
  },
  {
    "id": "pancake-004",
    "title": "认准翻面范围 · 4",
    "chapter": 0,
    "stack": [
      3,
      1,
      2
    ],
    "minMoves": 2
  },
  {
    "id": "pancake-005",
    "title": "认准翻面范围 · 5",
    "chapter": 0,
    "stack": [
      1,
      3,
      2
    ],
    "minMoves": 3
  },
  {
    "id": "pancake-006",
    "title": "认准翻面范围 · 6",
    "chapter": 0,
    "stack": [
      4,
      3,
      2,
      1
    ],
    "minMoves": 1
  },
  {
    "id": "pancake-007",
    "title": "认准翻面范围 · 7",
    "chapter": 0,
    "stack": [
      3,
      4,
      2,
      1
    ],
    "minMoves": 2
  },
  {
    "id": "pancake-008",
    "title": "认准翻面范围 · 8",
    "chapter": 0,
    "stack": [
      2,
      4,
      1,
      3
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-009",
    "title": "两次翻转相遇 · 1",
    "chapter": 1,
    "stack": [
      4,
      3,
      1,
      2
    ],
    "minMoves": 2
  },
  {
    "id": "pancake-010",
    "title": "两次翻转相遇 · 2",
    "chapter": 1,
    "stack": [
      4,
      1,
      2,
      3
    ],
    "minMoves": 2
  },
  {
    "id": "pancake-011",
    "title": "两次翻转相遇 · 3",
    "chapter": 1,
    "stack": [
      2,
      3,
      4,
      1
    ],
    "minMoves": 2
  },
  {
    "id": "pancake-012",
    "title": "两次翻转相遇 · 4",
    "chapter": 1,
    "stack": [
      2,
      1,
      4,
      3
    ],
    "minMoves": 3
  },
  {
    "id": "pancake-013",
    "title": "两次翻转相遇 · 5",
    "chapter": 1,
    "stack": [
      1,
      3,
      4,
      2
    ],
    "minMoves": 3
  },
  {
    "id": "pancake-014",
    "title": "两次翻转相遇 · 6",
    "chapter": 1,
    "stack": [
      1,
      4,
      2,
      3
    ],
    "minMoves": 3
  },
  {
    "id": "pancake-015",
    "title": "两次翻转相遇 · 7",
    "chapter": 1,
    "stack": [
      1,
      2,
      4,
      3
    ],
    "minMoves": 3
  },
  {
    "id": "pancake-016",
    "title": "两次翻转相遇 · 8",
    "chapter": 1,
    "stack": [
      1,
      4,
      3,
      2
    ],
    "minMoves": 3
  },
  {
    "id": "pancake-017",
    "title": "两次翻转相遇 · 9",
    "chapter": 1,
    "stack": [
      2,
      4,
      3,
      1
    ],
    "minMoves": 3
  },
  {
    "id": "pancake-018",
    "title": "两次翻转相遇 · 10",
    "chapter": 1,
    "stack": [
      3,
      2,
      4,
      1
    ],
    "minMoves": 3
  },
  {
    "id": "pancake-019",
    "title": "两次翻转相遇 · 11",
    "chapter": 1,
    "stack": [
      4,
      2,
      3,
      1
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-020",
    "title": "两次翻转相遇 · 12",
    "chapter": 1,
    "stack": [
      3,
      1,
      4,
      2
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-021",
    "title": "把大饼送到底 · 1",
    "chapter": 2,
    "stack": [
      2,
      1,
      4,
      5,
      3
    ],
    "minMoves": 3
  },
  {
    "id": "pancake-022",
    "title": "把大饼送到底 · 2",
    "chapter": 2,
    "stack": [
      5,
      1,
      2,
      4,
      3
    ],
    "minMoves": 3
  },
  {
    "id": "pancake-023",
    "title": "把大饼送到底 · 3",
    "chapter": 2,
    "stack": [
      1,
      2,
      5,
      4,
      3
    ],
    "minMoves": 3
  },
  {
    "id": "pancake-024",
    "title": "把大饼送到底 · 4",
    "chapter": 2,
    "stack": [
      4,
      3,
      2,
      5,
      1
    ],
    "minMoves": 3
  },
  {
    "id": "pancake-025",
    "title": "把大饼送到底 · 5",
    "chapter": 2,
    "stack": [
      2,
      3,
      5,
      1,
      4
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-026",
    "title": "把大饼送到底 · 6",
    "chapter": 2,
    "stack": [
      4,
      1,
      5,
      3,
      2
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-027",
    "title": "把大饼送到底 · 7",
    "chapter": 2,
    "stack": [
      1,
      2,
      4,
      5,
      3
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-028",
    "title": "把大饼送到底 · 8",
    "chapter": 2,
    "stack": [
      2,
      1,
      5,
      4,
      3
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-029",
    "title": "把大饼送到底 · 9",
    "chapter": 2,
    "stack": [
      4,
      3,
      5,
      1,
      2
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-030",
    "title": "把大饼送到底 · 10",
    "chapter": 2,
    "stack": [
      1,
      3,
      5,
      4,
      2
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-031",
    "title": "把大饼送到底 · 11",
    "chapter": 2,
    "stack": [
      2,
      5,
      4,
      1,
      3
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-032",
    "title": "把大饼送到底 · 12",
    "chapter": 2,
    "stack": [
      1,
      5,
      4,
      2,
      3
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-033",
    "title": "把大饼送到底 · 13",
    "chapter": 2,
    "stack": [
      5,
      2,
      4,
      1,
      3
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-034",
    "title": "把大饼送到底 · 14",
    "chapter": 2,
    "stack": [
      1,
      3,
      2,
      5,
      4
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-035",
    "title": "把大饼送到底 · 15",
    "chapter": 2,
    "stack": [
      1,
      3,
      5,
      2,
      4
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-036",
    "title": "把大饼送到底 · 16",
    "chapter": 2,
    "stack": [
      3,
      5,
      1,
      4,
      2
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-037",
    "title": "把大饼送到底 · 17",
    "chapter": 2,
    "stack": [
      4,
      2,
      5,
      1,
      3
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-038",
    "title": "把大饼送到底 · 18",
    "chapter": 2,
    "stack": [
      2,
      4,
      3,
      5,
      1
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-039",
    "title": "留住好邻居 · 1",
    "chapter": 3,
    "stack": [
      6,
      3,
      1,
      2,
      4,
      5
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-040",
    "title": "留住好邻居 · 2",
    "chapter": 3,
    "stack": [
      6,
      3,
      2,
      5,
      4,
      1
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-041",
    "title": "留住好邻居 · 3",
    "chapter": 3,
    "stack": [
      2,
      3,
      6,
      1,
      4,
      5
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-042",
    "title": "留住好邻居 · 4",
    "chapter": 3,
    "stack": [
      1,
      4,
      5,
      6,
      3,
      2
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-043",
    "title": "留住好邻居 · 5",
    "chapter": 3,
    "stack": [
      6,
      5,
      3,
      4,
      2,
      1
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-044",
    "title": "留住好邻居 · 6",
    "chapter": 3,
    "stack": [
      5,
      6,
      3,
      2,
      4,
      1
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-045",
    "title": "留住好邻居 · 7",
    "chapter": 3,
    "stack": [
      2,
      6,
      5,
      4,
      1,
      3
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-046",
    "title": "留住好邻居 · 8",
    "chapter": 3,
    "stack": [
      2,
      1,
      3,
      6,
      5,
      4
    ],
    "minMoves": 4
  },
  {
    "id": "pancake-047",
    "title": "留住好邻居 · 9",
    "chapter": 3,
    "stack": [
      5,
      3,
      4,
      6,
      1,
      2
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-048",
    "title": "留住好邻居 · 10",
    "chapter": 3,
    "stack": [
      1,
      3,
      2,
      6,
      4,
      5
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-049",
    "title": "留住好邻居 · 11",
    "chapter": 3,
    "stack": [
      2,
      4,
      3,
      6,
      1,
      5
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-050",
    "title": "留住好邻居 · 12",
    "chapter": 3,
    "stack": [
      4,
      5,
      2,
      6,
      3,
      1
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-051",
    "title": "留住好邻居 · 13",
    "chapter": 3,
    "stack": [
      4,
      6,
      1,
      2,
      5,
      3
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-052",
    "title": "留住好邻居 · 14",
    "chapter": 3,
    "stack": [
      3,
      1,
      6,
      5,
      4,
      2
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-053",
    "title": "留住好邻居 · 15",
    "chapter": 3,
    "stack": [
      5,
      4,
      1,
      6,
      3,
      2
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-054",
    "title": "留住好邻居 · 16",
    "chapter": 3,
    "stack": [
      5,
      2,
      6,
      1,
      3,
      4
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-055",
    "title": "留住好邻居 · 17",
    "chapter": 3,
    "stack": [
      2,
      5,
      4,
      6,
      1,
      3
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-056",
    "title": "留住好邻居 · 18",
    "chapter": 3,
    "stack": [
      2,
      6,
      1,
      4,
      3,
      5
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-057",
    "title": "留住好邻居 · 19",
    "chapter": 3,
    "stack": [
      1,
      4,
      6,
      2,
      5,
      3
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-058",
    "title": "留住好邻居 · 20",
    "chapter": 3,
    "stack": [
      1,
      4,
      2,
      6,
      3,
      5
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-059",
    "title": "留住好邻居 · 21",
    "chapter": 3,
    "stack": [
      5,
      1,
      6,
      3,
      2,
      4
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-060",
    "title": "留住好邻居 · 22",
    "chapter": 3,
    "stack": [
      4,
      2,
      6,
      3,
      1,
      5
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-061",
    "title": "留住好邻居 · 23",
    "chapter": 3,
    "stack": [
      5,
      1,
      3,
      6,
      2,
      4
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-062",
    "title": "留住好邻居 · 24",
    "chapter": 3,
    "stack": [
      4,
      6,
      2,
      5,
      1,
      3
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-063",
    "title": "换条路线试试 · 1",
    "chapter": 4,
    "stack": [
      1,
      2,
      3,
      7,
      4,
      6,
      5
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-064",
    "title": "换条路线试试 · 2",
    "chapter": 4,
    "stack": [
      1,
      2,
      7,
      3,
      6,
      5,
      4
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-065",
    "title": "换条路线试试 · 3",
    "chapter": 4,
    "stack": [
      7,
      5,
      3,
      2,
      1,
      4,
      6
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-066",
    "title": "换条路线试试 · 4",
    "chapter": 4,
    "stack": [
      4,
      5,
      2,
      6,
      7,
      3,
      1
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-067",
    "title": "换条路线试试 · 5",
    "chapter": 4,
    "stack": [
      4,
      7,
      1,
      3,
      2,
      5,
      6
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-068",
    "title": "换条路线试试 · 6",
    "chapter": 4,
    "stack": [
      6,
      4,
      7,
      5,
      3,
      2,
      1
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-069",
    "title": "换条路线试试 · 7",
    "chapter": 4,
    "stack": [
      5,
      4,
      1,
      2,
      7,
      6,
      3
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-070",
    "title": "换条路线试试 · 8",
    "chapter": 4,
    "stack": [
      4,
      3,
      5,
      6,
      1,
      7,
      2
    ],
    "minMoves": 5
  },
  {
    "id": "pancake-071",
    "title": "换条路线试试 · 9",
    "chapter": 4,
    "stack": [
      5,
      7,
      4,
      2,
      1,
      3,
      6
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-072",
    "title": "换条路线试试 · 10",
    "chapter": 4,
    "stack": [
      7,
      2,
      6,
      3,
      5,
      4,
      1
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-073",
    "title": "换条路线试试 · 11",
    "chapter": 4,
    "stack": [
      7,
      5,
      2,
      1,
      6,
      4,
      3
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-074",
    "title": "换条路线试试 · 12",
    "chapter": 4,
    "stack": [
      4,
      1,
      7,
      5,
      2,
      3,
      6
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-075",
    "title": "换条路线试试 · 13",
    "chapter": 4,
    "stack": [
      4,
      5,
      7,
      2,
      3,
      1,
      6
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-076",
    "title": "换条路线试试 · 14",
    "chapter": 4,
    "stack": [
      4,
      1,
      6,
      7,
      3,
      5,
      2
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-077",
    "title": "换条路线试试 · 15",
    "chapter": 4,
    "stack": [
      1,
      6,
      5,
      4,
      2,
      7,
      3
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-078",
    "title": "换条路线试试 · 16",
    "chapter": 4,
    "stack": [
      4,
      1,
      6,
      3,
      2,
      7,
      5
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-079",
    "title": "换条路线试试 · 17",
    "chapter": 4,
    "stack": [
      7,
      5,
      3,
      1,
      4,
      2,
      6
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-080",
    "title": "换条路线试试 · 18",
    "chapter": 4,
    "stack": [
      1,
      5,
      2,
      7,
      3,
      4,
      6
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-081",
    "title": "换条路线试试 · 19",
    "chapter": 4,
    "stack": [
      7,
      1,
      5,
      2,
      4,
      6,
      3
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-082",
    "title": "换条路线试试 · 20",
    "chapter": 4,
    "stack": [
      1,
      4,
      3,
      7,
      5,
      2,
      6
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-083",
    "title": "换条路线试试 · 21",
    "chapter": 4,
    "stack": [
      7,
      5,
      3,
      6,
      2,
      4,
      1
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-084",
    "title": "换条路线试试 · 22",
    "chapter": 4,
    "stack": [
      4,
      7,
      1,
      5,
      3,
      6,
      2
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-085",
    "title": "换条路线试试 · 23",
    "chapter": 4,
    "stack": [
      1,
      4,
      2,
      6,
      5,
      7,
      3
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-086",
    "title": "换条路线试试 · 24",
    "chapter": 4,
    "stack": [
      4,
      2,
      6,
      1,
      7,
      3,
      5
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-087",
    "title": "换条路线试试 · 25",
    "chapter": 4,
    "stack": [
      5,
      7,
      3,
      4,
      1,
      6,
      2
    ],
    "minMoves": 8
  },
  {
    "id": "pancake-088",
    "title": "换条路线试试 · 26",
    "chapter": 4,
    "stack": [
      3,
      7,
      5,
      2,
      6,
      1,
      4
    ],
    "minMoves": 8
  },
  {
    "id": "pancake-089",
    "title": "整叠的计划 · 1",
    "chapter": 5,
    "stack": [
      8,
      7,
      5,
      2,
      1,
      4,
      3,
      6
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-090",
    "title": "整叠的计划 · 2",
    "chapter": 5,
    "stack": [
      5,
      7,
      8,
      4,
      1,
      6,
      3,
      2
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-091",
    "title": "整叠的计划 · 3",
    "chapter": 5,
    "stack": [
      8,
      7,
      3,
      1,
      4,
      5,
      2,
      6
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-092",
    "title": "整叠的计划 · 4",
    "chapter": 5,
    "stack": [
      3,
      4,
      7,
      8,
      1,
      2,
      6,
      5
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-093",
    "title": "整叠的计划 · 5",
    "chapter": 5,
    "stack": [
      5,
      2,
      1,
      4,
      3,
      8,
      6,
      7
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-094",
    "title": "整叠的计划 · 6",
    "chapter": 5,
    "stack": [
      1,
      6,
      7,
      2,
      8,
      5,
      4,
      3
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-095",
    "title": "整叠的计划 · 7",
    "chapter": 5,
    "stack": [
      3,
      6,
      7,
      8,
      1,
      4,
      2,
      5
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-096",
    "title": "整叠的计划 · 8",
    "chapter": 5,
    "stack": [
      3,
      2,
      1,
      6,
      5,
      8,
      7,
      4
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-097",
    "title": "整叠的计划 · 9",
    "chapter": 5,
    "stack": [
      3,
      2,
      7,
      6,
      1,
      5,
      8,
      4
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-098",
    "title": "整叠的计划 · 10",
    "chapter": 5,
    "stack": [
      8,
      1,
      3,
      2,
      7,
      6,
      4,
      5
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-099",
    "title": "整叠的计划 · 11",
    "chapter": 5,
    "stack": [
      6,
      5,
      4,
      8,
      2,
      3,
      1,
      7
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-100",
    "title": "整叠的计划 · 12",
    "chapter": 5,
    "stack": [
      6,
      8,
      1,
      7,
      3,
      2,
      5,
      4
    ],
    "minMoves": 6
  },
  {
    "id": "pancake-101",
    "title": "整叠的计划 · 13",
    "chapter": 5,
    "stack": [
      8,
      1,
      3,
      2,
      5,
      4,
      6,
      7
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-102",
    "title": "整叠的计划 · 14",
    "chapter": 5,
    "stack": [
      2,
      1,
      3,
      7,
      6,
      8,
      4,
      5
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-103",
    "title": "整叠的计划 · 15",
    "chapter": 5,
    "stack": [
      8,
      6,
      2,
      5,
      1,
      4,
      3,
      7
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-104",
    "title": "整叠的计划 · 16",
    "chapter": 5,
    "stack": [
      6,
      4,
      7,
      3,
      8,
      5,
      1,
      2
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-105",
    "title": "整叠的计划 · 17",
    "chapter": 5,
    "stack": [
      5,
      7,
      6,
      8,
      2,
      1,
      3,
      4
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-106",
    "title": "整叠的计划 · 18",
    "chapter": 5,
    "stack": [
      6,
      3,
      7,
      1,
      8,
      5,
      4,
      2
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-107",
    "title": "整叠的计划 · 19",
    "chapter": 5,
    "stack": [
      2,
      6,
      7,
      5,
      3,
      1,
      8,
      4
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-108",
    "title": "整叠的计划 · 20",
    "chapter": 5,
    "stack": [
      2,
      4,
      8,
      1,
      6,
      7,
      5,
      3
    ],
    "minMoves": 7
  },
  {
    "id": "pancake-109",
    "title": "整叠的计划 · 21",
    "chapter": 5,
    "stack": [
      4,
      2,
      3,
      1,
      6,
      8,
      5,
      7
    ],
    "minMoves": 8
  },
  {
    "id": "pancake-110",
    "title": "整叠的计划 · 22",
    "chapter": 5,
    "stack": [
      5,
      8,
      3,
      4,
      1,
      7,
      6,
      2
    ],
    "minMoves": 8
  },
  {
    "id": "pancake-111",
    "title": "整叠的计划 · 23",
    "chapter": 5,
    "stack": [
      3,
      6,
      8,
      2,
      5,
      7,
      1,
      4
    ],
    "minMoves": 8
  },
  {
    "id": "pancake-112",
    "title": "整叠的计划 · 24",
    "chapter": 5,
    "stack": [
      5,
      2,
      6,
      1,
      8,
      4,
      7,
      3
    ],
    "minMoves": 8
  },
  {
    "id": "pancake-113",
    "title": "整叠的计划 · 25",
    "chapter": 5,
    "stack": [
      4,
      1,
      8,
      6,
      2,
      7,
      5,
      3
    ],
    "minMoves": 8
  },
  {
    "id": "pancake-114",
    "title": "整叠的计划 · 26",
    "chapter": 5,
    "stack": [
      3,
      8,
      6,
      1,
      4,
      2,
      5,
      7
    ],
    "minMoves": 8
  },
  {
    "id": "pancake-115",
    "title": "整叠的计划 · 27",
    "chapter": 5,
    "stack": [
      6,
      8,
      4,
      2,
      5,
      1,
      3,
      7
    ],
    "minMoves": 8
  },
  {
    "id": "pancake-116",
    "title": "整叠的计划 · 28",
    "chapter": 5,
    "stack": [
      1,
      7,
      5,
      3,
      6,
      4,
      8,
      2
    ],
    "minMoves": 8
  },
  {
    "id": "pancake-117",
    "title": "整叠的计划 · 29",
    "chapter": 5,
    "stack": [
      1,
      4,
      3,
      6,
      8,
      5,
      2,
      7
    ],
    "minMoves": 9
  },
  {
    "id": "pancake-118",
    "title": "整叠的计划 · 30",
    "chapter": 5,
    "stack": [
      5,
      7,
      3,
      8,
      1,
      4,
      6,
      2
    ],
    "minMoves": 9
  },
  {
    "id": "pancake-119",
    "title": "整叠的计划 · 31",
    "chapter": 5,
    "stack": [
      2,
      8,
      4,
      7,
      3,
      5,
      1,
      6
    ],
    "minMoves": 9
  },
  {
    "id": "pancake-120",
    "title": "整叠的计划 · 32",
    "chapter": 5,
    "stack": [
      2,
      7,
      4,
      8,
      5,
      1,
      6,
      3
    ],
    "minMoves": 9
  }
];
