// SPDX-License-Identifier: GPL-3.0-only
import { labQ as q } from "./ballisticsCircuitExact";
import {
  parabolicParts,
  type ParabolicLevel,
  type ParabolicMove,
  type ParabolicObstacle,
} from "./parabolicTargetsLogic";
const box = (
  name: string,
  left: number,
  right: number,
  bottom: number,
  top: number,
): ParabolicObstacle => ({
  name,
  left: q(left),
  right: q(right),
  bottom: q(bottom),
  top: q(top),
});
/** Targets and obstacles are authored independently of each replay certificate. */
export const parabolicTargetsLevels: ParabolicLevel[] = [
  {
    title: "一条绿色靶窗",
    idea: "只改变向上的初速度，比较同一飞行时间内的高度。",
    startHeight: 1,
    targetX: 8,
    targetLow: q(5, 2),
    targetHigh: q(7, 2),
    direction: "either",
    vx: [4],
    vy: [2, 3, 4],
    obstacles: [],
    certificate: { vx: 4, vy: 3 },
  },
  {
    title: "时间也会弯曲路线",
    idea: "水平速度决定飞到靶线的时间。时间过长，重力下落可能占上风。",
    startHeight: 1,
    targetX: 12,
    targetLow: q(5, 2),
    targetHigh: q(7, 2),
    direction: "either",
    vx: [3, 4, 6],
    vy: [3],
    obstacles: [],
    certificate: { vx: 6, vy: 3 },
  },
  {
    title: "越过矮墙",
    idea: "靶线高度相同，不代表中途轨迹相同。还要检查墙顶。",
    startHeight: 1,
    targetX: 12,
    targetLow: q(13, 2),
    targetHigh: q(15, 2),
    direction: "either",
    vx: [3, 4, 5, 6],
    vy: [3, 4, 5],
    obstacles: [box("矮墙", 5, 6, 0, 5)],
    certificate: { vx: 4, vy: 5 },
  },
  {
    title: "从棚下穿过",
    idea: "不是越高越好。上方的实体棚顶会挡住高弧线。",
    startHeight: 1,
    targetX: 12,
    targetLow: q(5, 2),
    targetHigh: q(7, 2),
    direction: "either",
    vx: [3, 4, 6],
    vy: [3, 4, 5],
    obstacles: [box("棚顶", 3, 8, 4, 10)],
    certificate: { vx: 6, vy: 3 },
  },
  {
    title: "先过墙，再过棚",
    idea: "用两个条件夹出一条通道：前段要够高，中段又不能太高。",
    startHeight: 1,
    targetX: 16,
    targetLow: q(9, 2),
    targetHigh: q(11, 2),
    direction: "either",
    vx: [4, 5, 6, 8],
    vy: [4, 5, 6],
    obstacles: [box("前墙", 4, 5, 0, 2), box("低棚", 8, 10, 6, 11)],
    certificate: { vx: 8, vy: 4 },
  },
  {
    title: "高台发射",
    idea: "起点高度也进入方程。靶窗高度从地面算起，不是从发射台算起。",
    startHeight: 3,
    targetX: 18,
    targetLow: q(11, 2),
    targetHigh: q(13, 2),
    direction: "either",
    vx: [3, 4, 6, 9],
    vy: [3, 4, 5, 6],
    obstacles: [
      box("岸墙", 7, 8, 0, 6),
      { ...box("上方梁", 13, 14, 7, 12), bottom: q(15, 2) },
    ],
    certificate: { vx: 6, vy: 4 },
  },
  {
    title: "细柱也不能穿越",
    idea: "障碍再薄也是真实的。整段连续曲线必须避开它。",
    startHeight: 1,
    targetX: 20,
    targetLow: q(49, 10),
    targetHigh: q(51, 10),
    direction: "either",
    vx: [4, 5, 6, 8, 10],
    vy: [3, 4, 5, 6, 7],
    obstacles: [
      {
        name: "细柱",
        left: q(19, 4),
        right: q(24, 5),
        bottom: q(0),
        top: q(3),
      },
      box("横梁", 9, 12, 8, 13),
    ],
    certificate: { vx: 5, vy: 5 },
  },
  {
    title: "两座高台之间",
    idea: "更高的发射台不会取消重力。仍要同时留意中途高度和终点高度。",
    startHeight: 4,
    targetX: 24,
    targetLow: q(15, 2),
    targetHigh: q(17, 2),
    direction: "either",
    vx: [4, 5, 6, 8, 10],
    vy: [4, 5, 6, 7, 8],
    obstacles: [box("高墙", 6, 7, 0, 7), box("平台上盖", 12, 15, 11, 16)],
    certificate: { vx: 6, vy: 5 },
  },
  {
    title: "向上穿靶",
    idea: "高度正确还不够：竖直速度大于零才是上升。小数显示不会替代精确分数判定。",
    startHeight: 2,
    targetX: 9,
    targetLow: q(239, 25),
    targetHigh: q(239, 25),
    direction: "rising",
    vx: [3, 4, 5, 6, 7],
    vy: [3, 4, 5, 6, 7],
    obstacles: [box("入口墙", 2, 3, 0, 4)],
    certificate: { vx: 5, vy: 6 },
  },
  {
    title: "向下穿靶",
    idea: "越过最高点以后仍能穿靶。用初始竖直速度减去重力造成的速度变化来判断方向。",
    startHeight: 2,
    targetX: 24,
    targetLow: q(39, 4),
    targetHigh: q(41, 4),
    direction: "falling",
    vx: [4, 5, 6, 8, 10],
    vy: [4, 5, 6, 7, 8],
    obstacles: [box("入口顶板", 5, 7, 9, 15), box("后墙", 15, 16, 0, 10)],
    certificate: { vx: 6, vy: 6 },
  },
  {
    title: "三道门槛",
    idea: "逐段核对：越墙、过棚、再越墙。不能只看靶线上的一个点。",
    startHeight: 3,
    targetX: 28,
    targetLow: q(11),
    targetHigh: q(11),
    direction: "falling",
    vx: [4, 5, 6, 7, 8, 10],
    vy: [4, 5, 6, 7, 8, 9],
    obstacles: [
      box("第一道墙", 9, 10, 0, 9),
      box("中央顶板", 16, 20, 13, 18),
      { ...box("末端墙", 25, 26, 0, 11), top: q(45, 4) },
    ],
    certificate: { vx: 7, vy: 6 },
  },
  {
    title: "独立设计师",
    idea: "综合飞行时间、最高点、连续避障与穿靶方向。先预测，再验证；没有倒计时。",
    startHeight: 2,
    targetX: 30,
    targetLow: q(11),
    targetHigh: q(14),
    direction: "falling",
    vx: [4, 5, 6, 7, 8, 9, 10, 12],
    vy: [4, 5, 6, 7, 8, 9, 10, 11],
    obstacles: [
      { ...box("入口墙", 7, 8, 0, 8), top: q(17, 2) },
      box("中央顶板", 15, 19, 15, 22),
      { ...box("末端墙", 27, 28, 0, 12), top: q(51, 4) },
    ],
    certificate: { vx: 6, vy: 7 },
  },
];
export const parabolicTargetsSolutions: ParabolicMove[][] =
  parabolicTargetsLevels.map((c) => [
    ...parabolicParts
      .filter((p) => c[p].length > 1)
      .map((part) => ({ part, value: c.certificate[part] })),
    { part: "launch" },
  ]);
