// SPDX-License-Identifier: GPL-3.0-only
import {useEffect,useRef,useState} from "react";
import type {GameProps} from "../lib/types";
import {initialPinball,pinballGardenLevels,pinFlipper,pinLaunches,servePinball,stepPinball} from "./pinballGardenLogic";
import type {PinballState} from "./pinballGardenLogic";
import "./pinballGarden.css";
export default function PinballGarden(props:GameProps){return <Round key={`${props.level}:${props.resetToken}`} {...props}/>;}
function Round({level,paused,hintToken,undoToken,onComplete,onStatus}:GameProps){
 const config=pinballGardenLevels[level]??pinballGardenLevels[0],[state,setState]=useState(()=>initialPinball(config)),[lane,setLane]=useState(1),[active,setActive]=useState([false,false]),[message,setMessage]=useState("选一个发球口，再按发球。花鼓全部亮起，还要完成挡板回击目标。");const live=useRef(state),keys=useRef([false,false]),pointer=useRef([false,false]),pulse=useRef([0,0]),frame=useRef(0),done=useRef(false),seenHint=useRef(hintToken),seenUndo=useRef(undoToken);const locked=paused||state.status==="won";
 function clear(){keys.current=[false,false];pointer.current=[false,false];pulse.current=[0,0];setActive([false,false]);}function save(s:PinballState){live.current=s;setState(s);}function serve(){if(locked||state.status!=="ready")return;save(servePinball(state,lane));setMessage("落球靠近下方挡板时回击。点亮进度会保留，多次发球不扣分。");}
 useEffect(()=>{onStatus("点亮所有花鼓，并完成真实挡板回击目标。A / D 或触屏控制固定左右挡板，空格发球。");return()=>{cancelAnimationFrame(frame.current);keys.current=[false,false];pointer.current=[false,false];pulse.current=[0,0];};},[]);
 useEffect(()=>{clear();if(paused||state.status!=="playing")return;let last=0;function tick(now:number){const left=keys.current[0]||pointer.current[0]||now<pulse.current[0],right=keys.current[1]||pointer.current[1]||now<pulse.current[1];setActive([left,right]);if(last)save(stepPinball(config,live.current,left,right,Math.min(.032,(now-last)/1000)));last=now;if(live.current.status==="playing")frame.current=requestAnimationFrame(tick);}frame.current=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame.current);keys.current=[false,false];pointer.current=[false,false];pulse.current=[0,0];};},[paused,state.status,config]);
 useEffect(()=>{if(hintToken===seenHint.current)return;seenHint.current=hintToken;if(locked)return;const missing=state.lit.findIndex(v=>!v),text=state.status==="ready"?missing>=0?`尚未点亮“${config.bumpers[missing].name}”。它在横坐标 ${config.bumpers[missing].x} 附近，可选最近的发球口。`:`花鼓都亮了，还需 ${Math.max(0,config.returns-state.left-state.right)} 次回击${config.both?"，并确保左右挡板各有一次":""}。继续发球。`:state.y>340&&state.vy>0?`小球正在${state.x<180?"左":"右"}侧下落，现在可以按${state.x<180?"左":"右"}挡板尝试回击。`:"小球仍在上半台。先看它落向哪边，靠近下方挡板时再回击。";setMessage(text);onStatus(text);},[hintToken,locked,state,config,onStatus]);
 useEffect(()=>{if(undoToken===seenUndo.current)return;seenUndo.current=undoToken;if(!locked)onStatus("实时弹珠不提供撤销；重来会清空亮灯和回击次数。");},[undoToken,locked,onStatus]);
 useEffect(()=>{if(state.status==="won"&&!paused&&!done.current){done.current=true;onStatus("花鼓全亮，挡板回击目标也完成了！");onComplete();}},[state.status,paused,onStatus,onComplete]);
 function tap(side:number){if(!locked&&state.status==="playing")pulse.current[side]=performance.now()+320;}
 return <div className="puzzle-layout pbg-game" data-pbg-state={JSON.stringify(state)} data-pbg-won={state.status==="won"}><section className="pbg-workbench"><header><span className="mini-label">弹珠花台 · {config.title}</span><b>第 {state.balls} 球</b></header><div className="pbg-tally"><span>花鼓 {state.lit.filter(Boolean).length}/{state.lit.length}</span><span>回击 {state.left+state.right}/{config.returns}</span><span>左 {state.left} · 右 {state.right}{config.both?"（各需一次）":""}</span></div>
 <div className="pbg-table" tabIndex={locked?-1:0} role="group" aria-label="弹珠台，A 左挡板，D 右挡板，空格发球" onBlur={clear} onKeyDown={e=>{if(locked||e.ctrlKey||e.metaKey||e.altKey)return;const k=e.key.toLowerCase();if(["a","d","arrowleft","arrowright"," "].includes(k)){e.preventDefault();if(k===" "){if(!e.repeat)serve();}else if(state.status==="playing")keys.current[k==="a"||k==="arrowleft"?0:1]=true;}}} onKeyUp={e=>{const k=e.key.toLowerCase();if(["a","arrowleft"].includes(k))keys.current[0]=false;if(["d","arrowright"].includes(k))keys.current[1]=false;}}>
 <svg viewBox="0 0 360 510" role="img" aria-label={`小球横坐标 ${Math.round(state.x)}，纵坐标 ${Math.round(state.y)}。${state.status==="ready"?"可以发球":"弹珠进行中"}`}><rect x="3" y="3" width="354" height="504" rx="40" fill="#e8e3cf" stroke="#557e68" strokeWidth="6"/><path d="M27 370V90Q27 28 90 28H270Q333 28 333 90V370" fill="none" stroke="#b5c4a4" strokeWidth="14"/><text x="180" y="65" textAnchor="middle" fontSize="13" fill="#527563">花 园 弹 珠 CLUB</text>
 {config.bumpers.map((b,i)=><g key={i} data-pbg-bumper={i} data-pbg-lit={state.lit[i]}><circle cx={b.x} cy={b.y} r={b.r+6} fill={state.lit[i]?"#f7d978":"#c4b7d0"} stroke={state.lit[i]?"#ae8236":"#9a81a8"} strokeWidth="3"/><circle cx={b.x} cy={b.y} r={b.r-4} fill={state.lit[i]?"#fff1ae":"#ece1ed"}/><text x={b.x} y={b.y+8} textAnchor="middle" fill={state.lit[i]?"#aa783b":"#92749f"} fontSize="27">✿</text><text x={b.x} y={b.y+b.r+23} textAnchor="middle" fontSize="10" fill="#58705f">{b.name}</text></g>)}
 {config.rails.map((rail,i)=><path key={i} d={`M${rail[0]} ${rail[1]}L${rail[2]} ${rail[3]}`} stroke="#6e9271" strokeWidth="9" strokeLinecap="round"/>)}
 {[0,1].map(side=>{const p=pinFlipper(side===0,active[side]);return <g key={side}><path d={`M${p[0]} ${p[1]}L${p[2]} ${p[3]}`} stroke={active[side]?"#d89447":"#b07b64"} strokeWidth="18" strokeLinecap="round"/><circle cx={p[0]} cy={p[1]} r="8" fill="#f5dfb8"/><text x={side===0?85:275} y="492" textAnchor="middle" fill="#53715d" fontSize="13">{side===0?"左 A":"右 D"}</text></g>;})}
 <circle cx={state.status==="ready"?pinLaunches[lane]:state.x} cy={state.status==="ready"?456:state.y} r="9" fill="#faf9ef" stroke="#687b79" strokeWidth="2"/><circle cx={(state.status==="ready"?pinLaunches[lane]:state.x)-3} cy={(state.status==="ready"?456:state.y)-3} r="3" fill="#fff"/>{paused?<g><rect width="360" height="510" fill="#fff" opacity=".66"/><text x="180" y="255" textAnchor="middle" fontSize="25" fill="#486c55">已暂停</text></g>:null}</svg></div>
 <div className="pbg-launches" role="group" aria-label="选择发球口">{["左口","中口","右口"].map((name,i)=><button key={i} data-pbg-lane={i} disabled={locked||state.status!=="ready"} aria-pressed={lane===i} onClick={()=>setLane(i)}>{name}</button>)}<button className="pbg-serve" disabled={locked||state.status!=="ready"} onClick={serve}>发球</button></div>
 <div className="pbg-controls">{["左挡板","右挡板"].map((name,side)=><button key={side} data-pbg-flipper={side} disabled={locked||state.status!=="playing"} onPointerDown={e=>{if(locked)return;e.preventDefault();pointer.current[side]=true;e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={()=>{pointer.current[side]=false;}} onPointerCancel={()=>{pointer.current[side]=false;pulse.current[side]=0;}} onLostPointerCapture={()=>{pointer.current[side]=false;pulse.current[side]=0;}} onClick={()=>tap(side)}>{side===0?"↖":"↗"} {name}</button>)}</div><p className="pbg-feedback" role="status">{paused?"已暂停，弹珠和挡板都静止。":state.status==="won"?"花园花鼓全亮，回击演奏完成！":state.status==="ready"&&state.balls?"小球落袋。亮灯和回击保留，可以重新选口发球。":message}</p></section>
 <aside className="game-notes"><span className="mini-label">重力 · 固定挡板 · 碰撞回击</span><h3>抬起挡板，奏响花鼓。</h3><p>{config.lesson}</p><ol><li>选左、中、右发球口，把球向上弹出。花鼓被真实撞到后亮起。</li><li>左右挡板固定在下方，不可拖着挡板追球。按住会抬起；轻点抬起 320 毫秒。</li><li>下落小球碰到抬起的挡板才计为回击。所有花鼓点亮且回击达标后通关。</li></ol><p>这是简化的玩具物理：固定重力、圆形花鼓、线段挡板；抬起挡板接球时给固定向上冲量，不模拟完整角动量。练习不限球数，落袋保留本轮目标进度。实时过程不撤销，重来清零。</p><p>键盘聚焦球台后按住 A / D（或左右箭头）控制挡板，空格发球。暂停、失焦和离开关卡清除按住状态。</p></aside></div>;
}
