// SPDX-License-Identifier: GPL-3.0-only
import type { PipeLevel } from "./pipeCapacityLogic";
// Public goals and capacities are authored independently; certificates are test witnesses only.
export const pipeCapacityLevels: PipeLevel[] = [
  {
    id: "pc-01",
    title: "分流的第一步",
    lesson: "输入 3 单位，两个出口分别需要 1 和 2；中转站不能凭空产生水。",
    nodes: [
      {
        label: "A",
        balance: 3,
        x: 120,
        y: 115,
      },
      {
        label: "B",
        balance: 0,
        x: 230,
        y: 115,
      },
      {
        label: "C",
        balance: -1,
        x: 340,
        y: 115,
      },
      {
        label: "D",
        balance: -2,
        x: 340,
        y: 215,
      },
    ],
    edges: [
      {
        from: 0,
        to: 1,
        capacity: 3,
        cost: 0,
      },
      {
        from: 1,
        to: 2,
        capacity: 2,
        cost: 0,
      },
      {
        from: 1,
        to: 3,
        capacity: 3,
        cost: 0,
      },
    ],
    certificate: {
      flows: [3, 1, 2],
      cost: 0,
    },
  },
  {
    id: "pc-02",
    title: "窄管在下游",
    lesson: "上游管宽不代表整条路都宽；两条支路必须共同分担下游需求。",
    nodes: [
      {
        label: "A",
        balance: 4,
        x: 120,
        y: 115,
      },
      {
        label: "B",
        balance: 0,
        x: 230,
        y: 115,
      },
      {
        label: "C",
        balance: 0,
        x: 230,
        y: 215,
      },
      {
        label: "D",
        balance: 0,
        x: 340,
        y: 115,
      },
      {
        label: "E",
        balance: -4,
        x: 450,
        y: 115,
      },
    ],
    edges: [
      {
        from: 0,
        to: 1,
        capacity: 3,
        cost: 0,
      },
      {
        from: 0,
        to: 2,
        capacity: 2,
        cost: 0,
      },
      {
        from: 1,
        to: 3,
        capacity: 2,
        cost: 0,
      },
      {
        from: 2,
        to: 3,
        capacity: 3,
        cost: 0,
      },
      {
        from: 3,
        to: 4,
        capacity: 4,
        cost: 0,
      },
    ],
    certificate: {
      flows: [2, 2, 2, 2, 4],
      cost: 0,
    },
  },
  {
    id: "pc-03",
    title: "两座水源",
    lesson: "两处供给汇合后再分配。每座水源必须恰好输出规定的净供给。",
    nodes: [
      {
        label: "A",
        balance: 2,
        x: 120,
        y: 115,
      },
      {
        label: "B",
        balance: 3,
        x: 120,
        y: 215,
      },
      {
        label: "C",
        balance: 0,
        x: 230,
        y: 115,
      },
      {
        label: "D",
        balance: -2,
        x: 340,
        y: 115,
      },
      {
        label: "E",
        balance: -3,
        x: 340,
        y: 215,
      },
    ],
    edges: [
      {
        from: 0,
        to: 2,
        capacity: 2,
        cost: 0,
      },
      {
        from: 1,
        to: 2,
        capacity: 3,
        cost: 0,
      },
      {
        from: 2,
        to: 3,
        capacity: 3,
        cost: 0,
      },
      {
        from: 2,
        to: 4,
        capacity: 3,
        cost: 0,
      },
    ],
    certificate: {
      flows: [2, 3, 2, 3],
      cost: 0,
    },
  },
  {
    id: "pc-04",
    title: "交叉供水",
    lesson:
      "两个支路都能支援两处需求，但交叉管的容量不同。允许任何满足供需的分配。",
    nodes: [
      {
        label: "A",
        balance: 5,
        x: 120,
        y: 115,
      },
      {
        label: "B",
        balance: 0,
        x: 230,
        y: 115,
      },
      {
        label: "C",
        balance: 0,
        x: 230,
        y: 215,
      },
      {
        label: "D",
        balance: -2,
        x: 340,
        y: 115,
      },
      {
        label: "E",
        balance: -3,
        x: 340,
        y: 215,
      },
    ],
    edges: [
      {
        from: 0,
        to: 1,
        capacity: 3,
        cost: 0,
      },
      {
        from: 0,
        to: 2,
        capacity: 3,
        cost: 0,
      },
      {
        from: 1,
        to: 3,
        capacity: 2,
        cost: 0,
      },
      {
        from: 1,
        to: 4,
        capacity: 2,
        cost: 0,
      },
      {
        from: 2,
        to: 3,
        capacity: 1,
        cost: 0,
      },
      {
        from: 2,
        to: 4,
        capacity: 3,
        cost: 0,
      },
    ],
    certificate: {
      flows: [2, 3, 1, 1, 1, 2],
      cost: 0,
    },
  },
  {
    id: "pc-05",
    title: "零也是决定",
    lesson:
      "问号表示尚未决定，0 表示明确关闭。这次免费路线足够，付费旁路应保持零流量。",
    nodes: [
      {
        label: "A",
        balance: 3,
        x: 120,
        y: 115,
      },
      {
        label: "B",
        balance: 0,
        x: 230,
        y: 115,
      },
      {
        label: "C",
        balance: 0,
        x: 340,
        y: 115,
      },
      {
        label: "D",
        balance: -1,
        x: 450,
        y: 115,
      },
      {
        label: "E",
        balance: -2,
        x: 450,
        y: 215,
      },
    ],
    edges: [
      {
        from: 0,
        to: 1,
        capacity: 3,
        cost: 0,
      },
      {
        from: 0,
        to: 2,
        capacity: 3,
        cost: 2,
      },
      {
        from: 1,
        to: 3,
        capacity: 1,
        cost: 0,
      },
      {
        from: 1,
        to: 4,
        capacity: 2,
        cost: 0,
      },
      {
        from: 2,
        to: 3,
        capacity: 1,
        cost: 0,
      },
      {
        from: 2,
        to: 4,
        capacity: 2,
        cost: 0,
      },
      {
        from: 1,
        to: 2,
        capacity: 2,
        cost: 2,
      },
    ],
    certificate: {
      flows: [3, 0, 1, 2, 0, 0, 0],
      cost: 0,
    },
    budget: 0,
  },
  {
    id: "pc-06",
    title: "汇流再分流",
    lesson: "第二座水源通往上方中转站的管道很窄，要协调两座水源的分担。",
    nodes: [
      {
        label: "A",
        balance: 2,
        x: 120,
        y: 115,
      },
      {
        label: "B",
        balance: 2,
        x: 120,
        y: 215,
      },
      {
        label: "C",
        balance: 0,
        x: 230,
        y: 115,
      },
      {
        label: "D",
        balance: 0,
        x: 230,
        y: 215,
      },
      {
        label: "E",
        balance: -1,
        x: 340,
        y: 115,
      },
      {
        label: "F",
        balance: -3,
        x: 340,
        y: 215,
      },
    ],
    edges: [
      {
        from: 0,
        to: 2,
        capacity: 2,
        cost: 0,
      },
      {
        from: 0,
        to: 3,
        capacity: 2,
        cost: 0,
      },
      {
        from: 1,
        to: 2,
        capacity: 1,
        cost: 0,
      },
      {
        from: 1,
        to: 3,
        capacity: 2,
        cost: 0,
      },
      {
        from: 2,
        to: 4,
        capacity: 1,
        cost: 0,
      },
      {
        from: 2,
        to: 5,
        capacity: 2,
        cost: 0,
      },
      {
        from: 3,
        to: 5,
        capacity: 2,
        cost: 0,
      },
    ],
    certificate: {
      flows: [1, 1, 1, 1, 1, 1, 2],
      cost: 0,
    },
  },
  {
    id: "pc-07",
    title: "少用一次泵",
    lesson: "每条管道按流量乘单价收费；路短不总是便宜，但重复抽水会累加费用。",
    nodes: [
      {
        label: "A",
        balance: 4,
        x: 120,
        y: 115,
      },
      {
        label: "B",
        balance: 0,
        x: 230,
        y: 115,
      },
      {
        label: "C",
        balance: 0,
        x: 230,
        y: 215,
      },
      {
        label: "D",
        balance: 0,
        x: 340,
        y: 115,
      },
      {
        label: "E",
        balance: -2,
        x: 450,
        y: 115,
      },
      {
        label: "F",
        balance: -2,
        x: 450,
        y: 215,
      },
    ],
    edges: [
      {
        from: 0,
        to: 1,
        capacity: 2,
        cost: 1,
      },
      {
        from: 0,
        to: 2,
        capacity: 4,
        cost: 0,
      },
      {
        from: 1,
        to: 4,
        capacity: 2,
        cost: 0,
      },
      {
        from: 2,
        to: 3,
        capacity: 4,
        cost: 1,
      },
      {
        from: 3,
        to: 4,
        capacity: 2,
        cost: 1,
      },
      {
        from: 3,
        to: 5,
        capacity: 2,
        cost: 0,
      },
    ],
    certificate: {
      flows: [2, 2, 2, 2, 0, 2],
      cost: 4,
    },
    budget: 4,
  },
  {
    id: "pc-08",
    title: "横向支援",
    lesson: "主支路分出一部分流量给另一支路；供水方向固定，不能把箭头反过来。",
    nodes: [
      {
        label: "A",
        balance: 5,
        x: 120,
        y: 115,
      },
      {
        label: "B",
        balance: 0,
        x: 230,
        y: 115,
      },
      {
        label: "C",
        balance: 0,
        x: 340,
        y: 115,
      },
      {
        label: "D",
        balance: 0,
        x: 450,
        y: 115,
      },
      {
        label: "E",
        balance: -2,
        x: 560,
        y: 115,
      },
      {
        label: "F",
        balance: -3,
        x: 450,
        y: 215,
      },
    ],
    edges: [
      {
        from: 0,
        to: 1,
        capacity: 4,
        cost: 0,
      },
      {
        from: 0,
        to: 2,
        capacity: 1,
        cost: 0,
      },
      {
        from: 1,
        to: 3,
        capacity: 2,
        cost: 0,
      },
      {
        from: 1,
        to: 2,
        capacity: 3,
        cost: 0,
      },
      {
        from: 2,
        to: 3,
        capacity: 3,
        cost: 0,
      },
      {
        from: 3,
        to: 4,
        capacity: 2,
        cost: 0,
      },
      {
        from: 2,
        to: 5,
        capacity: 3,
        cost: 0,
      },
    ],
    certificate: {
      flows: [4, 1, 1, 3, 1, 2, 3],
      cost: 0,
    },
  },
  {
    id: "pc-09",
    title: "沿途取水",
    lesson:
      "D 站自己取走 1 单位，再把余量送往终点；有需求的节点也可能继续输出。",
    nodes: [
      {
        label: "A",
        balance: 5,
        x: 120,
        y: 115,
      },
      {
        label: "B",
        balance: 0,
        x: 230,
        y: 115,
      },
      {
        label: "C",
        balance: 0,
        x: 230,
        y: 215,
      },
      {
        label: "D",
        balance: -1,
        x: 340,
        y: 115,
      },
      {
        label: "E",
        balance: 0,
        x: 340,
        y: 215,
      },
      {
        label: "F",
        balance: -4,
        x: 450,
        y: 115,
      },
    ],
    edges: [
      {
        from: 0,
        to: 1,
        capacity: 3,
        cost: 0,
      },
      {
        from: 0,
        to: 2,
        capacity: 3,
        cost: 0,
      },
      {
        from: 1,
        to: 3,
        capacity: 2,
        cost: 0,
      },
      {
        from: 1,
        to: 4,
        capacity: 2,
        cost: 0,
      },
      {
        from: 2,
        to: 3,
        capacity: 2,
        cost: 0,
      },
      {
        from: 2,
        to: 4,
        capacity: 2,
        cost: 0,
      },
      {
        from: 3,
        to: 5,
        capacity: 3,
        cost: 0,
      },
      {
        from: 4,
        to: 5,
        capacity: 3,
        cost: 0,
      },
    ],
    certificate: {
      flows: [2, 3, 0, 2, 2, 1, 1, 3],
      cost: 0,
    },
  },
  {
    id: "pc-10",
    title: "水源与费用",
    lesson: "两座水源的便宜路线不同。既要满足两处需求，也要限制付费绕行。",
    nodes: [
      {
        label: "A",
        balance: 3,
        x: 120,
        y: 115,
      },
      {
        label: "B",
        balance: 2,
        x: 120,
        y: 215,
      },
      {
        label: "C",
        balance: 0,
        x: 230,
        y: 115,
      },
      {
        label: "D",
        balance: 0,
        x: 230,
        y: 215,
      },
      {
        label: "E",
        balance: -2,
        x: 340,
        y: 115,
      },
      {
        label: "F",
        balance: -3,
        x: 340,
        y: 215,
      },
    ],
    edges: [
      {
        from: 0,
        to: 2,
        capacity: 3,
        cost: 2,
      },
      {
        from: 0,
        to: 3,
        capacity: 2,
        cost: 0,
      },
      {
        from: 1,
        to: 2,
        capacity: 2,
        cost: 0,
      },
      {
        from: 1,
        to: 3,
        capacity: 2,
        cost: 2,
      },
      {
        from: 2,
        to: 4,
        capacity: 2,
        cost: 0,
      },
      {
        from: 2,
        to: 5,
        capacity: 2,
        cost: 1,
      },
      {
        from: 3,
        to: 4,
        capacity: 2,
        cost: 1,
      },
      {
        from: 3,
        to: 5,
        capacity: 3,
        cost: 0,
      },
    ],
    certificate: {
      flows: [1, 2, 2, 0, 2, 1, 0, 2],
      cost: 3,
    },
    budget: 3,
  },
  {
    id: "pc-11",
    title: "双层分配网",
    lesson:
      "八个节点组成两层分配网。先想终点需要多少，再检查每一层能否传递这些流量。",
    nodes: [
      {
        label: "A",
        balance: 3,
        x: 120,
        y: 115,
      },
      {
        label: "B",
        balance: 2,
        x: 120,
        y: 215,
      },
      {
        label: "C",
        balance: 0,
        x: 230,
        y: 115,
      },
      {
        label: "D",
        balance: 0,
        x: 230,
        y: 215,
      },
      {
        label: "E",
        balance: 0,
        x: 340,
        y: 115,
      },
      {
        label: "F",
        balance: 0,
        x: 340,
        y: 215,
      },
      {
        label: "G",
        balance: -3,
        x: 450,
        y: 115,
      },
      {
        label: "H",
        balance: -2,
        x: 450,
        y: 215,
      },
    ],
    edges: [
      {
        from: 0,
        to: 2,
        capacity: 3,
        cost: 0,
      },
      {
        from: 0,
        to: 3,
        capacity: 2,
        cost: 0,
      },
      {
        from: 1,
        to: 3,
        capacity: 2,
        cost: 0,
      },
      {
        from: 2,
        to: 4,
        capacity: 2,
        cost: 0,
      },
      {
        from: 2,
        to: 5,
        capacity: 2,
        cost: 0,
      },
      {
        from: 3,
        to: 4,
        capacity: 2,
        cost: 0,
      },
      {
        from: 3,
        to: 5,
        capacity: 2,
        cost: 0,
      },
      {
        from: 4,
        to: 6,
        capacity: 3,
        cost: 0,
      },
      {
        from: 5,
        to: 6,
        capacity: 2,
        cost: 0,
      },
      {
        from: 5,
        to: 7,
        capacity: 2,
        cost: 0,
      },
    ],
    certificate: {
      flows: [1, 2, 2, 0, 1, 2, 2, 2, 1, 2],
      cost: 0,
    },
  },
  {
    id: "pc-12",
    title: "精打细算的管网",
    lesson: "容量、守恒、两处需求和泵费同时生效。不要只看某一条最便宜的管道。",
    nodes: [
      {
        label: "A",
        balance: 5,
        x: 120,
        y: 115,
      },
      {
        label: "B",
        balance: 0,
        x: 230,
        y: 115,
      },
      {
        label: "C",
        balance: 0,
        x: 230,
        y: 215,
      },
      {
        label: "D",
        balance: 0,
        x: 340,
        y: 115,
      },
      {
        label: "E",
        balance: 0,
        x: 340,
        y: 215,
      },
      {
        label: "F",
        balance: -2,
        x: 450,
        y: 115,
      },
      {
        label: "G",
        balance: -3,
        x: 450,
        y: 215,
      },
    ],
    edges: [
      {
        from: 0,
        to: 1,
        capacity: 3,
        cost: 0,
      },
      {
        from: 0,
        to: 2,
        capacity: 3,
        cost: 1,
      },
      {
        from: 1,
        to: 3,
        capacity: 2,
        cost: 1,
      },
      {
        from: 1,
        to: 4,
        capacity: 2,
        cost: 0,
      },
      {
        from: 2,
        to: 3,
        capacity: 2,
        cost: 0,
      },
      {
        from: 2,
        to: 4,
        capacity: 2,
        cost: 2,
      },
      {
        from: 3,
        to: 5,
        capacity: 2,
        cost: 0,
      },
      {
        from: 3,
        to: 6,
        capacity: 2,
        cost: 1,
      },
      {
        from: 4,
        to: 5,
        capacity: 2,
        cost: 1,
      },
      {
        from: 4,
        to: 6,
        capacity: 3,
        cost: 0,
      },
    ],
    certificate: {
      flows: [3, 2, 1, 2, 2, 0, 2, 1, 0, 2],
      cost: 4,
    },
    budget: 4,
  },
];
