// SPDX-License-Identifier: GPL-3.0-only
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import type {GameProps} from '../lib/types';
import {rollingBlockLevels,rollCells,rollKey,rollLabels,rollLegal,rollSolution,rollSolved,rollStep,type RollDirection,type RollPose} from './rollingBlockLogic';
import './rollingBlockGarden.css';
export default function RollingBlockGarden(props:GameProps){return <RollingRound key={`${props.level}:${props.resetToken}`} {...props}/>;}
function RollingRound({level,paused,hintToken,undoToken,onComplete,onStatus}:GameProps){const l=rollingBlockLevels[level]??rollingBlockLevels[0];const [history,setHistory]=useState<RollPose[]>([l.start]),[message,setMessage]=useState(l.tip),[hint,setHint]=useState<RollDirection|null>(null),[bumps,setBumps]=useState(0);const p=history[history.length-1],won=rollSolved(l,p),done=useRef(false),tokens=useRef({hintToken,undoToken}),state=useRef({history,p,paused,won});state.current={history,p,paused,won};const callbacks=useRef({onComplete,onStatus});callbacks.current={onComplete,onStatus};const report=(text:string)=>{setMessage(text);callbacks.current.onStatus(text);};
 useEffect(()=>{callbacks.current.onStatus(l.tip);},[]);useEffect(()=>{if(won&&!paused&&!done.current){done.current=true;report('石柱直立到达终点，石桥通过！');callbacks.current.onComplete();}},[won,paused]);
 useEffect(()=>{if(tokens.current.undoToken===undoToken)return;tokens.current.undoToken=undoToken;if(paused||done.current)return;if(history.length>1){setHistory(history.slice(0,-1));setHint(null);report('退回上一次翻滚之前。');}},[undoToken]);
 useEffect(()=>{if(tokens.current.hintToken===hintToken)return;tokens.current.hintToken=hintToken;if(paused||won)return;const solution=rollSolution(l,p);setHint(solution?.[0]??null);report(solution?.length?`从现在的姿态出发，下一步${rollLabels[solution[0]]}。最短还需 ${solution.length} 步。`:solution?'你已经到达终点。':'当前姿态无法到达终点，试试撤销。');},[hintToken]);
 function move(d:RollDirection){const now=state.current;if(now.paused||now.won)return;const next=rollStep(now.p,d);if(!rollLegal(l,next)){setBumps(v=>v+1);report(next.axis==='stand'&&l.fragile.includes(`${next.x},${next.y}`)?'薄石不能承受直立的石柱。这一步未执行，请换个姿态。':'石柱的一部分会落空。这一步未执行，请换个方向。');return;}const h=[...now.history,next];state.current={history:h,p:next,paused,won:rollSolved(l,next)};setHistory(h);setHint(null);report(`已${rollLabels[d]}翻滚，${next.axis==='stand'?'现在直立，占一格':next.axis==='wide'?'现在横卧，占左右两格':'现在纵卧，占上下两格'}。`);}
 const cells=rollCells(p);return <div className="rolling-block" data-roll-pose={rollKey(p)} data-roll-won={String(won)} data-roll-steps={history.length-1} data-roll-bumps={bumps} tabIndex={0} onKeyDown={e=>{if(e.ctrlKey||e.altKey||e.metaKey)return;const d=({ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right'} as Record<string,RollDirection>)[e.key];if(d){e.preventDefault();move(d);}}}>
 <section className="rolling-main"><header><div><span className="rolling-eyebrow">TUMBLE · 云上的石桥</span><h3>{l.title}</h3></div><b>{level+1} / {rollingBlockLevels.length}</b></header><p>翻滚这根长石柱，让它<strong>直立</strong>在圆形终点。石柱占用的每一格，都必须有石桥承托。</p><div className="rolling-meter"><span>{paused?'已暂停':won?'终点站稳了':p.axis==='stand'?'▣ 直立 · 1 格':p.axis==='wide'?'▰ 横卧 · 2 格':'▮ 纵卧 · 2 格'}</span><b>{history.length-1} 步</b></div>
 <div className="rolling-sky"><div className="rolling-board" style={{'--roll-cols':l.width,'--roll-rows':l.height} as CSSProperties} aria-label="石桥俯视图">{Array.from({length:l.width*l.height},(_,i)=>{const x=i%l.width,y=Math.floor(i/l.width),key=`${x},${y}`,tile=l.tiles.includes(key),active=cells.includes(key),goal=l.goal===key,thin=l.fragile.includes(key);return <div key={key} className={`rolling-tile ${tile?'stone':'void'} ${goal?'goal':''} ${thin?'fragile':''} ${active?'occupied':''} ${active&&p.axis==='stand'?'standing':''}`} aria-label={tile?`${y+1}行${x+1}列${goal?'，终点':''}${thin?'，薄石':''}${active?'，石柱':''}`:undefined}>{goal&&<span className="rolling-goal" aria-hidden="true">◎</span>}{thin&&<span className="rolling-crack" aria-hidden="true">⌁</span>}{active&&<span className="rolling-cuboid" aria-hidden="true">{p.axis==='stand'?'✦':'◆'}</span>}</div>;})}</div></div>
 <div className="rolling-dpad" aria-label="翻滚方向">{(['up','left','down','right'] as RollDirection[]).map(d=><button type="button" key={d} data-direction={d} className={`${d} ${hint===d?'hinted':''}`} disabled={paused||won} aria-label={rollLabels[d]} onClick={()=>move(d)}><span aria-hidden="true">{{up:'↑',left:'←',down:'↓',right:'→'}[d]}</span></button>)}</div><p className="rolling-message" role="status">{message}</p>{won&&<div className="rolling-victory">✦ 平稳落在云端</div>}</section>
 <aside className="rolling-notes"><span className="rolling-eyebrow">一步，两种占地</span><h3>先想姿态，再想方向</h3><div className="rolling-lesson"><b>01 · 直立</b><p>翻倒后伸出两格。看清桥边是否有足够的空间。</p><b>02 · 躺卧</b><p>沿长边翻会重新站立，沿短边翻则侧移一格。</p><b>03 · 薄石与终点</b><p>裂纹薄石上只能躺着。圆形终点必须直立到达，横躺经过不算成功。</p></div><p>{l.tip}</p><details><summary>键盘与安全翻滚</summary><p>聚焦棋盘后使用方向键或 WASD，也可用下方四个大按钮。无效动作会显示原因并保留原位。提示从当前姿态寻找最短合法路线；撤销退一步，重来回到起点。胜利后锁定；暂停不会执行动作。</p></details></aside></div>;}
