// SPDX-License-Identifier: MIT
import type {
  SymmetryCell,
  SymmetryLevel,
  SymmetryTransform,
} from "./symmetryRepairLogic";
const make = (
  id: number,
  title: string,
  lesson: string,
  rows: string[],
  locked: number[],
  transforms: SymmetryTransform[],
  filled: number,
  budget: number,
): SymmetryLevel => ({
  id: `sr-${String(id).padStart(2, "0")}`,
  title,
  lesson,
  size: rows.length,
  initial: rows
    .join("")
    .split("")
    .map((c) => (c === "#" ? 1 : c === "." ? 0 : null)) as SymmetryCell[],
  locked,
  transforms,
  filled,
  budget,
});
export const symmetryRepairLevels: readonly SymmetryLevel[] = [
  make(
    1,
    "镜子另一边",
    "左右镜像把每行的第 1 格与最后一格配成一组。锁定格不可修改。",
    ["#??", "...", "..?"],
    [0, 4],
    ["vertical"],
    2,
    4,
  ),
  make(
    2,
    "上下呼应",
    "上下镜像不改变列；中间一行映射回自身，可以独立选择。",
    ["#..", ".#.", "?.."],
    [0],
    ["horizontal"],
    4,
    3,
  ),
  make(
    3,
    "半圈之后",
    "旋转 180° 时，左上角对应右下角。中心格不动。",
    ["#..", ".?.", ".#."],
    [0],
    ["halfTurn"],
    5,
    4,
  ),
  make(
    4,
    "斜线镜面",
    "主对角线镜像交换行与列。对角线上的格子各自不动。",
    [".#..", "..#.", "#...", "...."],
    [1],
    ["diagonal"],
    6,
    5,
  ),
  make(
    5,
    "另一条斜线",
    "副对角线从右上到左下。尝试找出不移动的格子，再处理配对。",
    ["#..#", ".#..", "..#.", "...."],
    [3],
    ["antiDiagonal"],
    6,
    4,
  ),
  make(
    6,
    "四分之一圈",
    "90° 旋转会产生四格一组的轨道：一格变化会约束另外三格。",
    ["#...", ".#..", "..#.", "...."],
    [0],
    ["quarterTurn"],
    8,
    5,
  ),
  make(
    7,
    "双镜组成",
    "同时满足左右、上下镜像，也必然满足 180° 旋转；所有规则一起检查。",
    ["#..", ".#.", "..#"],
    [4],
    ["vertical", "horizontal"],
    5,
    4,
  ),
  make(
    8,
    "镜面遇上半圈",
    "左右镜像与 180° 旋转组合后，同组格子可能有四个。注意预算是净改动。",
    ["#...", ".#..", "....", "...#"],
    [0],
    ["vertical", "halfTurn"],
    8,
    7,
  ),
  make(
    9,
    "旋转中心",
    "5×5 的中心轨道只有一格，其他 90° 轨道各有四格。利用总填充数判断中心。",
    ["#....", ".#...", "..?..", "...#.", "....#"],
    [0],
    ["quarterTurn"],
    9,
    7,
  ),
  make(
    10,
    "两条对角线",
    "两条对角线组合会得到半圈旋转，但不一定满足左右镜像。",
    [".#...", "..#..", "..#..", ".#...", "....."],
    [12],
    ["diagonal", "antiDiagonal"],
    9,
    8,
  ),
  make(
    11,
    "完整方形对称",
    "左右镜像与 90° 旋转共同生成方形的全部八种对称。轨道可能有八格。",
    ["#....", ".#...", "..#..", "...#.", "....."],
    [0, 12],
    ["vertical", "quarterTurn"],
    9,
    5,
  ),
  make(
    12,
    "最少修补展览",
    "预算很紧：先找出已有多数的一组，再决定保留还是擦去。任何满足公开条件的图案都通过。",
    ["#.#.#", ".#...", "#.#.#", "...#.", "#...#"],
    [0, 12],
    ["diagonal", "quarterTurn"],
    9,
    5,
  ),
];
