/** Original MIT puzzles. Generated by scripts/tents/generate.py; do not edit by hand. */
import type { TentsLevel } from "./tentsLevels";
import data from "./tentsExpansionData.json";
export const tentsExpansion: TentsLevel[] = data;
