/** Static adapter for original GPL-3.0-only puzzles generated by scripts/tents/generate.py. */
import type { TentsLevel } from "./tentsLevels";
import data from "./tentsExpansionData.json" with { type: "json" };
export const tentsExpansion: TentsLevel[] = data;
