// SPDX-License-Identifier: GPL-3.0-only
import {useEffect,useRef,useState} from 'react';
import type {GameProps} from '../lib/types';
import {threeMorrisLevels,morrisApply,morrisBest,morrisMoves,morrisWinner,type MorrisBoard,type MorrisMove} from './threeMorrisLogic';
import './threeMorrisGarden.css';
type Round={board:MorrisBoard;plies:number;seen:string[];result:'playing'|'won'|'lost'|'draw';last:number|null};
export default function ThreeMorrisGarden(props:GameProps){return <MorrisRound key={`${props.level}:${props.resetToken}`} {...props}/>;}
function MorrisRound({level,paused,hintToken,undoToken,onComplete,onStatus}:GameProps){const l=threeMorrisLevels[level]??threeMorrisLevels[0];const [history,setHistory]=useState<Round[]>([{board:l.board,plies:0,seen:[l.board.join('')+'1'],result:'playing',last:null}]),[selected,setSelected]=useState<number|null>(null),[hint,setHint]=useState<MorrisMove|null>(null),[message,setMessage]=useState(l.tip);const p=history[history.length-1],done=useRef(false),tokens=useRef({hintToken,undoToken}),buttons=useRef<(HTMLButtonElement|null)[]>([]),state=useRef({history,p,paused,selected});state.current={history,p,paused,selected};const callbacks=useRef({onComplete,onStatus});callbacks.current={onComplete,onStatus};const report=(text:string)=>{setMessage(text);callbacks.current.onStatus(text);};
 useEffect(()=>{callbacks.current.onStatus(l.tip);},[]);useEffect(()=>{if(p.result==='won'&&!paused&&!done.current){done.current=true;callbacks.current.onComplete();}},[p.result,paused]);
 useEffect(()=>{if(tokens.current.undoToken===undoToken)return;tokens.current.undoToken=undoToken;if(paused||done.current)return;if(history.length>1){setHistory(history.slice(0,-1));setSelected(null);setHint(null);report('已退回你的上一手之前，同时撤销电脑回击。');}},[undoToken]);
 useEffect(()=>{if(tokens.current.hintToken===hintToken)return;tokens.current.hintToken=hintToken;if(paused||p.result!=='playing')return;const result=morrisBest(p.board,1);setHint(result.move);setSelected(result.move&&result.move.from>=0?result.move.from:null);report(result.move?`当前局面的七层搜索建议：${result.move.from<0?'落子':`将 ${result.move.from+1} 号点的绿子移`}到 ${result.move.to+1} 号点。${result.score>1000?'这条线可形成制胜威胁。':'有限搜索未确认必胜；可继续观察或撤销。'}`:'当前没有合法移动，这盘是和局。');},[hintToken]);
 function click(i:number){const now=state.current;if(now.paused||now.p.result!=='playing')return;if(now.p.board[i]===1&&now.p.board.filter(v=>v===1).length===3){const selected=now.selected===i?null:i;state.current.selected=selected;setSelected(selected);setHint(null);return;}const from=now.p.board.filter(v=>v===1).length<3?-1:now.selected;if(from===null){report('先选一颗绿子，再点相邻的空点。');return;}const move={from,to:i};if(!morrisMoves(now.p.board,1).some(m=>m.from===from&&m.to===i)){report('这里只能沿画出的连线移动一步，且落点必须空着。');return;}let board=morrisApply(now.p.board,1,move),plies=now.p.plies+1,seen=[...now.p.seen,board.join('')+'2'],last:number|null=null;let result:Round['result']=morrisWinner(board)===1?'won':'playing';if(result==='playing'&&(seen.filter(k=>k===seen[seen.length-1]).length>=3||plies>=80||morrisMoves(board,2).length===0))result='draw';if(result==='playing'){const ai=morrisBest(board,2).move;if(ai){board=morrisApply(board,2,ai);plies++;seen.push(board.join('')+'1');last=ai.to;if(morrisWinner(board)===2)result='lost';else if(seen.filter(k=>k===seen[seen.length-1]).length>=3||plies>=80||morrisMoves(board,1).length===0)result='draw';}}
 const next={board,plies,seen,last,result},h=[...now.history,next];state.current={history:h,p:next,paused,selected:null};setHistory(h);setSelected(null);setHint(null);report(result==='won'?'三颗绿子连成一线，你赢了！':result==='lost'?'紫方先连成了一线。可以撤销完整一轮再试。':result==='draw'?'同一局面三次出现、达到 80 手或一方无步，这盘和局。撤销或重来再试。':`紫方落在 ${last!+1} 号点。轮到你。`);}
 const placement=p.board.filter(v=>v===1).length<3,legal=morrisMoves(p.board,1).filter(m=>m.from===(placement?-1:selected)).map(m=>m.to),winning=morrisWinner(p.board),winLine=winning?[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].find(line=>line.every(i=>p.board[i]===winning)):null;
 return <div className="three-morris" data-morris-board={p.board.join(',')} data-morris-result={p.result} data-morris-plies={p.plies}><section className="morris-main"><header><div><span className="morris-eyebrow">THREE MEN · 小小连线棋</span><h3>{l.title}</h3></div><b>{level+1} / {threeMorrisLevels.length}</b></header><p>你执绿子，电脑执紫子。每方三颗，先<strong>沿任意直线连成三颗</strong>的一方获胜。</p><div className="morris-meter"><span>{paused?'已暂停':p.result==='won'?'绿方成线':p.result==='lost'?'紫方成线':p.result==='draw'?'本盘和局':placement?'落子阶段 · 点空位':'移子阶段 · 先选绿子'}</span><b>{p.plies} 手</b></div>
 <div className="morris-board" aria-label="三子移阵棋盘"><svg className="morris-lines" viewBox="0 0 300 300" aria-hidden="true"><path d="M50 50H250V250H50ZM50 150H250M150 50V250M50 50L250 250M250 50L50 250"/></svg>{p.board.map((v,i)=><button type="button" key={i} data-point={i} className={`morris-point ${v===1?'green':v===2?'purple':'empty'} ${selected===i?'selected':''} ${legal.includes(i)?'reachable':''} ${hint?.to===i?'hinted':''} ${winLine?.includes(i)?'winning':''}`} ref={el=>{buttons.current[i]=el;}} disabled={paused||p.result!=='playing'} aria-label={`${i+1}号点，${v===1?'绿子':v===2?'紫子':'空点'}`} aria-pressed={selected===i} onClick={()=>click(i)} onKeyDown={e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;const delta=({ArrowLeft:-1,ArrowRight:1,ArrowUp:-3,ArrowDown:3} as Record<string,number>)[e.key];if(delta){e.preventDefault();const next=i+delta;if(next>=0&&next<9)buttons.current[next]?.focus();}}}><span aria-hidden="true">{v===1?'✿':v===2?'◆':legal.includes(i)?'·':''}</span><small>{i+1}</small></button>)}</div>
 <div className="morris-legend"><span>✿ 你 · 绿方</span><span>◆ 电脑 · 紫方</span><span>· 可到达空点</span></div><p className="morris-message" role="status">{message}</p>{p.result==='won'&&<div className="morris-victory">✿ 三子相连，花开成行</div>}</section><aside className="morris-notes"><span className="morris-eyebrow">落子只是开始</span><h3>三颗子，无限转机</h3><ol><li>尚未用完三颗子时，轮流落在任意空点。</li><li>三颗全部落下后，每手沿一条线移动到相邻空点，不可跳子。</li><li>横、竖、对角线都能获胜。中心与周围八点相连，边上的点不能斜跳。</li></ol><p>{l.tip}</p><details><summary>电脑、和局与操作</summary><p>本地电脑搜索未来七手，不保证全局最优。提示重新分析当前棋盘，不会代下。同一棋盘与行棋方出现三次、80 手仍未成线或一方无合法移动时和局，和局不计通关。</p><p>点击或使用 Tab、方向键和 Enter / 空格。暂停阻止操作；撤销回退整轮；重来恢复这道残局。真实胜利后锁定棋盘。</p></details></aside></div>;}
