// SPDX-License-Identifier: GPL-3.0-only
import {useEffect,useRef,useState,type KeyboardEvent,type PointerEvent} from 'react';
import type {GameProps} from '../lib/types';
import {VikingEngine,type Direction,type VikingSnapshot} from '../vendor/vikingCore';
import {VIKING_STORY} from './vikingStory';
import './viking.css';
const SAVE='playgarden.viking.v1';
const directions=[{id:'up' as const,name:'向上走',mark:'↑',dx:0,dy:-1},{id:'left' as const,name:'向左走',mark:'←',dx:-1,dy:0},{id:'down' as const,name:'向下走',mark:'↓',dx:0,dy:1},{id:'right' as const,name:'向右走',mark:'→',dx:1,dy:0}];
function loadEngine(level:number,fresh?:boolean){if(!fresh)try{const saved=localStorage.getItem(`${SAVE}.${level}`);if(saved){const e=VikingEngine.fromSave(JSON.parse(saved));if(e&&e.snapshot.levelIndex===level)return e;}}catch{/* Invalid or unavailable storage starts at the original bed. */}return new VikingEngine(level);}
function statusFor(s:VikingSnapshot){if(s.phase==='score')return `已找到出口！散落物 ${s.score.pickupPercent}%，物件复原 ${s.score.objectPercent}%。不用全部收集也能过关。`;if(s.phase==='replay')return `正向回放：已重演 ${s.replayCursor} / ${s.replayTotal} 条动作。`;if(s.phase==='replayDone'||s.phase==='complete')return s.levelIndex===6?'第七日的回忆走完了。终章已到，仍可重玩挑战更高评分。':'这一日的回放结束了，可以前往下一关。';if(s.lastAction?.change==='repair')return '物件已复原。它现在会挡路，离开后不能直接走回来。';if(s.lastAction?.change==='pickup')return '找回了一件散落物，这格仍然可以通行。';if(s.lastAction?.blockedBy==='object')return '复原的物件挡住了路。试试绕行，或撤销上一步。';if(s.lastAction?.blockedBy==='wall')return '这里是墙。墙上的碎物只能从它正下方向上碰触。';return `回溯第 ${s.actionCount} 步：从床出发，沿痕迹找到南边出口。`;}
export default function VikingGame(props:GameProps){return <VikingRound key={`${props.level}:${props.resetToken}`} {...props}/>;}
function VikingRound({level,paused,freshStart,hintToken,undoToken,onComplete,onStatus}:GameProps){
 const [engine]=useState(()=>loadEngine(level,freshStart)),[view,setView]=useState(()=>engine.snapshot),[intro,setIntro]=useState(()=>engine.snapshot.actionCount===0&&engine.snapshot.phase==='playing'),[zoom,setZoom]=useState(false),[replayRunning,setReplayRunning]=useState(false),[inactive,setInactive]=useState(false),[saved,setSaved]=useState(true),[message,setMessage]=useState(()=>engine.snapshot.phase!=='playing'?statusFor(engine.snapshot):engine.snapshot.actionCount?'已恢复这一日的行走进度。':'醒来时只记得零碎的片段。先读一读这一天的回忆。');
 const callbacks=useRef({onComplete,onStatus}),notified=useRef(false),hint=useRef(hintToken),undo=useRef(undoToken),pointer=useRef<{x:number;y:number;type:string}|null>(null),scroll=useRef<HTMLDivElement>(null),board=useRef<SVGSVGElement>(null);callbacks.current={onComplete,onStatus};
 const locked=paused||inactive||intro,playing=view.phase==='playing',replaying=view.phase==='replay',finished=!playing,cell=32,cleared=new Set(view.cleared),map=view.level;
 function publish(next:VikingSnapshot,text?:string){setView(next);setMessage(text??statusFor(next));}
 function move(dir:Direction){if(locked)return;if(replaying){setReplayRunning(false);publish(engine.skipReplay());return;}if(!playing)return;publish(engine.move(dir));}
 function restart(){if(paused||engine.snapshot.phase!=='playing')return;setReplayRunning(false);setIntro(false);notified.current=false;publish(engine.reset(),'已回到床边，物件、衣物和行走记录全部恢复。');}
 function replay(){if(locked)return;publish(engine.beginReplay());setReplayRunning(true);}
 function skip(){if(locked)return;setReplayRunning(false);publish(engine.skipReplay());}
 function key(e:KeyboardEvent){if(e.altKey||e.ctrlKey||e.metaKey)return;const d=({ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',a:'left',s:'down',d:'right'} as Record<string,Direction>)[e.key];if(d){e.preventDefault();if(!e.repeat&&!e.altKey&&!e.ctrlKey&&!e.metaKey)move(d);}else if(e.key.toLowerCase()==='r'&&!e.repeat){e.preventDefault();restart();}}
 function pointerDown(e:PointerEvent<SVGSVGElement>){if(zoom&&e.pointerType==='touch')return;pointer.current={x:e.clientX,y:e.clientY,type:e.pointerType};}
 function pointerUp(e:PointerEvent<SVGSVGElement>){const p=pointer.current;pointer.current=null;if(!p||locked||!playing)return;const dx=e.clientX-p.x,dy=e.clientY-p.y;if(Math.max(Math.abs(dx),Math.abs(dy))>24){move(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');return;}const box=e.currentTarget.getBoundingClientRect(),x=Math.floor((e.clientX-box.x)/box.width*map.width),y=Math.floor((e.clientY-box.y)/box.height*map.height),d=directions.find(d=>view.player.x+d.dx===x&&view.player.y+d.dy===y);if(d)move(d.id);else setMessage('只能走向相邻一格；也可以使用下方的大方向按钮。');}
 useEffect(()=>{callbacks.current.onStatus(message);},[message]);
 useEffect(()=>{try{localStorage.setItem(`${SAVE}.${level}`,JSON.stringify(engine.exportSave()));setSaved(true);}catch{setSaved(false);}},[view,engine,level]);
 useEffect(()=>{if(finished&&!paused&&!notified.current){notified.current=true;callbacks.current.onComplete();}},[finished,paused]);
 useEffect(()=>{if(!replaying||!replayRunning||paused||inactive)return;const timer=window.setInterval(()=>publish(engine.stepReplay()),220);return()=>clearInterval(timer);},[replaying,replayRunning,paused,inactive,engine]);
 useEffect(()=>{const blur=()=>{setInactive(true);pointer.current=null;},focus=()=>setInactive(document.hidden),visibility=()=>{setInactive(document.hidden);if(document.hidden)pointer.current=null;};window.addEventListener('blur',blur);window.addEventListener('focus',focus);document.addEventListener('visibilitychange',visibility);return()=>{window.removeEventListener('blur',blur);window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',visibility);pointer.current=null;};},[]);
 useEffect(()=>{if(hint.current===hintToken)return;hint.current=hintToken;if(!paused)setMessage('复原家具之前，先看离开后会不会堵住自己的回头路。墙饰要站在正下方向上碰；出口不要求100%收集。');},[hintToken,paused]);
 useEffect(()=>{if(undo.current===undoToken)return;undo.current=undoToken;if(!locked&&playing&&view.canUndo)publish(engine.undo(),'已撤销上一条行动，位置和物件一起恢复。');},[undoToken,locked,playing,view.canUndo,engine]);
 useEffect(()=>{const host=window as unknown as {__vikingRead?:()=>VikingSnapshot&{intro:boolean;paused:boolean;replayRunning:boolean}};host.__vikingRead=()=>({...engine.snapshot,intro,paused:paused||inactive,replayRunning});return()=>{delete host.__vikingRead;};},[engine,intro,paused,inactive,replayRunning]);
 return <section onKeyDown={key} className="vk-game" data-vk-level={level} data-vk-phase={view.phase} data-vk-actions={view.actionCount} data-vk-x={view.player.x} data-vk-y={view.player.y}>
  <header className="vk-heading"><div><span>DRUNKEN VIKING · {map.day}</span><h3>把昨夜，倒着走一遍。</h3></div><b>{String(level+1).padStart(2,'0')}<small>/ 07</small></b></header>
  <p className="vk-lead">从床边回溯到南门。拾起散落物，把碎物复原；修好的家具会重新挡住路。</p>
  {intro?<article className="vk-story" aria-label="这一日的故事"><h4>第 {level+1} 日 · {map.day}</h4>{VIKING_STORY[level].map((line,i)=><p key={i}>{line}</p>)}<button disabled={paused} onClick={()=>{setIntro(false);setMessage('回忆开始了。沿上下左右一格一格走，寻找南边的出口。');board.current?.focus();}}>开始回溯</button></article>:<details className="vk-day-story"><summary>这一日的故事</summary>{VIKING_STORY[level].map((line,i)=><p key={i}>{line}</p>)}</details>}
  <div className="vk-stats"><span>行动 <b>{view.actionCount}</b></span><span>散落物 <b>{view.liveScore.pickups}/{view.liveScore.totalPickups}</b></span><span>复原 <b>{view.liveScore.objects}/{view.liveScore.totalObjects}</b></span><span>{paused||inactive?'已暂停':replaying?'时间向前':playing?'时间倒流':'已抵达出口'}</span></div>
  <div className="vk-tools"><span>20 × 15 原作地图 · 第{view.player.y+1}行 第{view.player.x+1}列</span><button disabled={paused} onClick={()=>{setZoom(!zoom);pointer.current=null;}}> {zoom?'查看全盘':'放大地图'} </button></div>
  <div ref={scroll} className={`vk-scroll ${zoom?'vk-zoom':''}`}><svg ref={board} className="vk-board" viewBox="0 0 640 480" role="group" aria-label="维京回溯地图，方向键或相邻格移动" tabIndex={0} onPointerDown={pointerDown} onPointerUp={pointerUp} onPointerCancel={()=>{pointer.current=null;}}>
   <rect width="640" height="480" fill="#e4dcc5"/>
   {map.layers.Background.map((bg,i)=>{const x=(i%20)*cell,y=Math.floor(i/20)*cell,wall=map.layers.Walls[i]>0,good=map.layers.Good[i],broken=map.layers.Broken[i],done=cleared.has(i),bed=map.layers.Bed[i]>0,pickup=broken>0&&good===0,exit=i===290,kind=wall?'墙':bed?'床':good>0?(done?'复原物件':'碎物'):pickup?(done?'拾取后的空地':'散落物'):'空地';return <g key={i} transform={`translate(${x} ${y})`} data-vk-cell={i} data-vk-kind={kind}>
    <title>第{Math.floor(i/20)+1}行，第{i%20+1}列，{kind}</title><rect width="32" height="32" fill={wall?'#646551':bg===21?'#d5dbbd':'#e9dec4'} stroke={wall?'#77775d':'#daceb0'} strokeWidth=".6"/>
    {wall&&<path d="M0 16h32M10 0v16M23 16v16" stroke="#8a8a6c" fill="none"/>}
    {exit&&<><rect x="2" y="2" width="28" height="28" rx="4" fill="#bfd39f"/><path d="M16 5v20m-7-8 7 8 7-8" stroke="#44694c" strokeWidth="3" fill="none"/></>}
    {bed&&<><rect x="4" y="6" width="24" height="22" rx="3" fill="#9a744c"/><rect x="7" y="8" width="18" height="7" rx="2" fill="#f8f0d9"/><path d="M6 17h20v8H6" fill="#708c8b"/></>}
    {broken>0&&!done&&(pickup?<><path d="m8 8 5-3q3 4 6 0l5 3 4 8-6 3-2-4v13H11V15l-3 4-5-3Z" fill="#70a4a1" stroke="#42716d" strokeWidth="1"/></>:<><path d="m7 10 7 7-5 9m8-20 6 8-6 5m3 5 8-3" stroke="#b2663e" strokeWidth="3" strokeLinecap="round" fill="none"/><circle cx="25" cy="8" r="2" fill="#d29d5b"/></>)}
    {good>0&&done&&<><rect x="4" y="4" width="24" height="24" rx={good%3===0?9:4} fill="#7d9270" stroke="#486447" strokeWidth="1.5"/><path d="m9 16 5 5 10-11" stroke="#f5f4dd" strokeWidth="2.5" fill="none"/></>}
    {map.layers.Decor[i]>0&&!wall&&!bed&&!broken&&<circle cx="16" cy="16" r="3" fill="#aaa484" opacity=".5"/>}
   </g>;})}
   <g transform={`translate(${view.player.x*32} ${view.player.y*32})`} data-vk-player="true"><circle cx="16" cy="17" r="13" fill="#f5f0d9" stroke="#805334" strokeWidth="2"/><path d="M7 18h18l-3 11H10Z" fill={view.clothed?'#547e84':'#c19161'}/><circle cx="16" cy="12" r="8" fill="#dbaa77"/><path d="M8 10q8-12 16 0" fill="#656d51"/><path d="m10 15 6 8 6-8" fill="#995c36"/><path d="M11 10h10" stroke="#d9c785" strokeWidth="2"/></g>
  </svg></div>
  <p className="vk-hintline">{zoom?'放大后可滑动查看地图，方向按钮仍可移动。':'点相邻格或使用大方向键移动；小屏幕可放大查看。'} 墙上碎物只能从下方向上碰触。</p>
  <div className="vk-legend"><span><i className="vk-person">●</i>自己</span><span><i>╱</i>碎物</span><span><i className="vk-solid">✓</i>已复原，会挡路</span><span><i className="vk-clothes">衣</i>散落物</span></div>
  <div className="vk-controlrow"><div className="vk-dpad" aria-label="行走方向">{directions.map(d=><button key={d.id} disabled={locked||!playing} aria-label={d.name} onClick={()=>move(d.id)}>{d.mark}</button>)}</div><p className={`vk-message ${finished?'vk-success':''}`} role="status">{message}</p></div>
  {finished&&<article className="vk-scorecard" aria-label="这一日的评分"><h4>第 {level+1} 日 · 已找到出口</h4><div className="vk-scoregrid"><div><b>{view.score.pickupPercent}%</b><span>散落物 {view.score.pickups}/{view.score.totalPickups}</span></div><div><b>{view.score.objectPercent}%</b><span>物件复原 {view.score.objects}/{view.score.totalObjects}</span></div></div><p>出口就是过关条件。没有达到100%也能继续；更高评分留给下一次回溯，点顶部“重来”可重走这一日。</p><div className="vk-replay-actions">{view.phase==='score'&&<button disabled={locked} onClick={replay}>观看正向回放</button>}{replaying&&<><button disabled={paused||inactive} onClick={()=>setReplayRunning(!replayRunning)}>{replayRunning?'暂停回放':'继续回放'}</button><button disabled={paused||inactive} onClick={skip}>跳过回放</button></>}{(view.phase==='replayDone'||view.phase==='complete')&&<button disabled={locked} onClick={replay}>再看一次回放</button>}</div>{replaying&&<p className="vk-replay-progress">已回放 {view.replayCursor}/{view.replayTotal} 条动作</p>}{level===6&&(view.phase==='replayDone'||view.phase==='complete')&&<div className="vk-ending" aria-label="第七日结局"><h4>七日篇章 · 终章</h4><p>最后一天的路线已经重现。感谢同行，维京人的故事暂告一段落。</p><p>可以返回其他日子，重新寻找更完整的回忆。</p></div>}</article>}
  {!saved&&<p role="alert" className="vk-save-warning">浏览器无法保存这次进度；当前这一局仍可继续。</p>}
  <details><summary>规则、回放与原作说明</summary><p>原作7天，每天一张20×15地图，同一座屋子里的墙和物件布置会改变。你从床开始逆着时间行走：经过碎物让它复原，经过散落物把它拾起。复原物件会成为障碍；站在刚复原的格子上仍可离开。</p><p>墙面物件只能从正下方向上碰触。走出地图边界即可完成这一日，散落物与复原率各自评分，没有强制100%门槛。可随时重走，或在行走中撤销。</p><p>正向回放保留原作的指令规则：已复原的家具不再阻挡回放行走，所以曾经撞家具的指令可能变成一步移动。回放可以暂停、跳过、重看；暂停游戏、切到后台或离开页面会停止自动推进。</p><p>中文翻译保留原作关于酒后回忆的七日故事。人物、物件与衣着用本站符号重画，不包含原图、录音、字体或Phaser。地图与MIT源码保持原版本；本站增加了经过动作校验的本地续玩存档。</p><p>改编自 Cong 的 Drunken Viking，固定版本356d8e19。<a href="./viking-LICENSE.txt" target="_blank" rel="noreferrer">原作完整MIT许可证</a>。</p></details>
 </section>;
}
