// SPDX-License-Identifier: MIT
import type {
  Oscillator,
  WaveCoefficients,
  WaveLevel,
} from "./waveStudioLogic";
const target = (cosine: number[], sine = [0, 0, 0, 0]): WaveCoefficients => ({
  cosine,
  sine,
});
const full = {
  frequencies: [1, 2, 3, 4],
  amplitudes: [0, 1, 2, 3],
  phases: [0, 90, 180, 270] as const,
};
export const waveStudioLevels: readonly WaveLevel[] = [
  {
    ...full,
    id: "ws-01",
    title: "一个完整周期",
    lesson: "频率 1 表示横轴一圈内完成一次振荡。先打开振幅。",
    oscillators: 1,
    amplitudes: [0, 1],
    phases: [0],
    target: target([1, 0, 0, 0]),
    activeRequired: 1,
    budget: 1,
  },
  {
    ...full,
    id: "ws-02",
    title: "数出三个周期",
    lesson: "频率决定一圈内有几个周期，不改变波峰高度。",
    oscillators: 1,
    amplitudes: [0, 1],
    phases: [0],
    target: target([0, 0, 1, 0]),
    activeRequired: 1,
    budget: 1,
  },
  {
    ...full,
    id: "ws-03",
    title: "振幅三格",
    lesson: "振幅改变峰高，频率保持周期数。",
    oscillators: 1,
    phases: [0],
    target: target([3, 0, 0, 0]),
    activeRequired: 1,
    budget: 3,
  },
  {
    ...full,
    id: "ws-04",
    title: "四分之一圈",
    lesson: "cos(θ+90°) = −sin(θ)。相位改变波形的起点与方向。",
    oscillators: 1,
    target: target([0, 0, 0, 0], [-2, 0, 0, 0]),
    activeRequired: 1,
    budget: 2,
  },
  {
    ...full,
    id: "ws-05",
    title: "半圈翻转",
    lesson: "180° 把余弦系数变成负数，这不是负的振幅。",
    oscillators: 1,
    target: target([0, -2, 0, 0]),
    activeRequired: 1,
    budget: 2,
  },
  {
    ...full,
    id: "ws-06",
    title: "正向正弦",
    lesson: "270° 对应正的正弦系数。读数字可以辨认相位方向。",
    oscillators: 1,
    target: target([0, 0, 0, 0], [0, 0, 1, 0]),
    activeRequired: 1,
    budget: 1,
  },
  {
    ...full,
    id: "ws-07",
    title: "同相增强",
    lesson: "单台振幅最多 2。两台同频同相才能得到系数 3。",
    oscillators: 2,
    frequencies: [1, 2],
    amplitudes: [0, 1, 2],
    phases: [0, 180],
    target: target([3, 0, 0, 0]),
    activeRequired: 2,
    budget: 3,
  },
  {
    ...full,
    id: "ws-08",
    title: "反相相消",
    lesson: "必须开启两台。用 2 与反相的 1 留下净振幅 1。",
    oscillators: 2,
    frequencies: [1, 2],
    amplitudes: [0, 1, 2],
    phases: [0, 180],
    target: target([0, 1, 0, 0]),
    activeRequired: 2,
    budget: 3,
  },
  {
    ...full,
    id: "ws-09",
    title: "两种谐波",
    lesson: "不同频率的系数独立相加。分别匹配余弦与正弦列。",
    oscillators: 2,
    frequencies: [1, 2, 3],
    amplitudes: [0, 1, 2],
    target: target([2, 0, 0, 0], [0, -1, 0, 0]),
    activeRequired: 2,
    budget: 3,
  },
  {
    ...full,
    id: "ws-10",
    title: "三台协奏",
    lesson: "恰好开启三台且总振幅不超过 3，分配增强与独立谐波。",
    oscillators: 3,
    frequencies: [1, 2, 3],
    amplitudes: [0, 1, 2],
    target: target([1, 0, 2, 0]),
    activeRequired: 3,
    budget: 3,
  },
  {
    ...full,
    id: "ws-11",
    title: "相消的余量",
    lesson: "三台必须开启。用反相配对得到一个小系数，同时保留另一谐波。",
    oscillators: 3,
    target: target([0, -1, 0, 0], [0, 0, 0, 1]),
    activeRequired: 3,
    budget: 4,
  },
  {
    ...full,
    id: "ws-12",
    title: "完整谐波配方",
    lesson: "在总振幅 5 内，用三台同时实现不同频率与方向的三个分量。",
    oscillators: 3,
    target: target([2, 0, 0, -2], [0, 1, 0, 0]),
    activeRequired: 3,
    budget: 5,
  },
];
const o = (
  frequency: number,
  amplitude: number,
  phase: Oscillator["phase"] = 0,
): Oscillator => ({ frequency, amplitude, phase });
const certificates: readonly (readonly Oscillator[])[] = [
  [o(1, 1)],
  [o(3, 1)],
  [o(1, 3)],
  [o(1, 2, 90)],
  [o(2, 2, 180)],
  [o(3, 1, 270)],
  [o(1, 1), o(1, 2)],
  [o(2, 2), o(2, 1, 180)],
  [o(1, 2), o(2, 1, 90)],
  [o(1, 1), o(3, 1), o(3, 1)],
  [o(2, 2, 180), o(2, 1), o(4, 1, 270)],
  [o(1, 2), o(2, 1, 270), o(4, 2, 180)],
];
export function getWaveCertificate(index: number): Oscillator[] | null {
  return Number.isInteger(index) && certificates[index]
    ? certificates[index].map((o) => ({ ...o }))
    : null;
}
